### ISSUE TITLE
[Docs]: Change Middleware

### ISSUE THREAD

**Issue by pepijnweijers** [amannn/next-intl#1002]
### Link to page

https://next-intl-docs.vercel.app/docs/getting-started/app-router#middleware

### Describe the problem

Right now the docs has the following config for the middleware:
```js
export const config = {
  matcher: ['/', '/(de|en)/:path*']
};
```

The problem with this configuration is that it assumes every first parameter is the language. For instance, if you have a page `/example` and are working with `localePrefix: 'as-needed'`, it will incorrectly interpret 'example' as your language. Additionally, if I'm using this configuration, it doesn't support dynamic `<Link>` components. Therefore, if you're on the language `/de` and link the user to the page 'example', it will generate `/example` instead of `/de/example`.

But I feel like the old middleware works better for Next.js:
```js
export const config = {
    matcher: ['/((?!api|_next|_vercel|.*\\..*).*)']
};
```

Also a suggestion to make `localePrefix: 'as-needed'`, I believe this is better for SEO ;)

**Comment by amannn** [comment]
We initially had `localePrefix: 'as-needed'` as the default, but there are some gotchas here: [Pathnames without a locale prefix](https://next-intl-docs.vercel.app/docs/routing/middleware#matcher-no-prefix).

Based on feedback from users, we've switched to `localePrefix: 'always'` as the default, as there's typically less to consider for this to work reliably.

Thanks for the feedback though!
