### ISSUE TITLE
Custom namespace separator character.

### ISSUE THREAD

**Issue by tnphis** [amannn/next-intl#105]
Greetings. I've recently tried using next-intl for a migrated project with some pre-existing locale files and had issues with a lot of messages not being resolved. After some research, it turned out that the period (".") characted is hardcoded as the namespace separator, and, since we had a lot of those in the message ids in our existing locale files, the resolver must have been looking for nested objects instead of trying to translate the string itself.

Would it be possible to add an option to have a custom namespace separator to avoid such issues? Otherwise, a lot of id renaming would be needed (which would have to be done semi-manually in the js files).

Also, as it this hardcode caused some strange behaviour, this might be worth mentioning in the faq / docs. Unless I missed it somewhere.

**Comment by amannn** [comment]
Hi @tnphis and thank you for your report!

Unfortunately the namespace separator is currently not intended to be customized. With the recently introduced TypeScript support for validating message keys it is also not possible to introduce a configuration option for this unfortunately.

However I've set up a PR to validate namespace keys to avoid confusion in regards to this in the future: https://github.com/amannn/next-intl/pull/106. Does this look useful to you?

**Comment by amannn** [comment]
Alright! I'm sorry to hear about your frustration, but thank you for taking the time to report your finding so others can avoid this in the future.

I've just merged the improved error handling so this will be part of the next release.

**Comment by amannn** [comment]
This question came up again in https://github.com/amannn/next-intl/discussions/148#discussioncomment-4274218, I've linked to [a simple transformation script](https://codesandbox.io/s/hungry-panka-psnuee?file=/src/App.js) that converts the namespaces to a nested structure.
