### ISSUE TITLE
`null` translation values causes `validateMessagesSegment` to fail

### ISSUE THREAD

**Issue by dzhng** [amannn/next-intl#109]
**Describe the bug**
If a translation file contain a null key, `IntlProvider` will now throw an error on startup.

**To Reproduce**
Pass in any messages object with a `null` as one of the values.

**Expected behavior**
This is a breaking change - previous versions of `next-intl` did not have this behavior.

**Comment by amannn** [comment]
Hi @dzhng and thanks for the report! I've created https://github.com/amannn/next-intl/pull/110 to fix this, as this was not intentional.

I'd be curious though why you need `null` for a message value?

**Comment by dzhng** [comment]
Thanks for the quick turnaround!

The translation service I use (Phrase) auto exports empty translations as `null` instead of empty string. So we're stuck with nulls.

Maybe there's a way to configure it (the settings are a bit convoluted), but IMO this lib should just be able to work with one of the more popular translation services out of the box.

**Comment by amannn** [comment]
Yep, I agree. Thank you for providing some background!
