### ISSUE TITLE
Pass `request` to `getRequestConfig()`

### ISSUE THREAD

**Issue by llamadeus** [amannn/next-intl#1145]
### Is your feature request related to a problem? Please describe.

To fetch the user's locale from the database and apply it to the `next-intl` config, I need to read values from the incoming request. However, there is no way to access the request from `getRequestConfig()`.

### Describe the solution you'd like

Pass the `request` as a parameter to `getRequestConfig()`.

### Describe alternatives you've considered

Apply the `getRequestConfig()` middleware later so that my own middleware was able to run and inject necessary headers into the request.

**Comment by amannn** [comment]
`i18n.ts` (with its `getRequestConfig`) is called during the RSC render (see [docs](https://next-intl-docs.vercel.app/docs/usage/configuration#i18nts)). You can read from `headers()` or `cookies()` there, but the raw request is not available for Server Components (only in the middleware).

**Comment by llamadeus** [comment]
Thank you so much for your quick reply and the hint. I must've missed this in the docs so please excuse the feature request.

**Comment by amannn** [comment]
I think I'll add a hint about this to make it a bit more explicit. Good that you've brought this up @llamadeus!
