### ISSUE TITLE
Allow for handling optional/invalid numbers on plural interpolation

### ISSUE THREAD

**Issue by noahbald** [amannn/next-intl#1163]
### Is your feature request related to a problem? Please describe.

I'd like to be able to handle the case where a given value is `undefined`, `null`, or `NaN`.
Right now if I try the following
```ts
// {years, plural, =0 {} =1 {# year} undefined {--} other {# years}}
t('years', { years: undefined })
```
I get `NaN years` as an output

### Describe the solution you'd like

If I do provide `undefined` or `NaN` as my translation value, I'd like it to use the translation given in `undefined {--}` or `NaN {--}`

### Describe alternatives you've considered

I can create a seperate translation to handle this
```ts
years
  ? t('years', { years })
  : t('years-fallback')
```

**Comment by amannn** [comment]
Thanks for the feature proposal! The ICU standard doesn't support special-casing of non-defined values of numbers as far as I know, therefore `next-intl` doesn't either. The alternative you've mentioned is the one I'd recommend in this case!
