### ISSUE TITLE
[Docs]: It is not clear to add pathnames to middleware file if you want to use localized pathnames

### ISSUE THREAD

**Issue by qublaidev** [amannn/next-intl#1174]
### Link to page

https://next-intl-docs.vercel.app/docs/routing#pathnames

### Describe the problem

I followed the docs in tutorial about localized pathnames and created the navigation.ts and middleware.ts files accordingly but when testing the localized paths returned 404.

The solution was under the [localized pathnames revalidation accordion tab](https://next-intl-docs.vercel.app/docs/routing#localized-pathnames-revalidation) showing that you should add pathnames to next-intl middleware.

It would be more clear if it is shown in the actual section not under a tab

**Comment by amannn** [comment]
This is covered right at the beginning of the routing page: [Shared configuration](https://next-intl-docs.vercel.app/docs/routing#shared-configuration).

I do agree though that it's currently too easy to provide configuration either only to the navigation APIs or the middleware. I'm working on a small API revamp in https://github.com/amannn/next-intl/issues/779 that should help with this in the future.

Thanks for raising this!
