### ISSUE TITLE
Support self closing tags

### ISSUE THREAD

**Issue by apfelbox** [amannn/next-intl#118]
### Is your feature request related to a problem? Please describe.

When using rich formatting in translations, it would be great to be able to use tags without content, especially: `<br />`

Using `Test<br></br>Test2` is pretty annoying.

### Describe the solution you'd like

The tags used for providing rich formatting already work great, so self-closing tags should just be usable the same way.

### Describe alternatives you've considered

Using `<br></br>` works, but is a lot of noise in the translation texts.

**Comment by amannn** [comment]
Hi @apfelbox and thanks for raising the issue!

We're currently relying on [`icu-messageformat-parser`](https://github.com/formatjs/formatjs/tree/main/packages/icu-messageformat-parser) for parsing messages. They've decided to [not introduce this feature](https://github.com/formatjs/formatjs/issues/3254) so I'd also like to keep `next-intl` aligned with that to avoid fragmentation.

Note however that from what I'm seeing possibly you're looking for something like this if you want multiple paragraphs:

```
<p>Test</p>
<p>Test2</p>
```

That would lead to more semantic markup.

**Comment by apfelbox** [comment]
Hi @amannn,

thanks for the response. Yeah, that is quite unfortunate. 

Changing it into paragraphs wouldn't help here, as I can't separate an address into separate paragraphs for example.

**Comment by amannn** [comment]
> Changing it into paragraphs wouldn't help here, as I can't separate an address into separate paragraphs for example.

Ah, got it! Yep, that's definitely a valid use case for `<br />` and I see your point, the self closing tag would definitely be helpful here.
