### ISSUE TITLE
Type utility for message key

### ISSUE THREAD

**Issue by coffeedoughnuts** [amannn/next-intl#119]
### Is your feature request related to a problem? Please describe.

I want to write a generic <Text /> component that accepts a message key as a prop.

### Describe the solution you'd like

I'd like a utility to help me write that component's props in a type-safe way, e.g.

```typescript
import { MessageKey, useTranslations } from 'next-intl';

interface Props {
  message: MessageKey;
}

function Text(props: Props) {
  const { message } = props;
  const t = useTranslations();
  return <span>{t(message)}</span>;
}
```

### Describe alternatives you've considered

The library doesn't export any utility types that I can see, so I attempted this:

```
type MessageKey = Parameters<ReturnType<typeof useTranslations>>[0]
```

but because the hook allows a partial key string it wasn't type-safe. What I'm after is a fully-resolved message key (perhaps `AbsoluteMessageKey` would be a better name for the type?)

**Comment by amannn** [comment]
Hmm, can you tell me a bit more about your use case?

This might be a bit difficult to achieve, the API of `next-intl` is really based on the idea that `useTranslations()` is called in the same component where a key is referenced. This issue was related: https://github.com/amannn/next-intl/issues/92. Apart from the type story this kind of usage might also make it harder to achieve future optimisations, so I'm hesistant to support this use case.

This might be the best workaround for you:

```tsx
function Parent() {
  const t = useTranslations();
  return <Text>{t('message')}</Text>;
}

function Text({children}) {
  return <span>{children}</span>;
}
```

**Comment by coffeedoughnuts** [comment]
Hi, thanks for getting back to me

I've been putting together a few typography-focussed components for a design system (different types of headers etc.) and was wondering if there was a place for a generic <Text /> component so that all text in our app was wrapped with a component at some point. When weighing up the advantages and disadvantages, I thought that disallowing the 'children' prop and instead making people provide a message key would be another way to ensure people didn't mistakenly put text in our app that wasn't covered by the translations corpus.

It's not an essential pattern by any means, so not so important if you see maintenance issues with supporting that use case.

**Comment by amannn** [comment]
I see. Yep, I think especially when you want to validate that only valid keys are passed to translation functions, you want all of those calls in your app code and not your design system. Hope this helps!

**Comment by kachkaev** [comment]
Has anyone found a solution to this? I am migrating a project from `next-i18next` and have to replace string message keys with the typed ones in a few places. I know it’s better to have translations passed than individual messages, it’s just a bit hard to refactor everything in one go.
