### ISSUE TITLE
Fails when `i18n.defaultLocale` is not defined in `next.config.js`

### ISSUE THREAD

**Issue by noahflk** [amannn/next-intl#121]
### Description

I figure out the locale myself in `getServerSideProps`. And i don't want to use Next's internationalized routing. So I get this error.

```
[next-international] 'i18n.defaultLocale' not defined in 'next.config.js'
```

### Reproduction

Remove `i18n` object from `next.config.js`

**Comment by amannn** [comment]
Hello @noahflk,

You can pass an explicit `locale` to `NextIntlProvider` as mentioned in [the docs](https://next-intl-docs.vercel.app/docs/installation).

I'm unfortunately only able to provide more help when you follow the issue template and you include a CodeSandbox reproduction.

If you can't find a fix for your issue, please open a new issue with the reproduction. Thank you for your understanding.
