### ISSUE TITLE
[Docs]: Confused about 2 domains

### ISSUE THREAD

**Issue by angel-luis** [amannn/next-intl#1211]
### Describe the problem

I don't know why my search engine follows me to: https://next-intl-docs-git-feat-next-13-rsc-next-intl.vercel.app while the official page is supposed to be: https://next-intl-docs.vercel.app. Is that in purpose?

**Comment by amannn** [comment]
I'm not sure either, that page returns a `X-Robots-Tag: noindex` header. I also [don't get any results](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fnext-intl-docs-git-feat-next-13-rsc-next-intl.vercel.app&oq=site%3Ahttps%3A%2F%2Fnext-intl-docs-git-feat-next-13-rsc-next-intl.vercel.app&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg60gEIMTMxOWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8) on Google for that site.

I'm going to close this for the time being as this seems non-actionable.

**Comment by angel-luis** [comment]
@amannn I'm not sure how can you fix that, but the first result in DuckDuckGo is the link that I've pointed, instead of the official. 

<img width="887" alt="image" src="https://github.com/user-attachments/assets/4e630e1d-6069-4952-b5cf-fb8f88149f56">

**Comment by amannn** [comment]
That's interesting, thanks for the hint. I've added a 301 redirect now, hopefully that will nudge DuckDuckGo to show the right page in the future.
