### ISSUE TITLE
t.rich/markup: react/no-unstable-components

### ISSUE THREAD

**Issue by stevensacks** [amannn/next-intl#1218]
### Is your feature request related to a problem? Please describe.

The `t.rich()` and `t.markup()` functions violate the [react/no-unstable-nested-components](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md) ESLint rule.
```ts
{t.rich('messageKey', {
  code: (chunks) => (
         ~~~~~~
    <code className="font-mono font-bold">{chunks}</code>
  ),
})}
```
> ESLint: Do not define components during render. React will see a new component type on every render and destroy the entire subtree’s DOM nodes and state (https://reactjs.org/docs/reconciliation.html#elements-of-different-types). Instead, move this component definition out of the parent component “HomePage” and pass data as props. If you want to allow component creation in props, set allowAsProps option to true.(react/no-unstable-nested-components)

Disabling this ESLint rule is a bad idea:
>**When Not To Use It**
>If you are not interested in preventing bugs related to re-creation of the nested components or do not care about optimization of virtual DOM.

This issue does not occur with react-i18next [Trans component](https://react.i18next.com/latest/trans-component#using-with-react-components). This reconciliation issue may very well be why they use the Trans component to do JSX replacement of tags.

### Describe the solution you'd like

A solution in next-intl that allows for swapping out of tags that adheres to the rules and does not result in unstable nested components.

### Describe alternatives you've considered

The only alternative is to use a different i18n library that does not have this issue. I'd like to see next-intl provide a solution for this so it remains a viable alternative to other i18n libraries for Next.js.

**Comment by amannn** [comment]
This is a false positive, rich text functions are not React components but actual functions that are invoked during rendering. Ideally the ESLint rule would be able to discover this since no `props` are passed to the function but `chunks`.

I suggest you disable the rule accordingly where relevant.

**Comment by olayinkasf** [comment]
This would be a valuable feature to have. Consider a scenario where specific styling is required for a brand name across multiple translations. Currently, the syntax requires a full closing tag (e.g., `<brandname></brandname>`), which feels unnecessarily verbose. Supporting a self-closing or single-tag syntax like `<brandname />` would be an improvement IMO.
