### ISSUE TITLE
[Docs]: Middleware with Supabase Auth integration is outdated

### ISSUE THREAD

**Issue by harrybawsac** [amannn/next-intl#1228]
### Link to page

https://next-intl-docs.vercel.app/docs/routing/middleware#example-integrating-with-supabase-authentication

### Describe the problem

Recently Supabase updated their SSR package. The `cookies` object has changed.

More information: https://supabase.com/docs/guides/auth/server-side/nextjs

**Comment by amannn** [comment]
Thanks for the hint!

Do you by chance have a working implementation and would like to propose an update to [the middleware page](https://github.com/amannn/next-intl/blob/main/docs/pages/docs/routing/middleware.mdx)?

**Comment by harrybawsac** [comment]
Yeah, I have a working project. Will make a proposal tomorrow!
