### ISSUE TITLE
Is it possible to load more than one translation?

### ISSUE THREAD

**Issue by pedroota** [amannn/next-intl#1230]
### Is your feature request related to a problem? Please describe.

I've always wondered if is it possible to load more than one translation at a time, for example:

`
const home = () => {
  const t = useTranslations(["HomePage", "utils"])

  return <p>{t('home.title')} {t('utils.buy_now')}</p

}
`

### Describe the solution you'd like

`const home = () => {
  const t = useTranslations(["HomePage", "utils"])

  return <p>{t('home.title')} {t('utils.buy_now')}</p

}`

### Describe alternatives you've considered

`const home = () => {
  const t = useTranslations(["HomePage", "utils"])

  return <p>{t('home.title')} {t('utils.buy_now')}</p

}`

**Comment by amannn** [comment]
This has been discussed a few times already: https://github.com/amannn/next-intl/issues/217
