### ISSUE TITLE
NextJS 15 support

### ISSUE THREAD

**Issue by mp3por** [amannn/next-intl#1248]
### Is your feature request related to a problem? Please describe.

I am using NextJS RC.0 with NextIntl 3.17.2. Everything works as expected so far. 

However - due to dependency specifications I get the following error when I try to install things (ex: npx shadcn-ui@latest add avatar):

```
Command failed with exit code 1: npm install @radix-ui/react-avatar
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: next-intl@3.17.2
npm ERR! Found: next@15.0.0-rc.0
npm ERR! node_modules/next
npm ERR!   peer next@"^14.0.0 || ^15.0.0-rc.0" from next-firebase-auth-edge@1.7.0-canary.6
npm ERR!   node_modules/next-firebase-auth-edge
npm ERR!     next-firebase-auth-edge@"^1.7.0-canary.6" from the root project
npm ERR!   next@"15.0.0-rc.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0" from next-intl@3.17.2
npm ERR! node_modules/next-intl
npm ERR!   next-intl@"^3.17.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: next@14.2.5
npm ERR! node_modules/next
npm ERR!   peer next@"^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0" from next-intl@3.17.2
npm ERR!   node_modules/next-intl
npm ERR!     next-intl@"^3.17.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/velinkerkov/.npm/_logs/2024-08-11T08_03_31_829Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/velinkerkov/.npm/_logs/2024-08-11T08_03_31_829Z-debug-0.log
```

### Describe the solution you'd like

Please specify through the dependencies that this package works with NextJS RC.0.

### Describe alternatives you've considered

When I am installing packages I use `--legacy-peer-deps` until this is fixed.

**Comment by amannn** [comment]
Adding React RC versions to `peerDependencies` is unfortunately not that straightforward: https://x.com/phry/status/1811070395879149682.

I think for now the best option is to use `--legacy-peer-deps` and bump the peer dependency version once React 19 stable is out.

**Comment by amannn** [comment]
I'm going to close this in favor of https://github.com/amannn/next-intl/issues/1075
