### ISSUE TITLE
next-intl not working on old mac devices

### ISSUE THREAD

**Issue by MrFarhan** [amannn/next-intl#125]
### Description

Everything works fine in all devices except old mac devices especially with IOS 12.4.
![image](https://user-images.githubusercontent.com/26528236/188643226-7873cee1-9a1c-4b8e-a41d-1dcd1eebe2e9.png)

### Reproduction

To reproduce, open the same website on any other device it should show Hello world EN whereas in mac ios version 12.4 it will show Login.login`.

[Github repo](https://github.com/MrFarhan/next-intl-test.git).
A [Live URL](https://next-intl-test-one.vercel.app/)

Note: I have tested this on real device and emulator the issue is same on both.

### Expected behaviour

It should show Hello world EN

**Comment by amannn** [comment]
Hello @MrFarhan,

You might want to use the Safari inspector to get a hold of the error message that is thrown in the browser to analyze this. It's a bit hard to tell what's wrong with the blank screen. It could be that you're missing polyfills for this browser.

**Comment by amannn** [comment]
Yep, seems like you're missing at least one polyfill for `Intl.Locale` (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale#browser_compatibility)).

The mentioning of polyfills is quite small in the current docs, I hope I can extend this at some point. I've got a note about it in #72. Probably it would also be good if the error message was printed instead of crashing the app.

For now you can fix this by including the necessary polyfills.

**Comment by MrFarhan** [comment]
@amannn Do you have any idea about required policy fills? (like which polyfills are required as this is working fine on the latest devices but not working on OS 12.4.

I have tried following but nothing helped:
Added this script `              <Script
                src="https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver"
                strategy="beforeInteractive"
              />`
              
Installed below dependencies:
`    "@next/polyfill-module": "^12.2.5",`
  `  "@next/polyfill-nomodule": "^12.2.5",`
  
  I belief all required polyfills must be installed with the installation of next-intl .

**Comment by amannn** [comment]
> I have tried following but nothing helped:
Added this script <Script src="https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver" strategy="beforeInteractive" />

You're loading a polyfill for `IntersectionObserver`, but you need to load polyfills in regards to internationalization APIs.

E.g.:

```
https://polyfill.io/v3/polyfill.min.js?features=Intl%2CIntl.Locale
```

Search for "intl" here to find others in case you're running into other errors: https://polyfill.io/v3/url-builder/

**Comment by cancng** [comment]
I tried on iPhone 6 and same for me.

**Comment by amannn** [comment]
Are you saying that there's a bug in the polyfill? If you can reproduce it, maybe you can open a bug report on the issue tracker of polyfill.io.

**Comment by amannn** [comment]
I'll close this issue due to inactivity. Better documentation for polyfills is being tracked in #72. Thanks for bringing the topic up again!
