### ISSUE TITLE
[Docs]: Typescript Validation

### ISSUE THREAD

**Issue by SoloReverse** [amannn/next-intl#1255]
### Link to page

https://next-intl-docs.vercel.app/docs/workflows/typescript

### Describe the problem

I have ran into a problem where my messages file contains some arrays and that broke typescript validation
It would be beneficial to add to the bottom of the page in the 

"If you're encountering problems, please double check that:" section 

6. Make sure that the json file does not contain arrays

I didn't think to add it as a bug since its a typescript issue.

**Comment by amannn** [comment]
Using arrays in messages files is really not recommended, please see the [arrays of messages](https://next-intl-docs.vercel.app/docs/usage/messages#arrays-of-messages) docs.
