### ISSUE TITLE
Number format does not take skeleton into account

### ISSUE THREAD

**Issue by loudjanilef** [amannn/next-intl#127]
### Description

Any skeleton specified after the number format in a message doesn't seem to be taken into account

With the following message :
```json
{
    "problem": "This value should be displayed with the .# format (At most 1 fraction digit) : {value, number, .#}"
}
```
The output of the following function :
```ts
t('problem', 
        {
          value: 0.524251,
        }
)
```
should be : `This value should be displayed with the .# format (At most 1 fraction digit) : 0.5`.
It is `This value should be displayed with the .# format (At most 1 fraction digit) : 0.524`.

Any other skeleton written according to [this documentation](https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html) produces the same output.

### Reproduction

CodeSandbox reproduction: https://stackblitz.com/edit/github-8ezthy-xvctab?file=pages/index.js

Steps to reproduce:
1. Go to `messages/index/en.json`
2. Check that the skeleton is correct (.#)
3. See error: The output displayed in the preview tab is not formated according to the skeleton (.###)

### Expected behaviour

The output should be formated according to the skeleton.
Here, the output always has the same .### format

**Comment by amannn** [comment]
Hello @loudjanilef and thanks for the report!

You're right, this is a bug. It seems like the parser that `next-intl` currently uses ([`intl-messageformat`](https://www.npmjs.com/package/intl-messageformat)) has this bug. Would you mind moving the bug report to their repo? It can be reproduced by opening https://formatjs.io/docs/intl-messageformat/#datetimenumber-skeleton and pasting this code snippet into the live editor:

```js
new IntlMessageFormat(
  'The price is: {value, number, .#}',
  'en-GB'
).format({value: 0.524251})
```

You can use a workaround for the time being though:
```js
const intl = useIntl();

// 300.0
intl.formatNumber(299.99, {
  minimumFractionDigits: 1,
  maximumFractionDigits: 1
})
```

The same should be possible if you define a global format on the provider, please see the [docs on global formats](https://next-intl-docs.vercel.app/docs/usage/configuration#global-formats).

**Comment by loudjanilef** [comment]
Hello,
Thank you for your answer
As suggested, I submited an issue to the `formatjs` repo : https://github.com/formatjs/formatjs/issues/3848

**Comment by amannn** [comment]
Thanks! I'll close this issue in favour of the one at format.js then, hope that's ok! I'll watch the issue and if there's anything to do on the `next-intl` side, I'll update the library accordingly!

Thanks again!

**Comment by amannn** [comment]
Seems like there was a bug in the docs: https://github.com/formatjs/formatjs/issues/3848#issuecomment-1254589475. #130 will address this.

Thanks a lot for bringing this up!

**Comment by loudjanilef** [comment]
Great, it's way clearer this way!
Thanks for your work on this library
