### ISSUE TITLE
[Docs]: Example for app directory + cookie / header based locale switching

### ISSUE THREAD

**Issue by softmarshmallow** [amannn/next-intl#1315]
### Describe the problem

The App directory example only contains for router based localese, it would be nice to have a "best practice" example for doing a header (accept language) + cookie (NEXT_LOCALE) based, user preference based local switching.

**Comment by amannn** [comment]
Are you referring to an example that doesn't use an i18n routing setup? The [corresponding setup guide](https://next-intl-docs.vercel.app/docs/getting-started/app-router/without-i18n-routing) links to two examples at the bottom.
