### ISSUE TITLE
Official examples have type errors in _app.tsx

### ISSUE THREAD

**Issue by JTimings** [amannn/next-intl#134]
### Description

Minimal example _app.tsx type error => Property 'messages' does not exist on type '{}'

### Reproduction

https://next-intl-docs.vercel.app/examples/minimal
https://next-intl-docs.vercel.app/examples/advanced

### Expected behaviour

Examples can be built without type errors

**Comment by amannn** [comment]
That's a good point, thanks!

I'd suggest this:

```tsx
import { AbstractIntlMessages, NextIntlProvider } from "next-intl";
import { AppProps } from "next/app";

type Props = AppProps & {
  pageProps: {messages: AbstractIntlMessages}
}

export default function App({ Component, pageProps }: Props) {
  return (
    <NextIntlProvider messages={pageProps.messages}>
      <Component {...pageProps} />
    </NextIntlProvider>
  );
}
```

Would you be interested in updating this? The examples are in this repository.
