### ISSUE TITLE
`t.rich` strips all the passed props

### ISSUE THREAD

**Issue by vorillaz** [amannn/next-intl#135]
### Description

First things first, thanks a ton for this wonderful library, it makes i18n a breeze for Next.js projects.

My use-case scenario is a bit weird cause I need to pass along the parsed props from messages down to the rendering component.

My messages are something like this:
```
{
    "common": {
        "docs_link": "Welcome to the <link href="https://mysite.com/docs">docs</link>!",
        "support_link": "Welcome to the <link href="https://mysite.com/link">support</link>!"
    }
}
```

And the rendering component as follows:
```
const Component = () => {
  const { t } = useTranslations("common");
  const items = ["docs", "support"];
  return (
    <div>
      {items.map((item) => (
        <div key={item}>
          {t.rich(`${item}_link`, {
            a: (children) => <a>{children}</a>,
          })}
        </div>
      ))}
    </div>
  );
};
```

This example is pretty simple but the main idea is that I've got a bunch of translated items with unique links per language.

### Reproduction

CodeSandbox reproduction: https://codesandbox.io/s/next-intl-template-forked-pfhko4?file=/pages/index.js

Steps to reproduce:
1. Go to https://codesandbox.io/s/next-intl-template-forked-pfhko4?file=/pages/index.js
2. Internal props are not properly interpolated.

### Expected behaviour

Rendered properties from the translations should be passed to the associated components.

**Comment by amannn** [comment]
Hi @vorillaz and thank you for your kind words!

I see your point and to be honest I also had moments where I'd have liked to use this. Unfortunately the message parser that's used in the library doesn't support this.

Currently this is likely your best option:

```js
{
    "common": {
        "docs": {
          "label": "Welcome to the <link>docs</link>!",
          "href": "https://mysite.com/docs",
        },
        ...
    }
}
```

```js
const Component = () => {
  const { t } = useTranslations("common");
  const items = ["docs", "support"];
  return (
    <div>
      {items.map((item) => (
        <div key={item}>
          {t.rich(`${item}.label`, {
            link: (children) => <a href={t(`${item}.href`)}>{children}</a>
          })}
        </div>
      ))}
    </div>
  );
};
```

It might look a bit cumbersome, but reflects an important aspect that link href values are part of your app code. This can be relevant if you use a router with named routes for example.

If you have large blobs of HTML content you might want to consider `t.raw`.

Hope this helps!

**Comment by vorillaz** [comment]
Hi @amannn 
That's what I did at first place :)
Thanks a ton for your support, cheers!
