### ISSUE TITLE
Prepare for async `await headers()` in Next.js 15

### ISSUE THREAD

**Issue by amannn** [amannn/next-intl#1375]
### Is your feature request related to a problem? Please describe.

Ref.: https://github.com/vercel/next.js/pull/68812

`next-intl` currently relies on reading a request header to detect the current locale when relevant APIs are called in a Server Component. Note that this by itself is a workaround, ideally the locale could be retrieved from a param (see https://github.com/vercel/next.js/discussions/58862).

The APIs `next-intl` offers can be put in three categories:
1. Formatting APIs ([`useTranslations`](https://next-intl-docs.vercel.app/docs/usage/messages) & [`useFormatter`](https://next-intl-docs.vercel.app/docs/usage/dates-times))
2. APIs for retrieving [global configuration](https://next-intl-docs.vercel.app/docs/usage/configuration) (e.g. `useLocale`)
3. [Navigation APIs](https://next-intl-docs.vercel.app/docs/routing/navigation) (e.g. `Link`—these are lightweight wrappers for navigation APIs from Next.js and automatically incorporate localization of pathnames like locale prefixes)

The first two categories use APIs that have signatures that are either hooks or awaitable async functions—so those should be fine to update.

In the third category, the APIs are a bit more diverse. However, most APIs can be adapted as necessary:
1. The `Link` component can be turned `async` to use `await getLocale()` internally
2. `useRouter` & `usePathname` can consume a promise via `use`
3. `getPathname` requires an explicit locale anyway

Only one API stands out as problematic: [`redirect`](https://next-intl-docs.vercel.app/docs/routing/navigation#redirect)

This is a function that can be called in the following environments:
1. During the RSC render in an `async` component
2. During the RSC render in a non-`async` component
3. During SSR in a Client Component
4. During CSR in a Client Component
5. (Calling outside of render, e.g. in an event handler, will not have any effect)

Since `use(…)` doesn't work in `async` components, we'd have to use an awaitable API for (1). However, for the other call sites, a non-awaitable API would be more ergonomic (otherwise the user would have to wrap in `use`)

### Describe the solution you'd like

I can think of the following solutions to address this:

1. **Require a locale to be passed to `redirect`**: `redirect({locale: 'en', href: '/about'})`. To retrieve the locale, it'd be the job of the user to either call `async getLocale()` or `useLocale()` depending on the calling component.
    - Pros: Flexible, also adding the capability to redirect to other locales
    - Cons: More verbose to what we had before (i.e. `redirect('/about')`
2. **Make `redirect` awaitable**
    - Pros: Can keep the ergonomics and not require a `locale` (mostly)
    - Cons: Divergence from what the user knows from Next.js (prone to errors), can not be used in non-async components

Another implication is likely that the user can't read the `locale` that's passed to [`i18n/request.ts`](https://next-intl-docs.vercel.app/docs/getting-started/app-router/with-i18n-routing#i18n-request) synchronously. We might have to replace this with something promise-based (`await locale` or `await getLocale()`).

### Moving forward

As matters stand currently, it seems like (1) will be more future-proof. Also, in case `use()` becomes available in async Server Components in the future, we can put back a default for the current locale in a later release.

Note that the navigation APIs are currently being reworked in https://github.com/amannn/next-intl/pull/1316, so now would be a good point to adjust for the future.

**Comment by amannn** [comment]
The following PRs will resolve this:
1. https://github.com/amannn/next-intl/pull/1316
2. https://github.com/amannn/next-intl/pull/1383

**Comment by amannn** [comment]
Please see here: https://github.com/amannn/next-intl/pull/1391

**Comment by amannn** [comment]
@tonyabracadabra Did you upgrade to the new APIs in the canary version? (see also https://github.com/amannn/next-intl/pull/1391#issuecomment-2411017222)

I tried recently with a Next.js 15 canary version and was able to get rid of all warnings. Can you try to diagnose where exactly you're seeing a warning and what causes it?



> Also I am still really confused by the approach of adding `unstable_setRequestLocale(locale);` everywhere in server layout and pages, will this still be the case in the next js 15 compatible version of `next-intl`? Thank you!

That's unfortunately a different story, see https://github.com/amannn/next-intl/issues/663

**Comment by danielkoller** [comment]
I'm encountering a similar issue with the latest canary version of Next.js and next-intl. Specifically, I'm getting a type error related to `params` in my page components:

`Type error: Type '{ params: { locale: string; }; }' does not satisfy the constraint 'PageProps'.
Types of property 'params' are incompatible.
Type '{ locale: string; }' is missing the following properties from type 'Promise<SegmentParams>': then, catch, finally, [Symbol.toStringTag]`

My page component is structured like this:

```typescript
type Args = {
params: Promise<{
slug?: string
locale: string
}>
}
export default async function Page({ params }: Args) {
const { slug = 'home', locale } = await params
// ... rest of the component
}
export async function generateMetadata({ params }: Args): Promise<Metadata> {
const { slug = 'home', locale } = await params
// ... rest of the function
}```

I've implemented `unstable_setRequestLocale(locale)` in my layouts and pages as suggested, but I'm still encountering this type error during the build process.

Is there an additional step I'm missing to properly type `params` as a Promise in this context? Or is this a known issue that's still being addressed?

Any guidance on resolving this type incompatibility while maintaining proper internationalization support would be greatly appreciated.

**Comment by imranbarbhuiya** [comment]
@amannn Have you seen https://github.com/vercel/next.js/discussions/58862#discussioncomment-10843594?

**Comment by amannn** [comment]
@imranbarbhuiya Yep, we had a brief exchange on X: https://x.com/jamannnnnn/status/1842179418657116244. It's essentially the same approach as `unstable_setRequestLocale`, but in the case of nuqs, parsing is applied on top.

@danielkoller I can't really see an issue in that code sample you've provided. Maybe the error is triggered by another component? I'll soon have the examples in this repo updated for Next.js 15, maybe that can help for reference.

**Comment by danielkoller** [comment]
@amannn perfect, thanks!

**Comment by amannn** [comment]
Next.js 15 is supported now without warnings:
1. [next-intl 3.22](https://next-intl-docs.vercel.app/blog/next-intl-3-22): Adopt `await requestLocale` and `createNavigation`
2. [next-intl 3.23](https://github.com/amannn/next-intl/releases/tag/v3.23.0): Next.js 15 has been added to peer dependencies

However, please consider: https://github.com/amannn/next-intl/issues/1442. Due to this, I'm waiting for now with updating examples and the official bug repro.
