### ISSUE TITLE
CMD+Click support or go to correct key with `go to declaration`

### ISSUE THREAD

**Issue by ahmadshiddiq** [amannn/next-intl#1378]
### Is your feature request related to a problem? Please describe.

This is pure feature, there no a bug. I really love the typesafe with this library given, but seems i miss the DX that find the correct key automatically when i click `cmd+left_click`.
Currently the response from my IDE (webstorm) is says: "Cannot find declaration to go to"

### Describe the solution you'd like

I don't know how to make the solution

### Describe alternatives you've considered

Currently i didn't have any alternative that working on, so i need to find it by myself.

**Comment by amannn** [comment]
You might want to check [i18n Ally for JetBrains](https://plugins.jetbrains.com/plugin/17212-i18n-ally) (see also the [`next-intl` VSCode integration](https://next-intl-docs.vercel.app/docs/workflows/vscode-integration)).
