### ISSUE TITLE
[Docs]: Given passthrough Root layout doesn't compile

### ISSUE THREAD

**Issue by alexmge** [amannn/next-intl#1385]
### Link to page

https://next-intl-docs.vercel.app/docs/environments/error-files#catching-non-localized-requests

### Describe the problem

This documentation says that if you want to catch non localized requests with a `not-found.tsx` file, you can still add `app/not-found.tsx` before the `app/[lang]` route and add a passthrough root layout in `app/layout.tsx`.

The given passthrough root layout example is
``` ts
// Since we have a root `not-found.tsx` page, a layout file
// is required, even if it's just passing children through.
export default function RootLayout({children}) {
  return children;
}
```

However, as described in the NextJS documentation [here](https://nextjs.org/docs/messages/missing-root-layout-tags), the `html` and `body` tags are required in the root layout, leading to a compilation error if missing (at least that's what I experienced).

**Comment by amannn** [comment]
The Next.js docs are unfortunately a bit inconsistent, e.g. [here](https://nextjs.org/docs/app/building-your-application/routing/internationalization#static-generation) the `html` and `body` tag is suggested at `app/[lang]/layout.tsx`.

**Comment by daveycodez** [comment]
<img width="561" alt="Image" src="https://github.com/user-attachments/assets/af3656f3-9e71-42c9-8369-763902c4fd47" />

@amannn Are we supposed to just ignore this error for root not-found.tsx?

**Comment by daveycodez** [comment]
I figured out we can just put suppressHydrationWarning on both html tags on both layouts, that should do the fix
