### ISSUE TITLE
Passing a React.Node into t.rich

### ISSUE THREAD

**Issue by rrrshtt** [amannn/next-intl#1406]
### Is your feature request related to a problem? Please describe.

I want to pass an React.Node into some 'destination' key without chunks.

### Describe the solution you'd like

For some reasons this usage is work perfectly. I just passed a key into node.
```
t.rich('message', {
  destination: (<span key="destination">Hello destination</span>) as unknown as string,
});
```

### Describe alternatives you've considered

i will write it down later, didn't saw next-intl code yet.

**Comment by amannn** [comment]
Please refer to the docs: https://next-intl-docs.vercel.app/docs/usage/messages#rich-text-self-closing
