### ISSUE TITLE
Add support for returning translated objects and arrays

### ISSUE THREAD

**Issue by astralarya** [amannn/next-intl#1434]
### Is your feature request related to a problem? Please describe.

I would like to be able to retrieve translated objects and arrays.  See the feature from i18next: https://www.i18next.com/translation-function/objects-and-arrays

### Describe the solution you'd like

Perhaps the `t` object could have a `.object()` function.  For example:

### en.json
```json
{
  "MyScope": {
    "MyObject": [
      {
        "label": "Label 1",
        "value": "Value 1"
      },
      {
        "label": "Label 2",
        "value": "Value 2"
      }
    ]
  }
}
```

### component.tsx
```tsx
function MyObject() {
  const t = useTranslations("MyScope");
  const myObject = t.object("MyObject");
  return <dl>
    {myObject.map((item, idx) => (
      <Fragment key={idx}>
        <dt>{item.label}</dt>
        <dd>{item.value}</dd>
      </Fragment>
    ))}
  </dl>
}
```

### Describe alternatives you've considered

The simple example above could be done with `.rich()` or `.markup()`, but imagine instead of a simple `<dl>` list, we are passing props to components, etc.  There is also the `useMessages()` hook, but that is extremely manual and way less convenient than having a `.object()` function which could do it automatically.

**Comment by amannn** [comment]
Handling arrays is covered in the docs, please have a look: [Arrays of messages](https://next-intl-docs.vercel.app/docs/usage/messages#arrays-of-messages)
