### ISSUE TITLE
[Docs]: Sitemaps

### ISSUE THREAD

**Issue by fab-uleuh** [amannn/next-intl#1446]
### Link to page

https://next-intl-docs.vercel.app/docs/environments/actions-metadata-route-handlers#sitemap

### Describe the problem

The sitemap example on the doc is not the same than in the exemple on the code. The exemple in the code work for me but the code into the doc make a double language into url: 

Good code : 

https://github.dev/amannn/next-intl/blob/e79dd7e6d070702e56d0bf303be0af12a0981cb9/examples/example-app-router/src/app/sitemap.ts

**Comment by amannn** [comment]
Thanks a bunch for noticing, a fixed version should be up in a minute!
