### ISSUE TITLE
Support for nextjs v13

### ISSUE THREAD

**Issue by kaname-png** [amannn/next-intl#147]
### Is your feature request related to a problem? Please describe.

Actually I see that all the examples are based on nextjx v12 that used only the `pages` folder, but now in nextjs v13 they implemented the `app` page (https://nextjs.org/blog/next-13), so I wonder if there is a way to use it with nextjs v13 and if not, it would be great to implement it.

### Describe the solution you'd like

Examples or compatibility with nextjs v13.

### Describe alternatives you've considered

I do not know.

**Comment by amannn** [comment]
Hi @kaname-png and thanks for reaching out!

I'm exploring this currently in #144 (basic support) and #139 (integration with RSC). I'll close this issue as soon as I have found a good solution!
