### ISSUE TITLE
Disabling printing the errors via a boolean flag

### ISSUE THREAD

**Issue by BjoernRave** [amannn/next-intl#1496]
### Is your feature request related to a problem? Please describe.

Currently its possible to disable next-intl to log the errors it encounters by passing a custom onError event handler. However when in the app router on a server component it errors, as you are not allowed to pass event handlers there.

![Screenshot 2024-10-31 at 13 14 32](https://github.com/user-attachments/assets/32622546-bd18-4736-b059-45be29cfbfb1)

### Describe the solution you'd like

Provide a simple boolean field to disable logging of errors

### Describe alternatives you've considered

Putitng the provider inside a client compponent, but its more tedious

**Comment by amannn** [comment]
Yep, I agree this is currently a bit tedious. This is tracked in https://github.com/amannn/next-intl/issues/1285.
