### ISSUE TITLE
useTranslations populates a new 't' on every render

### ISSUE THREAD

**Issue by ilanbm** [amannn/next-intl#15]
If there is a component/useEffect/useCallback that has `t` as a prop/dependency, it makes it rerender/rerun since `t` is changing.

I assume it should change only on locale change (at least the case I was using)

I'm using this as a workaround:
```
   const t = useCallback(useTranslations(), [locale])
```

**Comment by amannn** [comment]
Yep, I think that's fair. Typically I'd suggest to not use `t` in `useEffect`, but only in render, but I guess there are use case where you don't have another option.

I'll look into this!

**Comment by amannn** [comment]
I've fixed this in `use-intl@0.3.1`. Note that this is the underlying library from `next-intl` and is installed automatically. Please make sure that your lockfile references the correct version of `use-intl` or otherwise reinstall the dependency.
