### ISSUE TITLE
Export getRoute from utils.ts to get route in server function

### ISSUE THREAD

**Issue by numito** [amannn/next-intl#1501]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

export 
```javascript 
getRoute<AppLocales extends Locales>(
  locale: AppLocales[number],
  pathname: string,
  pathnames: Pathnames<AppLocales>
): keyof Pathnames<AppLocales> 
```
So we can use it in server component to get the current route. 

Another option would be to set new headers in the middleware. For example:

```javascript
    request.headers.set("x-current-path", request.nextUrl.pathname)
    request.headers.set("x-current-route", getRoute(locale, request.nextUrl.pathname, pathnames))
```

Therefore in server components we can get access to the path and current route.

### Describe alternatives you've considered

Trying to duplicate the code the get the current route but it's not viable, there two many dependencies.

**Comment by amannn** [comment]
The current pathname can't be read by design in Server Components: https://github.com/vercel/next.js/issues/43704#issuecomment-2090798307
