### ISSUE TITLE
Content Negotiation & hreflang Support

### ISSUE THREAD

**Issue by anaclumos** [amannn/next-intl#1577]
### Is your feature request related to a problem? Please describe.

I've noticed there doesn't seem to be a support for HTTP Content Negotiation and hreflang support.

### Describe the solution you'd like

An automated way of HTTP Content Negotiation and hreflang support

### Describe alternatives you've considered

N/A

**Comment by amannn** [comment]
Not sure I can follow, can you provide some more details?

Some references:
1. The middleware uses the [`accept-language` header](https://next-intl-docs.vercel.app/docs/routing/middleware#locale-detection) to negotiate a matching locale (among other aspects)
2. [`Link`](https://next-intl-docs.vercel.app/docs/routing/navigation#link) sets an `hreflang` in case you're linking to another locale. When you're linking to a page that uses the current locale, no `hreflang` is necessary.

**Comment by anaclumos** [comment]
Sorry for checking this late -- does next-intl set link tags in `<head>` like:

```
<link rel="alternate" href="https://yourdomain.com/be/" hreflang="fr-be" />
```

I was mainly talking about this!

For example, docusaurus sets:

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/12678912-e4b0-4fd1-93e3-7ec92414dc54">

**Comment by amannn** [comment]
Yep, `next-intl` sets these links via the `link` header on the response:

![Screenshot 2024-12-10 at 13 27 40](https://github.com/user-attachments/assets/aa6d09f7-f05b-4453-a8df-482923ba83b0)

Whether you're using an HTML tag or a response header is equal from [the perspective of a search engine](https://developers.google.com/search/docs/specialty/international/localized-versions?hl=en#methods-for-indicating-your-alternate-pages).

Just one note though: Next.js 15 broke the `link` response header if you're using `next/font` or `next/image`. I've set up a PR to fix this: https://github.com/vercel/next.js/pull/73431. So if you use these features, you might want to wait with upgrading to Next.js 15 until this is merged :).

Hope this helps!

**Comment by anaclumos** [comment]
Fabulous — I just sent a one-time sponsor as you went deeper even to submit a PR! Incredibly thankful. Please get something to treat yourself, maybe a cup of coffee 😁

**Comment by amannn** [comment]
You're one of the absolutely nicest people running around on the internet—many thanks Sunghyun! 😄
