### ISSUE TITLE
Documentation lacks one example

### ISSUE THREAD

**Issue by angelod1as** [amannn/next-intl#158]
### Description

In the [documentation](https://next-intl-docs.vercel.app/docs/usage/messages#rendering-of-messages) of the Rendering of Messages, each example of interpolation has its correspondent in code, except one:

```
  "select": "{gender, select, male {He} female {She} other {They}} is online.",
```

It does not have its corresponding example in the following box.

### Reproduction

N/A

### Expected behaviour

The documentation should provide all examples, according to the others.

**Comment by amannn** [comment]
Thanks, I missed that one!
