### ISSUE TITLE
Check if translations exists

### ISSUE THREAD

**Issue by m4rc1nn** [amannn/next-intl#1588]
### Is your feature request related to a problem? Please describe.

Currently i have to use code like this to check if translations exists
`
{__("small-text") !== `${translations}.small-text` && (
                <div className="mb-6 text-center font-bold">
                  {__("small-text")}
                </div>
              )}
`

and this throw an error MISSING_MESSAGES and i have to pass onError function to provider. 

Can we add some function e.g: t.has()? 

### Describe the solution you'd like

add function to check if translations exists
t.has();

### Describe alternatives you've considered

add function to check if translations exists
t.has();

**Comment by amannn** [comment]
Have you seen https://next-intl-docs.vercel.app/docs/usage/messages#t-has?

**Comment by m4rc1nn** [comment]
@amannn No in the docs, but i already tried this in my code and get an error:
<img width="812" alt="Screenshot 2024-12-03 at 09 35 38" src="https://github.com/user-attachments/assets/c7ba1df8-591a-43f6-a44b-11d4fc11cb1d">

**Comment by amannn** [comment]
`t.has` was added in [v.3.21](https://github.com/amannn/next-intl/blob/main/CHANGELOG.md#3210-2024-10-09). If you upgrade, you can use it.

**Comment by m4rc1nn** [comment]
@amannn Thanks a lot!
