### ISSUE TITLE
[Docs]: Change "messages" variable name to "timeZone"

### ISSUE THREAD

**Issue by IlyaMinarov** [amannn/next-intl#1599]
### Link to page

https://next-intl-docs.vercel.app/docs/usage/configuration#time-zone

### Describe the problem

From the page:
```
// Regular components
import {useTimeZone} from 'next-intl';
const messages = useTimeZone();
 
// Async Server Components
import {getTimeZone} from 'next-intl/server';
const timeZone = await getTimeZone();
```

For consistency the above should be:
`const timeZone = useTimeZone();`

**Comment by amannn** [comment]
Of course, yes—thanks for noticing! 😊
