### ISSUE TITLE
[Docs]: Update example in LocaleLayout for Next.js 15

### ISSUE THREAD

**Issue by valentin-harrang** [amannn/next-intl#1626]
### Link to page

https://next-intl.dev/docs/getting-started/app-router/with-i18n-routing#layout

### Describe the problem

The `LocaleLayout` example provided in the documentation is outdated for the latest versions of Next.js. Since Next.js 15, the `params` in `app` directory layouts are now a promise. This requires using `await` when destructuring `params` in the `LocaleLayout`.

Current example from the docs:

```tsx
export default async function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
```

Proposed update:

```tsx
export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
```

Why this change is necessary:

The current example leads to a runtime error in Next.js 15+ because params is not destructurable until resolved as a promise. This adjustment will align the documentation with the latest Next.js API changes.

**Comment by C-Jeril** [comment]
I might have the same problem.
`
Error: Route "/[locale]" used `headers().get('X-NEXT-INTL-LOCALE')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at locale (i18n.mjs:44:41)
    at VocabularyDataServer (components\VocabularyDataServer.tsx:38:36)
    at Home (app\[locale]\page.tsx:36:66)
  42 | };
  43 |
> 44 | export default getRequestConfig(async ({ locale }) => {
     |                                         ^
  45 |   if (!i18nConfig.locales.includes(locale)) notFound();
  46 |
  47 |   try {
`

**Comment by amannn** [comment]
Thanks for the report! There's however already an existing one at https://github.com/amannn/next-intl/issues/1587 and a PR is open to address this.
