### ISSUE TITLE
NextJS 13 App folder: Intl context not defined when navigating between pages

### ISSUE THREAD

**Issue by kieranm** [amannn/next-intl#163]
### Description

I have followed the setup guide in the docs, including both the `NextIntlServerProvider` and `NextIntlClientProvider`. However, when navigating between pages, I get the following error...

```
Error: No intl context found. Have you configured `NextIntlServerProvider`?
```

### Reproduction

CodeSandbox reproduction: https://codesandbox.io/s/next-intl-context-bug-unf6ro?file=/app/%5Blocale%5D/page.js

Steps to reproduce:
1. Navigate to path `/en/views/page-one`
2. Click on "Go to page two"
3. See error: 

<img width="738" alt="Screenshot 2023-01-07 at 15 47 34" src="https://user-images.githubusercontent.com/232283/211159028-63f83920-5419-49b6-9e31-f8cad312cd2c.png">

### Expected behaviour

I would expect page transitions to happen without this error being thrown.

**Comment by tecsobs** [comment]
I have the same problem is very annoying

**Comment by amannn** [comment]
Thank you for pointing this out! This is a known bug that I expect to be fixed upstream, see known bug no. 1 on my list here: https://github.com/amannn/next-intl/pull/149 (has a workaround).

I'll close this issue for the time being, I need to resolve all the points mentioned in the PR before the RSC support becomes stable. Until then, the support in client components is stable—so if you need this on a production site, this is currently the way to go!
