### ISSUE TITLE
Nested pages doesn't work with generateStaticParams

### ISSUE THREAD

**Issue by MaxSvargal** [amannn/next-intl#169]
### Description

So, any page inside /[locale]/* doesn''t work if you export generateStaticParams()
```
export function generateStaticParams() {
	return []
}
```

next 13.1.2
next-intl 2.11.0-beta.2
![image](https://user-images.githubusercontent.com/1765954/213144854-857780ec-b3b5-4b77-8e27-59ec17ef8609.png)

### Reproduction

Make any nested page, add export fn generateStaticParams()

### Expected behaviour

Should works as expected

**Comment by amannn** [comment]
`generateStaticParams` is currently not supported, see the roadmap in the docs: https://next-intl-docs.vercel.app/docs/next-13/server-components#roadmap

Please make sure to follow the issue template in the future.

**Comment by alex289** [comment]
Any status update on this? Would love to have this

**Comment by amannn** [comment]
Nope, still the same situation. I'm looking for updates on the Next.js side that could potentially enable this, my latest thoughts on this are noted here: https://github.com/amannn/next-intl/pull/149
