### ISSUE TITLE
'IntlErrorCode' is not exported from 'next-intl'

### ISSUE THREAD

**Issue by ryexley** [amannn/next-intl#17]
Using v0.4.0, I've run into the above error attempting to follow [the error handling example from here in the README](https://github.com/amannn/next-intl#error-handling).

![image](https://user-images.githubusercontent.com/173844/103251109-47bbe780-4945-11eb-9b32-1f5241cd776e.png)

My code looks like this:

```jsx
// ...
import { NextIntlProvider, IntlErrorCode } from "next-intl"
// ...

function onIntlError(error) {
  if (error.code === IntlErrorCode.MISSING_MESSAGE) {
    console.warn(`⚠️ Translation missing for ...`)
    console.log(error)
  } else {
    // TODO log to Sentry
  }
}

export default function App({ Component, pageProps, translations }) {
  return (
    <NextIntlProvider messages={translations} onError={onIntlError}>
      <Component {...pageProps} />
    </NextIntlProvider>
  )
}

App.getInitialProps = async context => {
  const { router } = context
  const { locale, defaultLocale } = router

  const translations = await getTranslations({
    locale,
    defaultLocale
  })

  const appProps = await NextApp.getInitialProps(context)

  return {
    ...appProps,
    locale,
    translations
  }
}
```

For the moment, I've just been trying to log out the full details of the error so I can see what's on it, but I'm running into this error. Any ideas what I'm missing? Did something change in a recent release since this section of the README was written?

**Comment by amannn** [comment]
Thanks a lot for this report @ryexley!

There was indeed an issue with the compilation for JavaScript projects. I've just released `use-intl@0.3.2` which contains the necessary fix.

`use-intl` is the underlying library of `next-intl`. Please make sure the latest version is referenced in your lockfile.

**Comment by ryexley** [comment]
Thank you for fixing it @amannn, seems to work fine now.

For anyone that finds this later, we are using yarn, and I added this to my `package.json` file to use the updated version of `use-intl`:

```json
"resolutions": {
  "use-intl": "^0.3.2"
}
```

And that fixes it for me.

**Comment by amannn** [comment]
Thanks for the comment! Yep, the manual resolution works. Alternatively I think you should also be able to un- and then reinstall next-intl to make sure the latest dependencies are used. That way you don't have to modify your `package.json`.

By the way, thanks for giving the library a go! It's still a bit new, but I'm pretty happy with it so far. If you find any other rough edges, definitely let me know! 🙂
