### ISSUE TITLE
Cannot use translations in async server components

### ISSUE THREAD

**Issue by ardauzan** [amannn/next-intl#179]
### Description

Hi, I found that if a server component is async (to fetch data) I cannot use anything from this package. UseTranslations will not work, other hooks exported by this package also fail (Im sure that useLocale also causes a crash). 

### Reproduction URL (CodeSandbox)

Don't have time but its easy to reproduce

### Reproduction description

Steps to reproduce:
1. try making a server component async and using translations in it

### Expected behaviour

I expect it to work

**Comment by amannn** [comment]
Hi!

Are you using [the Server Components preview](https://next-intl-docs.vercel.app/docs/next-13/server-components)? This is a known bug upstream in React / Next.js. Did you read the error message? It should suggest an alternative how you can fix this.

**Comment by jetschni** [comment]
I am having the same issue! I use the Server Components (beta) of next-intl. 

I receive the following error (no suggestion how to solve it)
```
Error: Cannot read properties of null (reading 'useMemo')
```

Any ideas?

**Comment by amannn** [comment]
Can you sure a reproduction? You can use this as a template: https://github.com/amannn/next-intl-example-next-13

**Comment by jetschni** [comment]
If I add an async to page.tsx I receive the same error.

```
export default async function Index() {
  const t = useTranslations("Index");

  return (
    <PageLayout title={t("title")}>
      <p>{t("description")}</p>
      <LocaleSwitcher />
    </PageLayout>
  );
}
```

![image](https://user-images.githubusercontent.com/5909682/216353981-1370dd35-60a3-482d-9004-ef5e91c2e8c7.png)

**Comment by jetschni** [comment]
PS: With the following it works.

```typescript
let messages;
try {
    messages = (await import(`@/dictionaries/${locale}.json`)).default;
} catch (error) {
    notFound();
}

const t = createTranslator({ locale, messages });
```

**Comment by amannn** [comment]
Thanks for providing more details! There was indeed some additional handling missing in the latest beta to display a more helpful error message.

The next beta will include this error message:

<img width="991" alt="Screenshot 2023-02-03 at 09 43 14" src="https://user-images.githubusercontent.com/4038316/216553723-ae2b2e70-7f7a-42c4-b10a-366bcf93d9da.png">

I still have hope that this will be resolved [upstream in React / Next.js](https://github.com/vercel/next.js/issues/44778), but hopefully this serves as a workaround in the meantime.

**Comment by jupapios** [comment]
While there is a resolution for the upstream React/Next.js issue, you can use this one that's a drop-in replacement for `useTranslations` with its type-safety.

(It uses the deprecated `getLocale` tho 😅)

```ts
import { type NamespaceKeys, type NestedKeyOf } from "next-intl";
import { getLocale, getTranslator } from "next-intl/server";

type IntlMessages = typeof import("@/messages/en.json");

export function getTranslations<
  NestedKey extends NamespaceKeys<
    IntlMessages,
    NestedKeyOf<IntlMessages>
  > = never,
>(namespace?: NestedKey) {
  const locale = getLocale();
  return getTranslator(locale, namespace);
}
```

You might not need the `IntlMessages` type.

Here's how yo use it,

```git
-export function RSCNonAsync() {
-  const t = useTranslations("TranslationNamespace");
-  const copy = t("something");
+
+export async function AsyncRSC() {
+  const t = getTranslations("TranslationNamespace");
+. const copy = t("something"); // still type-safe
```

**Comment by Alexiafe** [comment]
I found this solution which is simple and working fine for me:

```
export default async function ProfilePage() {
  const locale = useLocale()
  const t = await getTranslator(locale, 'ProfilePage')

  return <div>{t('title')}</div>
}
```

**Comment by amannn** [comment]
There's some more discussion on this topic in https://github.com/amannn/next-intl/issues/406 btw.!

**Comment by natenadze1102** [comment]
<img width="951" alt="Image" src="https://github.com/user-attachments/assets/d906471e-92bc-48c4-a1fd-35e06117c2ad" />

https://next-intl.dev/docs/environments/server-client-components

This is solution.

**Comment by hijuliancode** [comment]
> <img alt="Image" width="951" src="https://private-user-images.githubusercontent.com/61623737/404550421-d906471e-92bc-48c4-a1fd-35e06117c2ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE5MDc1NzYsIm5iZiI6MTc0MTkwNzI3NiwicGF0aCI6Ii82MTYyMzczNy80MDQ1NTA0MjEtZDkwNjQ3MWUtOTJiYy00OGM0LWExZmQtMzVlMDYxMTdjMmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzEzVDIzMDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMjRmZTM0YWNhZDBjNjEwMzAwYzdiOWI0NWRmZGQzZGUyOTI5ZjQ5NGI0ODY2YjRlYmExMGYyNjhiYzZiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a5SbG6ncFJABgbkSIuwDFHn09vPcfcjqEifRKLgNx8U">
> https://next-intl.dev/docs/environments/server-client-components
> 
> This is solution.

This solution works for me. You're right, if we use const t = await getTranslations();, it works without any problem in a server component.

<img width="638" alt="Image" src="https://github.com/user-attachments/assets/aa2817f4-583f-410e-a17c-06c6fb1de336" />
