### ISSUE TITLE
How it support language detect using appDir for multi domain instead using segment path [lang] ?

### ISSUE THREAD

**Issue by tianyingchun** [amannn/next-intl#181]
### Is your feature request related to a problem? Please describe.

How it support language detect using appDir for multi domain?
1. a.domain.com --- for english   (https://a.domain.com/products)
2. b.domain.com ---for UK          (https://b.domain.com/products)
3. don't need to [lang] folder

### Describe the solution you'd like

No Idea from docs https://next-intl-docs.vercel.app/docs/next-13/client-components

### Describe alternatives you've considered

no idea

**Comment by amannn** [comment]
You can probably already achieve this with rewrites. I'd like to support this natively in the middleware, I've got it in my todo list here: https://github.com/amannn/next-intl/pull/149
