### ISSUE TITLE
Prefixing locale to every page URL with middleware

### ISSUE THREAD

**Issue by wxh06** [amannn/next-intl#185]
### Is your feature request related to a problem? Please describe.

Currently, only `/` can be redirected to to the URL with locale

<https://github.com/amannn/next-intl/blob/18c94d623a05afa7710fea83360f12f9811fb38d/packages/next-intl/src/server/createIntlMiddleware.tsx#L6-L7>

<https://github.com/amannn/next-intl/blob/18c94d623a05afa7710fea83360f12f9811fb38d/packages/next-intl/src/server/createIntlMiddleware.tsx#L21-L27>

### Describe the solution you'd like

Prefixing language code to every single page, e.g. redirecting `/about` to `/en/about` instead of returning 404

- <https://beta.nextjs.org/docs/guides/internationalization#routing-overview>
- <https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale>

### Describe alternatives you've considered

Providing an option to enable global redirection when calling `createIntlMiddleware`

For example:

```javascript
import { createIntlMiddleware } from 'next-intl/server';

export default createIntlMiddleware({
  locales: ['en', 'zh-CN'],
  defaultLocale: 'en',
  redirectRootOnly: false
});
```

**Comment by amannn** [comment]
Yep, this is coming: https://github.com/amannn/next-intl/pull/186
