### ISSUE TITLE
Jest mocking?

### ISSUE THREAD

**Issue by ryexley** [amannn/next-intl#19]
Anyone have any good examples of how to mock `next-intl` for testing with Jest and react-testing-library?

**Comment by amannn** [comment]
Is there anything particular you're looking for or an issue you're encountering? For unit testing you'd typically want to render a provider that wraps the components you're unit testing.

Here is an example test from this repo that uses Jest and react-testing-library: 
https://github.com/amannn/next-intl/blob/bc377ed9c7302d73d0e19c68c4018362de6db7e0/packages/next-intl/test/useTranslations.test.tsx#L11-L24

If you're having any issues, please report back!
