### ISSUE TITLE
When refreshing the example website, it automatically sets to German.

### ISSUE THREAD

**Issue by wh5938316** [amannn/next-intl#193]
### Description

When I refresh the page on the [next 13 example website](https://next-intl-example-next-13.vercel.app/), it automatically adds the /de suffix. When I click the 'Zu Englisch wechseln' button and remove the /en suffix and refresh the page again, it still redirects me to the /de page. Is this expected behavior or a bug?

### Reproduction URL (CodeSandbox)

https://next-intl-example-next-13.vercel.app/

### Reproduction description

Steps to reproduce:
1. Access https://next-intl-example-next-13.vercel.app/
2. Refresh the page
3. Access https://next-intl-example-next-13.vercel.app/en
4. Remove the /en suffix and refresh the page

### Expected behaviour

The website language should not automatically switch to German, even if the default language is German. When accessing the /en route after, it should not redirect or redirect to /en.

**Comment by amannn** [comment]
Hey and thanks for the bug report! This was indeed an issue, I've addressed it in https://github.com/amannn/next-intl/commit/7a76d2bfda0285cc02ff9bc8ac1414711e3102c4. I'll publish a new beta release today which will include the fix.

**Comment by amannn** [comment]
This is fixed in `2.11.0-beta.13`, thanks again for the report!
