### ISSUE TITLE
Allow getTranslations to return objects, not only single translation keys

### ISSUE THREAD

**Issue by LotharVM** [amannn/next-intl#194]
### Is your feature request related to a problem? Please describe.

Let's say I've setup my translations as the following:
```
{
  "general": {
    "search": "Search"
  },
  "program": {
    "title": "Today's events",
    "subtitle": "Check ik out."
  }
}
```

The idea behind this is that I can split my translations by page, `program` in this example. On the program page `/[locale]/program/page.js` I'd like to get all the `program` translations and pass it down to a Client component which takes care of the styling etc. 

If I try to do `const translation = await getTranslations('program')` and log the output, it's returning the following error:
```
IntlError: MISSING_MESSAGE: Cannot read properties of undefined (reading 'split')
```
I was hoping I could get the complete object, but for now it seems that it's only possible to get single translation keys (e.g `program.title`. When the program page get bigger and bigger, this would require a lottt of `getTranslations` on that page..

### Describe the solution you'd like

In the above example, I'd like that `const translation = await getTranslations('program')` returns an object: 
```
"program": {
  "title": "Today's events",
  "subtitle": "Check ik out."
}
```

### Describe alternatives you've considered

Rebuilding the json structure manually, like so:
```
const translations = {
    program: {
      title: t('program.title'),
      subtitle: t('program.subtitle'),
    },
  };
```
Feels very redundant though..

**Comment by amannn** [comment]
Hi @LotharVM and thanks for the question!

There's a small [guide on how to work with translations in Client Components in the docs](https://next-intl-docs.vercel.app/docs/next-13/server-components#switching-to-client-components). Generally I'd really encourage you to stay with your internationalization concerns on the server side. I'm currently working on a longer blog article that explores more patterns to help with this.

> Feels very redundant though..

I totally agree. Maybe you can find some ways to leave more parts of the page on the server side? E.g.:

```
function ProgramPage() {
  const t = useTranslations('ProgramPage');

  return (
    <ClientLayout title={t('title')}>
      <ProgramDetails />
    </ClientLayout>
  );
}

function ProgramDetails() {
  const t = useTranslations('ProgramDetails');

  // Still on the server side …
  return (
    <p>{t('details')}</p>
  );
}
```

As mentioned in the guide, if you absolutely need to pass messages to the client-side, there's an [example for this](https://github.com/amannn/next-intl/blob/feat/next-13-rsc/packages/example-next-13-advanced/src/components/client/02-MessagesOnClientCounter/Counter.tsx).

Hope this helps!

**Comment by LotharVM** [comment]
Hi @amannn,

> Generally I'd really encourage you to stay with your internationalization concerns on the server side.

I definitely agree on that! 
That's also one of the reasons why I would love to have this feature, because if `getTranslations` would support returning an object, I can split all my translations server-side page-by-page (in page.js) before passing it down to a client component. Since I'm using chakra-ui (so CSS-In-JS), I cannot really split up my components as server-components since most of them require styling.

I'm coming from [next-translate](https://github.com/aralroca/next-translate), and that libraries has a `returnObject` parameter option you can pass to their `useTranslation` hook. Maybe that could be an idea for this library as well? Then, you could (in my program page example) do something like this: 
```
const allProgramTranslations = t('program', {}, { returnObjects: true });

// allProgramTranslations would return:
"program": {
  "title": "Today's events",
  "subtitle": "Check ik out."
}
```

**Comment by amannn** [comment]
Do I understand the situation correctly that your issue is that due to chakra-ui you have to convert many components to Client Components that you would prefer to keep as Server Components? If so, I think that's something that needs to be addressed by chakra-ui (via adding `'use client';` directives), seems like there's already popular demand for this: https://github.com/chakra-ui/chakra-ui/issues/7180#issuecomment-1368247530. As a stopgap solution, you'd have to wrap them manually.

In regards to your code example: This is something I'd really like to avoid. The ICU parser that ships with `next-intl` offers many features that can't be used anymore if messages are plain strings that are accessed via an object property instead of via the `t` function. You can do this manually of course, you shouldn't need an API from `next-intl` for this.

**Comment by LotharVM** [comment]
Ahh no sorry the whole chakra-ui situation has nothing to do with this Issue and is all been taken care of; I just wanted to explain why I can't always use server-components (because chakra requires client-components -- which is all fine).

A for the code example; I was a bit too fast with that.. I get what you're saying and agree. Maybe let's put it in a different way: Let's say my `program` object (in `en.json`) a lot of translation...

```
// en.json
"program": {
  "slider": {
    "title": "Today's events"
    ... 19 more
  },
  "cards" : {
    "title": "Nice cards"
     ... 19 more
  }
}
```
...what would be the most ideal way to pass them down to a client-component? Without having to use the client context provider (less performance). Currently, the only way is the following (correct me if I'm wrong):

```
// page.jsx (server-component)
const t = await getTranslations('program');

return (
  <ClientComponent
    sliderTitle={t('slider.title')}
    cardsTitle={t('cards.title')}
    ...
  />
);
```
This fine for 1-2 translations, but not if there're 20..
Therefore, I was thinking, what if `const t = await getTranslations('program')` could, next to the translation function, also (with an optional param or something) return the whole object? Because then, I could just do this:

```
// page.jsx
const t = await getTranslations('program');
// or (inspired by next-translate) something like: const t = await getTranslations('program', { returnObjects: true }); 

return (
  <ClientComponent t={t} />
);

// ClientComponent.jsx
const { slider, cards  } = t;

return (
  <div>
    {slider.title}
    {cards.title}
  </div>
);
```
Does this makes it more clear? My point is that in the case of many translations, a lottt of prop drilling is required.


BTW: Thanks a lot for the fast replies! Really appreciate all the effort you put in this library and its users!

**Comment by amannn** [comment]
Sure, always great to hear from enthusiastic users and to get feedback! 🙂

Here's an example of how you can already achieve this:

```jsx
// page.jsx

export default async function Page() {
  const locale = useLocale();
  const messages = await (import(`../messages/${locale}`).json());
  return (
    <ClientComponent messages={messages.program} />
  );
}
```

Does that help?

I'd prefer to not support this in core, as my general recommendation is to really leave the i18n concerns on the server side. For edge cases `NextIntlClientProvider` is the escape hatch to get the same feature set on the client side.

**Comment by LotharVM** [comment]
That makes a lot of sense. Thanks so much 💯

**Comment by amannn** [comment]
Cool, great to hear! 👏

**Comment by TomJD** [comment]
Hello! 

Following the previous example, what if we would need to access `useLocale` inside of `ClientComponent`?

Error: `Error: No intl context found. Have you configured the provider?`

Thank you very much for your efforts
