### ISSUE TITLE
Namespace as a file

### ISSUE THREAD

**Issue by darklight9811** [amannn/next-intl#216]
### Is your feature request related to a problem? Please describe.

Usually I see projects using namespaces as files, and when you work with a big project, it gets really hard to keep up on a single file (per language). My project is already 300 lines and is really hard to work with it.

### Describe the solution you'd like

Allow for namespaces to be placed as a file (making languages as directories).

### Describe alternatives you've considered

I can keep using namespaces as json objects, but things get really messy when they are like that. I'm willing to help write the code for it if necessary.

**Comment by amannn** [comment]
It's only the recommended pattern to have a single file for all translations, you can structure and load the translations from any source that is useful to you.

E.g.:
```jsx
export async function getStaticProps({locale}) {
  return {
    props: {
      // You can get the messages from anywhere you like. The recommended
      // pattern is to put them in JSON files separated by language and read
      // the desired one based on the `locale` received from Next.js.
      messages: {
        ...(await import(`../../messages/shared/${locale}.json`)).default,
        ...(await import(`../../messages/home/${locale}.json`)).default
      }
    }
  };
}
```
