### ISSUE TITLE
Middleware matcher issue on usage with Next.js 13's Server Components

### ISSUE THREAD

**Issue by orbulant** [amannn/next-intl#218]
### Description

According the offical docs for [next-intl Server Components](https://next-intl-docs.vercel.app/docs/next-13/server-components) in version **next-intl@2.12.0-beta.5**,

The middleware section has causes this error:
 `ImageError: unable to optimize image and unable to fallback to upstream image`

This is an error regarding the usage of Middlewares and how it messes up the paths to retrieve image files placed on the **public** folder.

### Reproduction URL (CodeSandbox)

none

### Reproduction description

Steps to reproduce:
1. Implement based on Docs
2. Implement some <Image/> components from `next/image`
3. See error:  `ImageError: unable to optimize image and unable to fallback to upstream image`

### Expected behaviour

1. Implement based on Docs
2. Implement some <Image/> components from `next/image`
3. No problem should be there, all <Image/> components should load and work properly.

**Comment by orbulant** [comment]
**Fix**

I've managed to fix it by using:
`matcher: ['/((?!api|static|.*\\..*|_next).*)']`

instead of:

`matcher: ['/((?!api|_next|favicon.ico|assets).*)']`

The emphasis is on the RegEx section: `.*\\..*`

**Comment by amannn** [comment]
Hello @orbulant and thanks for the report. Glad you were able to find a solution!

This is mentioned in the docs:

> Skip all paths that aren't pages that you'd like to internationalize

I'm currently considering handling images and similar static assets automatically, this is a bullet point here: https://github.com/amannn/next-intl/pull/149

I'll close this for the time being, as this is already known and on my list.
