### ISSUE TITLE
BigInt support for useFormatter.format()

### ISSUE THREAD

**Issue by tacomanator** [amannn/next-intl#222]
### Is your feature request related to a problem? Please describe.

In TypeScript, cannot easily use `BigInt` with `useFormatter().format(value)` as only accepted type of value is `number`.

### Describe the solution you'd like

Change type of `value` parameter of `useFormatter().number()` function from `number` to `number | BigInt`.

https://github.com/amannn/next-intl/blob/be79c1b816314f16f6825ee9cde50d076ba342e6/packages/use-intl/src/core/createFormatter.tsx#L133

### Describe alternatives you've considered

Add a new function as opposed to changing existing, if compatibility is a concern. Note, however, that `Intl.NumberFormat(...).format(value)` does support `BigInt`.

**Comment by amannn** [comment]
Hello and thanks for the question!

> Change type of `value` parameter of `useFormatter().number()` function from `number` to `number | BigInt`.

That sounds reasonable to me. I haven't worked with `BigInt` so far, do you know if there are any drawbacks to consider?

I'm currently quite busy with the RSC integration, so if you'd like to contribute this feature, I'd be happy to review a PR!

**Comment by tacomanator** [comment]
Would be happy to. I made the change to a forked repo and I'd like to test it in a local project before submitting the PR, but I don't seem to be able to install from local or forked GitHub project as I normally would. Tried install from `file:../next-intl/packages/next-intl` but subsequent imports fail. Sorry for the basic question—I haven't used learna in this way before.

**Comment by amannn** [comment]
Thank you so much! 🙌

The easiest way is probably to add some tests in [`createFormatter.test.tsx`](https://github.com/amannn/next-intl/blob/be79c1b816314f16f6825ee9cde50d076ba342e6/packages/use-intl/test/core/createFormatter.test.tsx) and [`useFormatter.test.tsx`](https://github.com/amannn/next-intl/blob/be79c1b816314f16f6825ee9cde50d076ba342e6/packages/use-intl/test/react/useFormatter.test.tsx).

The packages starting with "example" are also linked to the local dependencies, you can use those to test the feature in an e2e way if you like! However, the examples are currently intended to demonstrate specific aspects that need to be pointed out, I think I wouldn't change them to show BigInt support though.

Please note that to run the examples, you need to [build `use-intl` and `next-intl` locally first](https://github.com/amannn/next-intl/blob/e2d688dd25511e0da4f8bb04966ff2b2e56394a8/.github/workflows/main.yml#L19-L20). This is a bit hidden knowledge currently, I should probably set up a contributors guide that mentions this.

Let me know how it goes!

**Comment by tacomanator** [comment]
Thank you much. For now, I added two tests and broke one of the existing tests into two parts. All passing—sending PR over.
