### ISSUE TITLE
Middleware: Support for `basePath` in the `app` directory

### ISSUE THREAD

**Issue by amannn** [amannn/next-intl#243]
Currently the middleware assumes that `/` is the root of the app and works on top of that.

We could adapt it as follows:
1. Don't hardcode the root URL
https://github.com/amannn/next-intl/blob/ed100335aebf921e90299bfd711070d64e796a99/packages/next-intl/src/middleware/middleware.tsx#L14
2. All the places where an absolute URL is constructed, the `basePath` needs to be considered
https://github.com/amannn/next-intl/blob/ed100335aebf921e90299bfd711070d64e796a99/packages/next-intl/src/middleware/middleware.tsx#L96
3. Somehow the `basePath` needs to be passed to the middleware. Maybe we could use the plugin that is worked on in https://github.com/amannn/next-intl/pull/149 to read it from the Next.js config and then make it automatically available to the middleware (e.g. with `webpack.DefinePlugin`).
 
Potentially this could also help to implement region-specific routing, see https://github.com/amannn/next-intl/issues/243#issuecomment-1655085673 and https://github.com/amannn/next-intl/issues/549

(discussed in https://github.com/amannn/next-intl/discussions/242)

**Comment by amannn** [comment]
Hey, thanks for starting this discussion! This is definitely a valid feature request, I'll convert this to an issue. 

I haven't explored this topic in detail yet, but possibly, we'd have to wait for the lead from Next.js here:

> `basePath` has been removed. The alternative will not be part of useRouter. It has not yet been implemented.

(from [the upgrade guide](https://beta.nextjs.org/docs/upgrade-guide#step-5-migrating-routing-hooks))

I just saw that in the `pages` folder with i18n routing, Next.js appends the locale to the base path (e.g. `domain.tld/base-path/en/about` and even `domain.tld/base/path/en/about`). Is that also what you need?

**Comment by setowilliam** [comment]
I'm having this problem too. It only happens when I try to go to the locale set to `defaultLocale`. For example:
```
export default createMiddleware({
  // A list of all locales that are supported
  locales: ['en', 'ja'],

  // If this locale is matched, pathnames work without a prefix (e.g. `/about`)
  defaultLocale: 'ja'
});
```

and `next.config.js`
```
const nextConfig = {
  reactStrictMode: true,
  basePath: '/path',
  experimental: {
    appDir: true
  }
};
```

If I try to navigate to `/path/en`, it will be fine. But navigating to `/path/ja` or `/path` will redirect to `/404`

**Comment by paqstd-dev** [comment]
Similar problem. The Next 13.4 documentation has [basePath](https://nextjs.org/docs/app/api-reference/next-config-js/basePath) which doesn't work for this library.

**Comment by paulvanbrenk** [comment]
I've been fighting this for the past week. I believe it's a bug in NextJS, but I'm not getting much of a response from them.

https://github.com/vercel/next.js/issues/49883

**Comment by dbrxnds** [comment]
Hi, just chipping in to say that we are currently running into this same issue. Similarly to @setowilliam this only seems to be an issue for the default locale.

**Comment by amannn** [comment]
I haven't looked deeper into this and currently have to look into a few other things. So if someone is interested in contributing this feature, you're more than welcome to!

Middleware: https://github.com/amannn/next-intl/blob/main/packages/next-intl/src/middleware/middleware.tsx
Tests: https://github.com/amannn/next-intl/blob/main/packages/next-intl/test/middleware/middleware.test.tsx

**Comment by fchienvuhoang** [comment]
vote this!

**Comment by koyama-tagbangers** [comment]
I'm interested in improving this feature.
It would be desirable to read `basePath` option from `next.config.js`, but how about implement additional `basePath` option to `MiddlewareConfig` interface temporarily.
I think that it's a good place to start by improve middleware feature.

**Comment by amannn** [comment]
@koyama-tagbangers Great, let me know if you need help!

Starting with an option on the middleware is likely a good idea, yes—at least for the beginning. By doing this, we could already release the feature to the stable channel, since there's no plugin there yet. Potentially we could add an automatic default with the plugin later.

**Comment by amannn** [comment]
Side note: I think `basePath` support on the middleware, especially if it can be configured separately from `next.config.js`, could potentially help to implement region-specific locales (e.g. `example.com/eu/en-GB`). `/[region]` (or `/:region`, TBD)` needs to be a valid base path then. This could also be added in a second step though, if it increases complexity.

**Comment by ivanafanasyeu** [comment]
Hi, any updates here. Is it any way to make it work with basePath?

**Comment by J4v4Scr1pt** [comment]
To bad, need to choose another lib because of this.. 😑

**Comment by amannn** [comment]
Sorry to hear about your frustration @FlorianLeChat! `basePath` is definitely on the radar.

Is your use case a static `basePath` or something more dynamic like region prefixes (e.g. `/europe/fr`)? I think the former should be rather straightforward to integrate (see also https://github.com/amannn/next-intl/issues/243#issuecomment-1557064754). With the new RSC integration, we now have a plugin, which would allow `next-intl` to read the `basePath` from the config and to distribute it via `webpack.DefinePlugin` to the relevant APIs of `next-intl` (middleware, navigation APIs).

Please let me know if someone wants to step in to work on this! I currently still have a few other priorities, but if no one else looks into it, eventually I'll try to take care of it. I can't promise an ETA at this point though.

**Comment by FlorianLeChat** [comment]
> Is your use case a static `basePath` or something more dynamic like region prefixes (e.g. `/europe/fr`)?

Thanks for your quick reply! Honestly, about 90% of developers in my opinion who use a base path will always use it statically. I'd really like to help you, but unfortunately it's definitely beyond my skills.

**Comment by Robjam** [comment]
Hey @amannn I have a fairly rough branch on my fork that I have gotten working locally via `yarn link` and tests are passing.
I had a couple of questions before creating a PR.
1. This will probably create some conflicts with the 3.0 branch, is that going to be an issue for you?
2. Would targeting the 3.0 branch work better? (My team has our first release coming up next month and we would really like to have basePath support)
Here's the tentative [diff](https://github.com/amannn/next-intl/compare/main...Robjam:next-intl:feature/243-base-path)

**Comment by AlejandroSanchez90** [comment]
Any eta on this?

**Comment by kjxbyz** [comment]
Same issue

**Comment by wildskyf** [comment]
I just found a workaround, here is it:
<https://blog.wildsky.cc/posts/workaround-for-nextjs-next-intl-basepath#code>

Although you may not be able to read Chinese characters, I believe that you only need to read the code to solve the problem. Good luck!

**Comment by kjxbyz** [comment]
When will this pr be merged? This feature is very important to me.

**Comment by amannn** [comment]
Support for `basePath` was added in `next-intl@3.3.0`, please see [the updated docs](https://next-intl-docs.vercel.app/docs/routing/middleware#base-path).

Many thanks to @Robjam for getting the ball rolling here! 🙌
