### ISSUE TITLE
Namespace keys containing "." in TypeScript

### ISSUE THREAD

**Issue by MarekBodingerBA** [amannn/next-intl#248]
### Description

Hello,

thank you for great library.

```Namespace keys can not contain the character "." as this is used to express nesting. Please remove it or replace it with another character.```

But, they are fine by TypeScript:
![image](https://user-images.githubusercontent.com/104828482/232741457-65e5d78b-10c7-4f82-ab4b-0d3e6cbb6882.png)

Can we fix the types to invalidate those?

Thanks.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

No need

### Reproduction description

Steps to reproduce:
1. Create a key with ".".
2. Use it in TypeScript.

### Expected behaviour

Key with "." should fail in TypeScript.

**Comment by amannn** [comment]
Hello @MarekBodingerBA,

this topic was already discussed before:
 - https://github.com/amannn/next-intl/discussions/148#discussioncomment-4274218
 - https://github.com/amannn/next-intl/issues/105

As mentioned in the linked discussions, I'm currently not intending to add this.

Maybe you can transform your translations file as mentioned in the linked discussion?
