### ISSUE TITLE
Add way to set language using Context

### ISSUE THREAD

**Issue by rikusen0335** [amannn/next-intl#253]
### Is your feature request related to a problem? Please describe.

In Next.js 13, you can't `push` a state object and should only push the href, so that we can push like `router.push('/home/en')` but this seems a bit weird.

Also we have a context that providing current locale, so we probably could make a setter for context to set current language.

### Describe the solution you'd like

^Above is all

### Describe alternatives you've considered

We can do as like I've said above, that we can use `router.push('/home/en')` or whatever root (`/`) will fallback to defaultLocale.

**Comment by amannn** [comment]
Hello @rikusen0335, I think you're looking for this: https://next-intl-docs.vercel.app/docs/next-13/server-components#routing

Does this help?

**Comment by rikusen0335** [comment]
Thank you for your response!

Well no, it's not. It's considered alternative for me, and I thought if there was a way to get current lang from context (meant provider)

**Comment by rikusen0335** [comment]
Okay I changed issue title, this could be more particular

**Comment by amannn** [comment]
> I thought if there was a way to get current lang from context

You can get the current locale via `useLocale`. It might be from context in case of Client Components, but could also be a URL segment in Server Components.

> Add way to set language using Context

In Next.js 13, with Server Components, there is no context—the URL is the source of truth for the current locale. Therefore changing the locale really means changing the URL, which is what the routing APIs I've mentioned above are for.

Does that help?

**Comment by rikusen0335** [comment]
> You can get the current locale via useLocale. It might be from context in case of Client Components, but could also be a URL segment in Server Components.

Okay, wait, my brain is really dying today. I meant to say if there's way to set lang through context.

> In Next.js 13, with Server Components, there is no context—the URL is the source of truth for the current locale. Therefore changing the locale really means changing the URL, which is what the routing APIs I've mentioned above are for.

Oh that's too bad...
So as I understand, is that we can't set language without using router? Something like state can't be used, because of server components (rendered in node.js server actually)

**Comment by amannn** [comment]
Yep, that's correct!

Can the routing APIs be used for your use case? I'd close this issue then.

**Comment by rikusen0335** [comment]
Yes, thank you for the help!

**Comment by rizkiandrianto** [comment]
@amannn the only problem with routing API is the state is become reseted. Any solution for this kind of problem?
