### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED in next-intl 12.4.0

### ISSUE THREAD

**Issue by chrislicodes** [amannn/next-intl#286]
### Description

Hello :) The following error occurs when adding 

```js
const withNextIntl = require('next-intl/plugin')(
  // This is the default (also the `src` folder is supported out of the box)
  './i18n.ts'
);
```

to `next.config.js`.

```
Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin' is not defined by "exports" in /Users/......./node_modules/next-intl/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:464:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:748:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at /Users/......./node_modules/next/dist/server/require-hook.js:180:36
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  type: 'Error',
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
The error didn't occur in version 2.14.0-beta.4 and also not in 2.15.0-beta.1

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-rsq7su?file=%2Flocales%2Fde.json%3A1%2C1

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. See logs

### Expected behaviour

Normal startup

**Comment by levipadre** [comment]
Same issue here

**Comment by amannn** [comment]
Hi @chrislicodes,

right, the RSC features are currently only available in beta versions as mentioned in [the docs](https://next-intl-docs.vercel.app/docs/next-13/server-components).

If you switch to `next-intl@2.15.0-beta.1`, then [your app works](https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-6lkuby).

Was there some confusion in regards to the versioning?

I guess it's a bit confusing that `2.14.0-beta.4` didn't turn into `2.14.0` stable. The reasoning is that there was a minor release on the main branch in between, so the new RSC betas will be released on `2.15.0-beta.x` for the time being.

**Comment by chrislicodes** [comment]
Hi @amannn, oh, then I must have confused it. I somehow assumed that the stable 2.14.0 would include the RSC Beta - I just went with 2.15.0-beta.x and everything works as expected and really well together so far 🔥 Looking forward to the merge into main

**Comment by amannn** [comment]
Right, sorry for the confusion and thanks for following along! 🙌

**Comment by fabdbt** [comment]
Thanks for information @amannn. In my case, I've been tricked since I use Dependabot and it automatically created a PR bumping from **2.14.0-beta.4** to **2.14.2** (stable), while I'm using NextJS 13.4 (RSC)
