### ISSUE TITLE
Build fails for nextjs 12.*.*

### ISSUE THREAD

**Issue by AN1BRA** [amannn/next-intl#287]
### Description

with the new support of `next/navigation` module, versions of `next-intl` `^2.7.5` don't support nextjs 12 anymore since the package `next/navigation` doesn't exist for that version thus the build fails. I had to lock the version of `next-intl` to exactly `2.7.5` yesterday since it broke the CI/CD pipeline. please fix or remove the new version from the `minor compatible versions with 2.7.5`

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-pages-forked-by8wxd?file=%2Fsrc%2Fpages%2F_app.tsx%3A11%2C1

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. run `yarn build`

### Expected behaviour

you should get the following error: 
```bash
yarn run v1.22.19
$ next build
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

./node_modules/next-intl/dist/next-intl.cjs.production.min.js
Module not found: Can't resolve 'next/navigation' in '/project/home/an1bra/workspace/node_modules/next-intl/dist'

Import trace for requested module:
./node_modules/next-intl/dist/next-intl.cjs.production.min.js
./node_modules/next-intl/dist/index.js


> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by amannn** [comment]
Uh, thanks for the report—will look into this! Sorry for the inconvenience caused!

**Comment by AN1BRA** [comment]
Thank you, it might have happened to a lot of people who haven't upgraded to next 13 yet, well considering they don't have their lock file frozen.
