### ISSUE TITLE
Can't install with NPM (No matching version found for use-intl@^2.14.1)

### ISSUE THREAD

**Issue by MiXeR54** [amannn/next-intl#289]
### Description

Error while next-intl package installation.

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for use-intl@^2.14.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

not needed

### Reproduction description

Steps to reproduce:
1. npx create-next-app@latest
2. select default next setting while installation process 
3. npm install next-intl
4. check error in console

### Expected behaviour

next-intl installs without errors

**Comment by amannn** [comment]
Oh right, thanks for the report! Should be fine now!

**Comment by MiXeR54** [comment]
> Oh right, thanks for the report! Should be fine now!

Confirmed, it works. Thank you!
