### ISSUE TITLE
No style using loading page

### ISSUE THREAD

**Issue by abepuentes** [amannn/next-intl#296]
### Description

NextJS let you add a loading.tsx page to render while fetching, if we import the same css module to this loading.tsx file and into page.tsx file, the style is not apply until refresh.

The reason to import from the same css module into this two files is to have the same styling while the data is fetching.

Works fine on dev, this bug its visible once deployed to Vercel/Amplify-Hosting or after building while using yarn start/npm run start

Thanks for all the work put into this library, works great.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/abepuentes/loading-test

### Reproduction description

Steps to reproduce:
1. npx create-next-app@latest
2. Add next-intl, middleware and file structure
3. Add a loading.tsx page
4. import the same css module to both page.tsx and loading.tsx
5. Deploy or Build the project

Live demo https://loading-css-test.vercel.app

### Expected behaviour

Style should be applied to the page file after loading without need to refresh the page. Working as expected while development. Workaround so far its pretty easy, just import style from different css modules.

**Comment by amannn** [comment]
Hello @abepuentes and thanks for the kind words!

Does this have anything to do with `next-intl`? It sounds like a general Next.js issue to me.

**Comment by abepuentes** [comment]
Hi, @amannn your absolutely right, I uninstall next-intl but keep the file structure and the issue is the same, si I will report this to next and update the GitHub repo without next-intl, thanks for your fast response.
