### ISSUE TITLE
I am facing a strange issue when adding a dot to the first segment.

### ISSUE THREAD

**Issue by aboda1986** [amannn/next-intl#307]
### Description

I am experiencing an issue when I add dot characters to a URL.

Tested with the following versions:
  - "next": "^13.4.3"
  - "next-intl": "^2.15.0-beta.4"

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://next-intl-example-next-13.vercel.app

### Reproduction description

Steps to reproduce:

1. Open the following URL: https://next-intl-example-next-13.vercel.app/test.test.
2. You will encounter a server error due to the middleware passing the language as "test.test"

### Expected behaviour

It should returns notFound page

**Comment by amannn** [comment]
Thanks for the report! There was some error handling missing, I've covered it in https://github.com/amannn/next-intl/commit/c46a1d6925ef3efbd5c5affc904e0b28cc9d64fc
