### ISSUE TITLE
Passing a `<Link>` to a client component as props creates an error.

### ISSUE THREAD

**Issue by ClementDreptin** [amannn/next-intl#319]
### Description

Trying to pass a `<Link>` to a client component as props creates the following error:
`Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".`
This is a common patern when using the [Material UI](https://mui.com/) components.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/ClementDreptin/next-intl-link

### Reproduction description

Steps to reproduce:
- Clone the reproduction repository
- Install the dependencies with `npm install`
- Start the development server with `npm run dev`
- Go to [localhost:3000](http://localhost:3000) to see the error
- Checkout the `fix` branch to see a working version

### Expected behaviour

The MUI link being displayed without any errors.

**Comment by ClementDreptin** [comment]
The fixed shown in the repository converts the `<Link>` component to a client component which seems reasonable considering the [`<Link>` component from next itself](https://github.com/vercel/next.js/blob/canary/packages/next/src/client/link.tsx#L1) is a client component. I don't know if it's a solution you would approve though.

**Comment by amannn** [comment]
Thanks for the report! This is outside the scope of `next-intl` as we don't modify the bundling of Next.js. Adding a wrapping component that is marked with `'use client';` is the solution.

E.g.:

```tsx
'use client';

import NextIntlLink from 'next-intl/link';
import { Link as MuiLink } from '@/mui/material';

export default function Link(props) {
  return (
    <MuiLink
      component={NextIntlLink}
      {...props}
    />
  );
}
```
