### ISSUE TITLE
Package subpath './plugin' is not defined by "exports" in 

### ISSUE THREAD

**Issue by alexclinky** [amannn/next-intl#322]
### Description

Hello

I am trying to Localize pathnames but I am getting this error when modifying next.config.js

DOC URL I am following: https://next-intl-docs.vercel.app/docs/next-13/middleware#localizing-pathnames

`- error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin' is not defined by "exports" in /Users/alex/Downloads/next-intl-feat-next-13-rsc/examples/example-next-13-named-routes/node_modules/next-intl/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:261:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:591:9)
    at resolveExports (node:internal/modules/cjs/loader:569:36)
    at Module._findPath (node:internal/modules/cjs/loader:643:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1056:27)
    at /Users/alex/Downloads/next-intl-feat-next-13-rsc/examples/example-next-13-named-routes/node_modules/next/dist/server/require-hook.js:188:36
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18) {
  type: 'Error',
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'`

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/amannn/next-intl/tree/feat/next-13-rsc/examples/example-next-13-named-routes

### Reproduction description

Steps to reproduce:
1. Open terminal in folder, do npm install next, then npm run dev
2. Server won't run

### Expected behaviour

Expected to work.

**Comment by alexclinky** [comment]
I tried other packages with next 13.4.0 and same problem.

**Comment by Isaachi1** [comment]
next.config.js

![image](https://github.com/amannn/next-intl/assets/14861271/aab8f472-1d78-4403-b702-2bb6f347eddd)

**Comment by Isaachi1** [comment]
Maybe you didn't realize that the doc has a code similar to the one in my print below. However, when I went to implement it following the doc, it shows that the "next-intl/server" module does not have any "getRequestConfig" function being exported.

![image](https://github.com/amannn/next-intl/assets/14861271/b87af96e-32d3-4d1d-bc73-a664befb1674)

Actually this module has several bugs. :/

**Comment by Isaachi1** [comment]
I managed to fix it as follows:

npm install next-intl@2.15.0-beta.5
or
yarn add next-intl@2.15.0-beta.5

**Comment by webdiego** [comment]
> I managed to fix it as follows:
> 
> npm install next-intl@2.15.0-beta.5 or yarn add next-intl@2.15.0-beta.5

Yes, the same, I had to going back to this version: **next-intl@2.15.0-beta.5**

**Comment by amannn** [comment]
`next-intl@2.15.0-beta.5` is the latest beta version that contains RSC support, so it is required to use as mentioned above.

Since the original bug report mentioned the example contained in this repo: As mentioned in [the contributors guide](https://github.com/amannn/next-intl/blob/main/CONTRIBUTORS.md), you need to use pnpm to link a local build of `next-intl`.

**Comment by velychkodmytro20** [comment]
> `next-intl@2.15.0-beta.5` is the latest beta version that contains RSC support, so it is required to use as mentioned above.
> 
> Since the original bug report mentioned the example contained in this repo: As mentioned in [the contributors guide](https://github.com/amannn/next-intl/blob/main/CONTRIBUTORS.md), you need to use pnpm to link a local build of `next-intl`.


If we want to use 2.19 version, will there be server components? 
Can you please provide info how can we use 2.19 version with getRequestConfig and server components as in early versions
And can you please provide a migration plan?

!!! Important !!! 
An Error Module ‘“next-intl/server”’ has no exported member ‘getRequestConfig’.ts  still exists in 2.19.0 / 2.19.1 versions

**Comment by amannn** [comment]
RSC support is only available in the RSC beta version referenced here: https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components

See also https://github.com/amannn/next-intl/issues/286#issuecomment-1543617410
