### ISSUE TITLE
Reload on message file updates

### ISSUE THREAD

**Issue by mattiloh** [amannn/next-intl#33]
Hi @amannn!
First of all: Great work! I really like the simplicity and flexibility of this lib 👍 

I started experimenting with it in a new project today (using `next@10.2.0`) and one thing is bothering me: I need to manually stop and restart the Next.js dev server to make updates on json message files visible. Do you have the same issue in your dev-setup or did you find a way to restart the server automatically?

**Comment by mattiloh** [comment]
Never mind. I don't know what I changed, but know the server restarts whenever I update the message files. I still need to manually reload the page to see the changes, but that's ok.

**Comment by amannn** [comment]
Hi @mattiloh,

thank you for giving next-intl a shot and your feedback! 🙂

The messages not updating sounds odd to me. I've just [upgraded the example in this repo to the latest Next.js version](https://github.com/amannn/next-intl/commit/35368b943eb1e87f47108f387569913f8a7150ef) and I get updated messages when I reload the page.

The update mechanism ultimately depends on how you provide your labels. If they're imported in client code statically, I think you'd even get Fast Refresh support. But if they come from `getStaticProps` and friends you need a page reload.

**Comment by mattiloh** [comment]
Yes, that's correct. I found this repo to get page-reloads for these cases: https://github.com/hashicorp/next-remote-watch

**Comment by amannn** [comment]
Oh that's nice, thanks for sharing!

**Comment by kachkaev** [comment]
What’s the current recommended way of page reloading when translations change? `next-remote-watch` does not work with Next.js 13 and 14: https://github.com/hashicorp/next-remote-watch/pull/52
