### ISSUE TITLE
Docs: Clicking on "Edit this page" leads to a 404

### ISSUE THREAD

**Issue by hb20007** [amannn/next-intl#330]
### Description

Clicking on "Edit this page" in the docs leads to a "404 - page not found". For example, clicking on it from the Getting Started page redirects to https://github.com/amannn/next-intl/blob/main/packages/website/pages/docs/getting-started.mdx which looks like this:
![screenshot](https://github.com/amannn/next-intl/assets/8860322/e39a676a-eb67-4317-bcb8-4ae046a7c1e2)

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://next-intl-docs.vercel.app/docs/getting-started

### Reproduction description

Steps to reproduce:
1. Open https://next-intl-docs.vercel.app/docs/getting-started
2. Click on "Edit this page"

### Expected behaviour

It should open the correct path in the repository, For example, https://github.com/amannn/next-intl/blob/main/docs/pages/docs/getting-started.mdx

**Comment by amannn** [comment]
Many thanks for the report! This will be fixed as part of #333
