### ISSUE TITLE
Improve Static Export by removing limitations

### ISSUE THREAD

**Issue by predrag-codetribe** [amannn/next-intl#344]
### Is your feature request related to a problem? Please describe.

We have a project with static export enabled:
```
const nextConfig = {
	output: 'export',
}
```

There's no default locale that can be used without a prefix (same as [localePrefix: 'always'](https://next-intl-docs.vercel.app/docs/next-13/middleware#always-use-a-locale-prefix))

Which means if I have a folder structure like this:
```
├── app
│   ├── [locale]
│   │   ├── about
│   │   ├── layout.tsx
│   │   └── page.tsx
│   ├── favicon.ico
│   ├── layout.tsx
│   └── page.tsx
```

and run `npm run build`
the following out dir will be generated:
```
├── 404.html
├── _next
│   ├── static
│   │   ├── chunks
│   │   └── yZyBHk4RaFZL2T2S_nr7o
│   └── yZyBHk4RaFZL2T2S_nr7o
├── en
│   ├── about.html
│   └── about.txt
├── en.html
├── en.txt
├── favicon.ico
├── next.svg
├── sr
│   ├── about.html
│   └── about.txt
├── sr.html
├── sr.txt
└── vercel.svg
```
The following routes are generated:

```
/en
/en/about

/sr
/sr/about
```

**NOTE** there are no `/` and `/about` routes.

-----

Here is a repro repo ->
[example.zip](https://github.com/amannn/next-intl/files/11846638/example.zip)

### Describe the solution you'd like

I would expect that `npm run build` to also generate `/` (to point to `/en`) and `/about` (to point to `/en/about`)

Request examples:
I would expect that the following middleware:
```ts
import createMiddleware from 'next-intl/middleware';

export default createMiddleware({
  // A list of all locales that are supported
  locales: ['en', 'sr'],

  // If this locale is matched, pathnames work without a prefix (e.g. `/about`)
  defaultLocale: 'en',
  localePrefix: "as-needed"
});

export const config = {
  // Skip all paths that should not be internationalized
  matcher: ['/((?!api|_next|.*\\..*).*)']
};
```
creates the following routes:
```
/ → /en
/about → /en/about
/sr/about → /sr/about
```

> NOTE: I know that the middleware is not available for static exports, but maybe there is away to reuse the passed next-intl config to generate the routes.

### Describe alternatives you've considered

Right now I am using the workaround describe in https://next-intl-docs.vercel.app/docs/next-13/middleware#usage-without-middleware-static-export

I redirect from '/' to `/en`
```ts
// app/page.tsx
import {redirect} from 'next/navigation';
 
// Redirect the user to the default locale when the app root is requested
export default function RootPage() {
  redirect('/en');
}
```

this is not prefect, because if I also need to support other routes, like `/about`, I would have to do the same thing for that route...

**Comment by amannn** [comment]
Right, I see your point! I'm afraid though that i18n routing without a prefix is not possible with static exports. As mentioned in the docs, the middleware doesn't run at all and features like [rewrites are not available](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#unsupported-features).

I guess the only option would be to configure some rewrites where your static files are hosted.

I'd love to be proven wrong, but I think this is a tradeoff you have to live with if you require a static export.
