### ISSUE TITLE
Can’t fetch data

### ISSUE THREAD

**Issue by wCatly** [amannn/next-intl#346]
### Description

I use App Router and client Side components instead of getting json from file I tried to make api request to my server but it didn’t work it says x not found 

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

Don’t have

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: …
4. 

### Expected behaviour

Fetch data success and display

**Comment by amannn** [comment]
Closing since the issue template was ignored and this is a usage question, not a bug report.
