### ISSUE TITLE
Module '"next-intl/server"' has no exported member 'getRequestConfig'.ts(2305)

### ISSUE THREAD

**Issue by bfovez** [amannn/next-intl#356]
### Description

I try to use the new feature here: Next.js 13: Internationalization (i18n) in Server Components
But, when creating the i18n.ts file (doc here https://next-intl-docs.vercel.app/docs/next-13/server-components#i18nts), I bump into 
this typescript error:
Module '"next-intl/server"' has no exported member 'getRequestConfig'.ts(2305)
And indeed, the next-intl/server module does not contain such an export.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/bfovez/i18n-bug

### Reproduction description

Steps to reproduce:
1. Create a brand new Nextjs project: npx create-next-app (enable typescript and App router)
2. Install next-intl: npm install next-intl
3. Create a i18n.ts file in the src directory
4. Copy/paste the code in the docs here  https://next-intl-docs.vercel.app/docs/next-13/server-components#i18nts
5. See the typescript error

### Expected behaviour

Well, not a typescript error.

**Comment by amannn** [comment]
You need to use the beta version as stated here at the very top: https://next-intl-docs.vercel.app/docs/next-13/server-components

**Comment by bfovez** [comment]
Thank you!

**Comment by Jacsonrai** [comment]
Module '"next-intl/server"' has no exported member 'getRequestConfig'.ts(2305)
And indeed, the next-intl/server module does not contain such an export.

dependency :
"next-intl": "^3.0.0-beta.6",

create i18n.tsx as :
import { headers } from "next/headers";
import { getRequestConfig } from "next-intl/server";

export default getRequestConfig(async ({ locale }) => {
  const now = headers().get("x-now");
  const timeZone = headers().get("x-time-zone") ?? "Europe/Vienna";
  const messages = (await import(`../messages/${locale}.json`)).default;

  return {
    now: now ? new Date(now) : undefined,
    timeZone,
    messages,
    defaultTranslationValues: {
      globalString: "Global string",
      highlight: (chunks) => <strong>{chunks}</strong>,
    },
    formats: {
      dateTime: {
        medium: {
          dateStyle: "medium",
          timeStyle: "short",
          hour12: false,
        },
      },
    },
    onError(error) {
      if (
        error.message ===
        (process.env.NODE_ENV === "production"
          ? "MISSING_MESSAGE"
          : "MISSING_MESSAGE: Could not resolve `missing` in `Index`.")
      ) {
        // Do nothing, this error is triggered on purpose
      } else {
        console.error(JSON.stringify(error.message));
      }
    },
    getMessageFallback({ key, namespace }) {
      return (
        "`getMessageFallback` called for " +
        [namespace, key].filter((part) => part != null).join(".")
      );
    },
  };
});

**Comment by velychkodmytro20** [comment]
We still have an error with Module '"next-intl/server"' has no exported member 'getRequestConfig'.ts(2305) on almost every version of next intl (NOT 2.15.beta... / 3.0.0.beta.... / 2.13...) 

How can we fix it on 2.19 / 2.16 / 2.18 versions?

**Comment by scerelli** [comment]
same here beta.17

**Comment by manu-kz** [comment]
The version 3.0.0-rc.6 does not work with the new Next 14 and this problem appears again, does someone know if a new version is planed to work properly with Next 14?

**Comment by amannn** [comment]
Support for Next.js 14 has already been implemented: https://github.com/amannn/next-intl/issues/584#issuecomment-1791334022. If you encounter an error related to `getRequestConfig`, please open a new issue with a reproduction.
