### ISSUE TITLE
Unusable 2.15.1 with Next.js App router

### ISSUE THREAD

**Issue by arekrgw** [amannn/next-intl#364]
### Description

```
const withNextIntl = require('next-intl/plugin')();
```

The import above doesn't work (there is no './plugin' subpath error), so the whole package is unusable with Next.js App router
On the version `2.15.0-beta.5` it works.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

Not needed

### Reproduction description

Steps to reproduce:
1. Scaffold basic Next.js App router app
2. Try to wire up next-intl@2.15.1, following the docs for the react server components
3. Run `npm run dev` -> app won't start

### Expected behaviour

Application starts without errors in development mode

**Comment by NastykSwED** [comment]
Hello mate, it seems that you are missing the path where the i18n configuration is located: 
`const withNextIntl = require('next-intl/plugin')('./i18n.ts');`
https://next-intl-docs.vercel.app/docs/next-13/server-components

**Comment by amannn** [comment]
You need to use [a Server Components beta version](https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components) to use the plugin.

Sorry if there's been confusion with the versioning (see https://github.com/amannn/next-intl/issues/286). We're now using a major version for RSC support, so this should not happen anymore.

**Comment by aknguyen11906** [comment]
> You need to use [a Server Components beta version](https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components) to use the plugin.
> 
> Sorry if there's been confusion with the versioning (see #286). We're now using a major version for RSC support, so this should not happen anymore.

Thank for your very quick reply!
