### ISSUE TITLE
No matching version found

### ISSUE THREAD

**Issue by alithecodeguy** [amannn/next-intl#37]
"npm i next-intl" cause "npm ERR! notarget No matching version found for use-intl@^1.3.11" since 4 hours ago.

OSX 11.4
npm 7.15.1
node version 16.3.0

I removed node_modules , npm cache clean and package-lock and even "npm update" but nothing happened.
finally i used yarn and the error happened again but it show me a list of use-intl versions but there were no 1.3.11 version. so i chose the 1.3.3 version of that and it worked.

log:
ali@Alis-MBP nnr % npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for use-intl@^1.3.11.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ali/.npm/_logs/2021-06-16T10_37_33_062Z-debug.log

**Comment by amannn** [comment]
Thanks for the heads up! In `next-intl@1.4.1` this is resolved.
