### ISSUE TITLE
Getting "MISSING_MESSAGE: No messages were configured on the provider" when generating static pages

### ISSUE THREAD

**Issue by pierrebiver** [amannn/next-intl#374]
### Description

I'm still using the page folder in next js and when using a component in `_app.tsx` that renders for every page (like a navbar or footer for instance) and when I use `getStaticProps` with `getStaticPaths` (e.g  `folderA/[id].tsx`) . I'm getting errors in the console such as "MISSING_MESSAGE". It would be harmless as it eventually load and works in dev, but I realized I was getting a lot of those while building my static pages when deploying to prod, and does not work at all in a deployed environment(getting a 500 from Next js and my page does not load at all ). I'm happy to provide more logs and screenshot if need be. 

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-pages-krm37f

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Go to URL `test/whatever` 
3. See error in console: MISSING_MESSAGE: No messages were configured on the provider

### Expected behaviour

No error should popup in console nor during static pages build time.

**Comment by amannn** [comment]
I can unfortunately not reproduce the bug, navigating to https://krm37f-3000.csb.app/test/whatever works fine for me. I don't think anything was changed in the reproduction.

Please also see other related issues: https://github.com/amannn/next-intl/issues?q=is%3Aissue+MISSING_MESSAGE+is%3Aclosed (esp. https://github.com/amannn/next-intl/issues/87)

**Comment by pierrebiver** [comment]
Ah my bad, I think I did not pas the right link for the reproduction but it seems to be related to the `fallback:true` option in the static props. Maybe you could add that to your doc ?

**Comment by floatrx** [comment]
> [@pierrebiver](https://github.com/pierrebiver) could you explain how u solved it ?

If you have a custom providers component, ensure that `NextIntlClientProvider` receives the `locale` and `messages` props. 

For example:

```tsx
// layout.tsx
import { setRequestLocale, getMessages } from 'next-intl/server';
...

const BaseLayout = ({ children, params }) => {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  const messages = await getMessages({ locale });

  return (
    <html>
    <body>
    <Providers i18n={{ locale, messages }}>
      {children}
      <SiteFooter />
    </Providers>
    </body>
    </html>
  );
};
// some code was omitted to clarify the example
```

```tsx
// providers.tsx
export interface ProvidersProps {
  children: ReactNode;
  i18n: {
    locale: Locale;
    messages: Messages;
  };
}

export function Providers({children, i18n}: ProvidersProps) {
  return (
    <NextIntlClientProvider {...i18n}>
      <OtherProvider>
        {children}
      </OtherProvider>
    </NextIntlClientProvider>
  );
}
```
