### ISSUE TITLE
 how to change locale programmatically

### ISSUE THREAD

**Issue by pkvov** [amannn/next-intl#390]
### Is your feature request related to a problem? Please describe.

is this the only way to change lang by Link?

// When the user is on `/en`, the link will point to `/en/about`
<Link href="/about">About</Link>
 
// You can override the `locale` to switch to another language
<Link href="/" locale="de">Switch to German</Link>

### Describe the solution you'd like

const [locale, setLocale] = useLocale()

setLocal('en')

setLocal('fi')

### Describe alternatives you've considered

const [locale, setLocale] = useLocale()

setLocal('en')

setLocal('fi')

**Comment by amannn** [comment]
Duplicate of https://github.com/amannn/next-intl/issues/253
