### ISSUE TITLE
Unable to use useLocale in async data fetching server component

### ISSUE THREAD

**Issue by Mbensler** [amannn/next-intl#392]
### Description

I am using the new app dir, and i have a server component with code that looks like this:

```js

// React
import React from 'react';

// next-intl
import { useLocale } from 'next-intl';
import { getTranslator } from 'next-intl/server';
import Link from 'next-intl/link';

async function getData() {
 my fetch request is here and return data
}

export default async function Banner() {
  const data = await getData();

  const locale = useLocale();
  const t = await getTranslator(locale, 'Components.Misc');

  return (
    <p>All my html here </p>
  )
}

```

Vercel is giving me the following error:
Error: React Hook "useLocale" cannot be called in an async function.  react-hooks/rules-of-hooks

I am not able to pass the locale down as a prop to this async component either. Only to a non async component.

The component works just fine locally, but wont compile to Vercel.

### Expected behaviour

I expected it to compile since it works just fine.

**Comment by amannn** [comment]
Duplicate of https://github.com/amannn/next-intl/discussions/276

**Comment by Mbensler** [comment]
> Duplicate of #276

I see, I got it working with that, thanks a lot :)
