### ISSUE TITLE
It is not possible to use it in the error.js page.

### ISSUE THREAD

**Issue by sawa-ko** [amannn/next-intl#400]
### Description

Currently I don't see any example of how to implement the translations in the error.js file of nextjs 13.

This solution does not work because the page cannot be asynchronous: https://next-intl-docs.vercel.app/docs/getting-started/app-router-client-components#next-intl-client-provider

The hooks useTranslation and getTranslator cannot be used either.

This solution also does not work because the hooks useLocale and useMessages cannot be used: https://next-intl-docs.vercel.app/docs/environments/server-client-components#option-3-providing-individual-messages

I am currently using nextjs v13.4.9 and next-intl v3.0.0-beta.7.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

N/A

### Reproduction description

Steps to reproduce:
1. Create a error.js page.
2. Try to translate with hooks.

### Expected behaviour

Any way to translate the error.js page.

**Comment by amannn** [comment]
Thank you for the question! We now have official docs on this: https://next-intl-docs.vercel.app/docs/environments/error-files

Hope this helps!
