### ISSUE TITLE
Load multiple namespaces

### ISSUE THREAD

**Issue by Industrial** [amannn/next-intl#41]
**Is your feature request related to a problem? Please describe.**
We have lots of duplicated translation strings

**Describe the solution you'd like**
To be able to pass an array of namespaces so that we can put common translations in common json files.

**Describe alternatives you've considered**
Putting everything in one namespace and adding namespacing on the translation key

**Comment by amannn** [comment]
Hi @Industrial,

thanks for the request! I've got a section on how I suggest to structure messages for such scenarios: https://github.com/amannn/next-intl/blob/main/docs/usage.md#structuring-messages. I typically reuse labels by reusing components.

You don't have to follow this convention though.

You can retrieve all labels like this:

```js
const t = useTranslations();
```

When you do that, you can access all messages from any namespace you like. This is helpful if there's no real common denominator for your messages.

I'm a bit hesitant about adding new API when there's already a way to solve this with existing functionality.

Does that help?

**Comment by Industrial** [comment]
Hi!

Sometimes it is not possible to put everything inside it's own component. Instead, I'm now sometimes using multiple `t` functions in the same component to retrieve translations in different translation files.

```ts
const t = useTranslations('thisComponent')
const translateProductCategories = useTranslations('productCategories')
```

This works well enough :-)

**Comment by amannn** [comment]
Ok, good to hear if you found a workaround!

To be honest I'm still wondering if this should be more ergonomic. So far I was considering using the lowest common denominator for the namespace of the `useTranslations` hook.

But in practice that could mean omitting it totally. Like for example your use case could be solved like:

```js
const t = useTranslations();
t('thisComponent.someLabel')
t('productCategories.anotherLabel')
```

However maybe if there are some optimisations in the future, it could be easier to optimise if we know the particular namespaces.

An API like this could also work:

```js
const t = useTranslations(['thisComponent', 'productCategories']);
t('someLabel')
t('anotherLabel')
```

The downside here is that there could be conflicts and we'd have to error out on those. Also it might be too magical where a particular translation comes from.

I'm just not sure yet, I'm just thinking aloud here.

**Comment by Industrial** [comment]
Instead of throwing an error, you could also create the total object of translations by extending it from the right.

```ts
const allTranslations = translations.reduce((a, x) => { ...a, ...x }, {}) // probably not the most efficient way to implement
```

But maybe this is too simple for people and when 'losing' translations due to double entries they'd be lost..

**Comment by amannn** [comment]
>  'losing' translations due to double entries they'd be lost..

That's what I was worried about as well. But sure, merging is also an option. Let's see, maybe there are other use cases which provide some more context about how this feature would make sense.
