### ISSUE TITLE
Routing not working for default language without prefix

### ISSUE THREAD

**Issue by combi-35** [amannn/next-intl#412]
### Description

My project is setup using catch all routes with `[[...slug]]` (using a headless CMS). I also setup everything for `next-intl` and it's working as expected, except for handling default routes with no locale prefix, as described here [Prefix based routing](https://next-intl-docs.vercel.app/docs/routing/middleware#prefix-based-routing)
So `localhost:3000/de` is working but `localhost:3000/` is not.

If I am trying to access `localhost:3000/about` I see that `about` is assumed to be the language code...

```
import createMiddleware from "next-intl/middleware"

export default createMiddleware({
  // A list of all locales that are supported
  locales: ["de"],

  // If this locale is matched, pathnames work without a prefix (e.g. `/about`)
  defaultLocale: "de",
})

export const config = {
  // Skip all paths that should not be internationalized. This example skips the
  // folders "api", "_next" and all files with an extension (e.g. favicon.ico)
  matcher: ["/((?!api|_next|.*\\..*).*)"],
}
```
![Bildschirmfoto 2023-07-20 um 16 02 05](https://github.com/amannn/next-intl/assets/56366138/1e1054a4-ced9-4110-95e1-715e7efbb4b6)

layout.tsx

```
type Props = {
  children: React.ReactNode
  params: {
    locale: string
  }
}

export function generateStaticParams() {
  return [{ locale: "de" }]
}

export default async function RootLayout({
  children,
  params: { locale },
}: Props) {
  let messages
  console.log("Locale: ", locale)
  try {
    messages = (await import(`../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }

  return (
      <html lang={locale}>
        <body>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
  )
}
```
Any help is very appreciated, thanks!

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

N/A

### Reproduction description

See above

### Expected behaviour

Path without language code should show default language translations.

**Comment by amannn** [comment]
Can you please provide the mandatory reproduction? Without this, it's unfortunately not possible for me to help you and I'll have to close the issue. I hope you understand.

**Comment by brendansimcox** [comment]
@combi-35 if it helps, i was experiencing the same issue and noticed that my middleware.ts file was not within my "/src" directory, fairly easy mistake to make - looking at the screenshot - i can't tell for sure, but the moment i moved my middleware.ts file into my src (as apposed to the base path) it started working for me

**Comment by combi-35** [comment]
Sorry for the late reply!

@brendansimcox Thanks a lot, indeed moving my middleware inside my src folder solved the problem. Thank you :)

**Comment by ThijmenGThN** [comment]
Unfortunately, the solution mentioned by @combi-35 is not feasible for my particular project because it does not rely on the use of a source directory.

If anyone has come across a solution that could work for my situation, I would greatly appreciate hearing about it 😄
