### ISSUE TITLE
Link prefetch causes locale to be switched without user interaction

### ISSUE THREAD

**Issue by philefstat** [amannn/next-intl#414]
### Description

Context:
- Following [docs](https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components#i18nts) for app router with server components
- Not using static generation
- 

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/philefstat/next-intl-bug-template-app-forked-

### Reproduction description

1. Clone reproduction & `npm install`
2. Important - since prefetch only is enabled in production, run `npm run build && npm run start` rather than `dev`
3. Page loads with english (should say "welcome"). If you reload without scrolling, it stays english. 
4. Scroll to the bottom of the page where there are two links, one to `/en`, one to `/fr`. Do NOT click the links. 
5. Refresh the page - the locale has now switched to `fr` (page should say "bienvenue") despite the links not having been clicked

Optional
1. Set `prefetch={false}` on the french link and try the steps above again - the locale does NOT switch now

### Expected behaviour

Locale should not switch when there are links to a different locale but the user hasn't clicked them.

Perhaps it's simply a matter of updating the docs to indicate that links in a different locale should have `prefetch={false}`, but ideally the middleware would detect that it's a prefetch and not set the cookie in this case (I don't know if this is possible or not).

**Comment by amannn** [comment]
The issue happens because you're using `next/link` instead of [`next-intl/link`](https://next-intl-docs.vercel.app/docs/routing/navigation#link) (which sets `prefetch` accordingly).

Hope this helps!

**Comment by philefstat** [comment]
@amannn 🤦 thanks!
