### ISSUE TITLE
Error: INVALID_MESSAGE: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by slvstr-dev** [amannn/next-intl#415]
### Description

I'm trying to use use-intl for my Expo project. From what I see from the FAQ this package should work with React Native. Currently using the Expo setup as described in #176 (+ file based routing), but with no success. Not 100% sure if this is a bug or that this package doesn't support Expo Router.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/slvstr-dev/eurovision-bingo

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Install project through `pnpm`
3. Run project with `pnpm ios` or `pnpm android`
4. Check console error `Error: INVALID_MESSAGE: Cannot read property 'prototype' of undefined`

### Expected behaviour

I expect the translation in `index.tsx` to render the string `Hello world!`.

**Comment by amannn** [comment]
I think the issue might be that some `Intl` APIs are missing in that environment (see [the next-intl runtime requirements](https://next-intl-docs.vercel.app/docs/production-checklist#runtime-requirements)).

I tried running your app on iOS 16.4 via the simulator and it seems like `Intl` is an empty object there (e.g. no `Intl.Locale`).

Can you try polyfilling the required APIs? If this works, I guess we should add a statement about this to the docs.

**Comment by slvstr-dev** [comment]
@amannn thanks, will try this when I have time working on the app again. I'll let you know.

**Comment by slvstr-dev** [comment]
@amannn ok the fix was pretty easy after all. Just needed to add Hermes to my project so that `Intl` is available/polyfilled. Will open a PR to add a statement to the docs later on.

https://docs.expo.dev/guides/localization/#intl-api

**Comment by amannn** [comment]
Ah, that makes sense!

> Will open a PR to add a statement to the docs later on.

Thank you so much! 🙌

**Comment by amannn** [comment]
@slvstr-dev Did you by chance find a moment for the docs PR? 🙃 I don't work with React Native much, might be helpful if someone who has more experience with RN includes a disclaimer!

You can edit the FAQ page directly on GitHub and add a PR: https://github.com/amannn/next-intl/blob/main/docs/pages/docs/faq.mdx

**Comment by amannn** [comment]
[The React Native FAQ entry](https://next-intl-docs.vercel.app/docs/faq#can-next-intl-be-used-with-react-native) now has a special mention of the runtime requirements. I think this should do for now.

**Comment by kgni** [comment]
@slvstr-dev sorry to bother you, but did get it to work only with hermes or did you also add polyfills manually?

I'm on `expo 50` // `react-native 0.73.4` using hermes, and I'm still getting this issue

**Comment by slvstr-dev** [comment]
@kgni np, my focus shifted quickly after adding this issue and I missed the tagging above. Haven't been able to work on multi-language any further.

**Comment by kgni** [comment]
Seems like you still need polyfills for certain Intl calls even when using hermes - https://github.com/expo/config-plugins/issues/73

I added the formatjs polyfill imports to my entrypoint and now everything works like a charm.

Thanks for taking the time to respond @slvstr-dev!

**Comment by ranlix** [comment]
> Seems like you still need polyfills for certain Intl calls even when using hermes - [expo/config-plugins#73](https://github.com/expo/config-plugins/issues/73)
> 
> I added the formatjs polyfill imports to my entrypoint and now everything works like a charm.
> 
> Thanks for taking the time to respond [@slvstr-dev](https://github.com/slvstr-dev)!

I tried to add polyfills and enable hermes engine in app.json like this:
```json
// app.json
{
  "expo": {
    "name": "mobile",
    "slug": "mobile",
    "version": "1.0.0",
    "jsEngine": "hermes",
    "ios": {
      "supportsTablet": true
    },
    ...
}
```

```typesctips
// LocaleContext.tsx

// // Polyfills must be imported first
import '@formatjs/intl-pluralrules/polyfill-force'

// // Then import locale data
import '@formatjs/intl-pluralrules/locale-data/en'
import '@formatjs/intl-pluralrules/locale-data/es'

import { messages } from '@repo/shared/infra/i18n'
import { locales as supportedLocales, type Locale } from '@repo/shared/infra/i18n/config'
import AsyncStorage from '@react-native-async-storage/async-storage'
import React, { createContext, useContext, useEffect, useState } from 'react'
import { IntlProvider } from 'use-intl'

interface LocaleContextType {
  locale: Locale
  setLocale: (locale: Locale) => Promise<void>
}

const LocaleContext = createContext<LocaleContextType | undefined>(undefined)

export const LocaleProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>('en')

  useEffect(() => {
    // 初始化时读取保存的 locale
    const initLocale = async () => {
      const savedLocale = await AsyncStorage.getItem('userLocale')
      if (savedLocale && supportedLocales.includes(savedLocale as Locale)) {
        setLocaleState(savedLocale as Locale)
      }
    }
    initLocale()
  }, [])

  const setLocale = async (newLocale: Locale) => {
    try {
      await AsyncStorage.setItem('userLocale', newLocale)
      setLocaleState(newLocale)
    } catch (error) {
      console.error('Error saving locale:', error)
    }
  }

  return (
    <LocaleContext.Provider value={{ locale, setLocale }}>
      <IntlProvider
        messages={messages[locale]}
        locale={locale}
        onError={(error) => {
          console.warn('IntlProvider error:', error)
          if (error.code === 'FORMATTING_ERROR') {
            return
          }
          throw error
        }}
      >
        {children}
      </IntlProvider>
    </LocaleContext.Provider>
  )
}

export const useLocale = () => {
  const context = useContext(LocaleContext)
  if (!context) {
    throw new Error('useLocale must be used within LocaleProvider')
  }
  return context
}

```

```jsx
// messages: "minutes": "{count, plural, =1 {1 minute} other {# minutes}}"

<ThemedView>
  <ThemedText type="subtitle">t with plurals</ThemedText>
  <ThemedText>{t('unit.minutes', { count: 42 })}</ThemedText>
</ThemedView>
```
And then there is a error warning:
**IntlProvider error: [Error: FORMATTING_ERROR: Cannot read property 'prototype' of undefined] [Component Stack]**
