### ISSUE TITLE
Unable to Use 'router.replace' with Custom Locale Parameter

### ISSUE THREAD

**Issue by PixelPage-YT** [amannn/next-intl#420]
### Description

I know this is not directly related to next-intl, but it's recommended in the docs and i need an alternative.
I encountered an issue while attempting to use the 'router.replace' method in combination with a custom 'locale' parameter. However, I received an error message stating, "Argument of type '{ locale: string; }' is not assignable to parameter of type 'Url | undefined'. Object literal may only specify known properties, and 'locale' does not exist in type 'UrlObject'.ts(2345)."

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-forked-yow8ep

### Reproduction description

1. Follow the documentation link provided (https://next-intl-docs.vercel.app/docs/routing/navigation#userouter) to learn about the recommended approach for routing with internationalization using 'router.replace'.
2. Implement the 'router.replace' method with the 'pathname' and 'locale' parameters in your Next.js application as described in the documentation.
3. Observe the TypeScript error mentioned above when attempting to compile the application.

### Expected behaviour

The user should be redirected to the current page with the correct translation provided.

**Comment by PixelPage-YT** [comment]
This is my temporary solution:
```ts
router.push(e + '/' + pathname.replace(/\/(de|en)?\/?/,'/'))
```

**Comment by amannn** [comment]
I unfortunately don't see anything changed in the CodeSandbox you've linked to. Can you please make sure to include a reproduction that shows the erroneous behavior?

**Comment by gc7g** [comment]
I'm experiencing the exact same problem

**Comment by mp3por** [comment]
Me too :)
