### ISSUE TITLE
A function that gives the available locales

### ISSUE THREAD

**Issue by Natchii59** [amannn/next-intl#430]
### Is your feature request related to a problem? Please describe.

No there is no problem. It's just that it's annoying to see the list of available locales rewritten each time.

### Describe the solution you'd like

I would like us to be able to retrieve via a function the list of all available locales that we have put in the messages/locales folder.

### Describe alternatives you've considered

Write each time an array of strings with the available locales.

**Comment by amannn** [comment]
You can already achieve this by importing the available locales from a shared module. The list of all locales is currently only known to the middleware, therefore we can't expose this e.g. via the provider anyway.

Hope this helps!
