### ISSUE TITLE
Keep locale after session was closed

### ISSUE THREAD

**Issue by Natchii59** [amannn/next-intl#431]
### Is your feature request related to a problem? Please describe.

When I close and open my site, it resumes my language preferences, instead of keeping the language I had chosen recently.

### Describe the solution you'd like

Add the ability to keep the previous language.

### Describe alternatives you've considered

The language is stored in a cookie whose age is the current session. You should fix that or store it in localStorage. Or have the possibility of saying which language to use from a user that is retrieved via database or from a token (Auth.js). That would be the best thing to do.

**Comment by Natchii59** [comment]
> I've added https://github.com/amannn/next-intl/pull/435 to set the max-age to one year. Does this sound right to you?

Is it possible to customize this? (Change the max-age as desired) @amannn

**Comment by amannn** [comment]
Currently not, no. Do you have a need for it? My assumption is that you'd want to keep a manually changed locale around for as long as possible.

**Comment by Natchii59** [comment]
I think it would be better for developers, depending on their needs
