### ISSUE TITLE
Update Crowdin's Logo

### ISSUE THREAD

**Issue by andrii-bodnar** [amannn/next-intl#438]
### Is your feature request related to a problem? Please describe.

Crowdin has recently [updated its logo](https://crowdin.com/blog/2023/07/31/what-is-new-at-crowdin-july-2023#updated-crowdin-logo-unveiled)

### Describe the solution you'd like

Updating the logo everywhere in the repo where it's presented. [Using the Crowdin Logo](https://support.crowdin.com/using-logo/)

### Describe alternatives you've considered

\-

**Comment by amannn** [comment]
Hey @andrii-bodnar, so nice to hear from you!

The new logo looks really cool, congrats on the update! The change should be online in a few moments.
