### ISSUE TITLE
passing locale through NextIntlProvider 

### ISSUE THREAD

**Issue by Mood-al** [amannn/next-intl#44]
Hey guys 
I'm using next-intl for integrating multi langs in my site but i faced a little issue which is having the locale from the route 
because i need it to determine what language i want to show 

this is my data type  `{
    "home": {
    "ar": "الرئيسية",
    "en": "Home"
    },
    "donate": {
    "ar": "تبرع",
    "en": "donate"
    }
}`

as you see u have [en - ar] inside the object 
so how im solving this is in every compenent i want to show translation i import the t method useTranslations and locale from useRouter like so 

`const t = useTranslations();
  const { locale } = useRouter();

return (

      <h5 className="mt-1 mb-0">{t(`home.${locale}`)}</h5>
)

`

so i dont want to import locale on every component that i want to translate so is there any way i can extract the locale from the
NextIntlProvider ??

**Comment by amannn** [comment]
`next-intl` intends to split messages by locale. This allows for smaller payloads, as you only load the messages for the locale that the user really needs.

If this is not an option for you, you could think about wrapping the `useTranslations` hook to apply the `locale` automatically when the `t` function is called.

**Comment by amannn** [comment]
I'll close this due to inactivity. I hope my previous message helps you.
