### ISSUE TITLE
Any way to escape dot notation when accessing translation keys? 

### ISSUE THREAD

**Issue by fobos531** [amannn/next-intl#453]
### Is your feature request related to a problem? Please describe.

Hello.

I was wondering whether it is possible to escape the dot notation in translation keys? For example, I have 

"Permissions": {
      "users.view": "View users",
 }

Now, if I try the translate this using translate("Permissions.users.view"), this won't work

### Describe the solution you'd like

A configurable option to define the "access character" when accessing translation keys, or the ability to escape the dots in the translation keys.

### Describe alternatives you've considered

N/A

**Comment by amannn** [comment]
This is currently not planned, but you can transform your messages before passing them to `next-intl` if you prefer to store them in a special format. Please see https://github.com/amannn/next-intl/discussions/148 for details.
