### ISSUE TITLE
Middleware causing full page reload when Link has prefetch={false}

### ISSUE THREAD

**Issue by zipme** [amannn/next-intl#460]
### Description

When the <Link> has prefetch={false}, navigation would cause a full page reload, this happens when middleware is being used.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/adoring-tu-8k2j6f?file=/app/[locale]/page.tsx:5,1-6,1

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on 'bar' link
3. Open network inspector/tab you can see the doc '/bar' got loaded.

### Expected behaviour

Should behave like a SPA intead of full page reload

**Comment by amannn** [comment]
In your reproduction I don't get a full reload when I click on the "bar" link and I also don't see any functionality from `next-intl` used in any relevant files.

Am I missing something?

**Comment by zipme** [comment]
hi @amannn 
>  I also don't see any functionality from next-intl used in any relevant files
There is and it's in the middleware: https://codesandbox.io/p/sandbox/adoring-tu-8k2j6f?file=/middleware.ts:1,1

> In your reproduction I don't get a full reload when I click on the "bar" link 
The bar link works fine because the `prefetch` is set to `false`, however, from the /bar page and if you click on the home link, which has the `prefetch={false}` you can see the full page reload

**Comment by zipme** [comment]
@amannn And if I remove the middleware everything works normally, that's why I thought the culprit might be the middleware

**Comment by zipme** [comment]
My apology that I noticed that my initial description mentioned clicking on the 'bar' which has the correct behavior. I updated the description.

**Comment by amannn** [comment]
Ah right, now I see. Here's a fix for your issue: https://github.com/vercel/next.js/issues/43118#issuecomment-1547408398

**Comment by zipme** [comment]
@amannn OH NICE! It works like a charm! Thank you very much!
