### ISSUE TITLE
Support for splitting messages into multiple files in a directory

### ISSUE THREAD

**Issue by iverks** [amannn/next-intl#483]
### Is your feature request related to a problem? Please describe.

Having all translations per language in a single file gets crowded for large projects. It would be nice to split them into multiple files based on namespace

### Describe the solution you'd like

Having my translation namespaces as files nested in the messages/en folder and the messages/no folder like so

```
├── messages 
│   ├── en
│   │       ├── common.json
│   │       ├── frontpage.json
│   │       └── ...
│   ├── no
│   │       ├── common.json
│   │       ├── frontpage.json
│   │       └── ...
│   └── ...
│   
```

### Describe alternatives you've considered

Manually importing every file with some clever loop in my `layout.tsx` and putting it into my messages.json

**Comment by amannn** [comment]
This has been discussed in https://github.com/amannn/next-intl/discussions/357 before, I hope this answers your question!

**Comment by amannn** [comment]
On a related note, there's now a VSCode integration for `next-intl` which helps to streamline the management of translations in large files: [VSCode integration docs](https://next-intl-docs.vercel.app/docs/workflows/vscode-integration).
