### ISSUE TITLE
Typing of return value of the `withNextIntl` function

### ISSUE THREAD

**Issue by boris-arkenaar** [amannn/next-intl#485]
### Is your feature request related to a problem? Please describe.

I have type checking on my `next.config.js` and I'm using `composePlugins` from `@nx/next`.
On `composePlugins` I get a ts error telling me

```
    Type '(config: NextConfig) => unknown' is not assignable to type 'NextPlugin'.
      Type 'unknown' is not assignable to type 'NextConfig'.
```

This is referring to `withNextIntl` which has apparently a typing of `(config: NextConfig) => unknown`.

### Describe the solution you'd like

Provide a typing of `NextConfig` for the return value of the `withNextIntl` function.

### Describe alternatives you've considered

Ignore TS errors with

```
// @ts-ignore
```

This ignores type checking on all my plugins.

**Comment by amannn** [comment]
Thank you for another great bug report! This is fixed in `next-intl@3.0.0-beta.14`, I hope it works correctly in your setup!

**Comment by boris-arkenaar** [comment]
Where can I keep track of the beta releases?

**Comment by amannn** [comment]
New features are announced in https://github.com/amannn/next-intl/pull/149 and bug fixes are mentioned in the issues that reference them, where typically the affected users are subscribed. The latest published version is always referenced here: https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components#current-beta-version

The release process for beta versions is currently a bit manual. The stable releases are easier to keep track of, I hope that the beta period will end in the foreseeable future so the releases are a bit more transparent.
