### ISSUE TITLE
Missing changed locale when reload the page 

### ISSUE THREAD

**Issue by Kennn-dev** [amannn/next-intl#49]
i see the Example on next 
https://stackblitz.com/edit/github-81zmya

****
When i change the Language  ( switch locale ) , everything is good , but when i reload the entire of page , the locale is missing and back to the default locale 

So how we can prevent this ?

**Comment by amannn** [comment]
I'm not familiar with StackBlitz, but it seems like they don't change the URL of the preview when the URL of the app changes. Also when you navigate to the about page the URL stays the same and is thus lost after a reload.

If you run the example natively in a browser this works as expected.

Does this help?

**Comment by Kennn-dev** [comment]
> I'm not familiar with StackBlitz, but it seems like they don't change the URL of the preview when the URL of the app changes. Also when you navigate to the about page the URL stays the same and is thus lost after a reload.
> 
> If you run the example natively in a browser this works as expected.
> 
> Does this help?

I Was try to create a new page using this , yeah its work ! Thanks for your help
