### ISSUE TITLE
Next 13, canonical and next-intl

### ISSUE THREAD

**Issue by RobSchilderr** [amannn/next-intl#498]
### Description

When adding the alternates at a specific page in the app router:
```
alternates: {
    canonical: 'https://domain.app/privacy',
    languages: {
      'en-US': '/en-US',
      'pl-PL': '/pl-PL',
      'tr-TR': '/tr-TR',
    },
  }
```

It always adds the language at the end, like: `htps://domain.app/privacy/en-US`, while next-intl work with `https://domain.app/en-US/privacy`.

How do we use the canonical in situations like this?

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

none

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

Not sure whether this is a Next.js issue or Next-intl should change its behavior.

**Comment by Felipeex** [comment]
Here is duplicated
