### ISSUE TITLE
Typing of 't' function when used as parameter inside a function 

### ISSUE THREAD

**Issue by fitimbyttyqi** [amannn/next-intl#500]
### Is your feature request related to a problem? Please describe.

Currently, I have a function that accepts the t function from useTranslations.

e.x const columns = (t: 'some type') => [...data];

The type of t was a bit difficult to find because it's not exported from the package as far as am aware?

### Describe the solution you'd like

What I would want to have is an exported type from the package which is easier to be found for beginners of this package.

e.x const columns = (t: TFunction) => [...data];

### Describe alternatives you've considered

Right now, I have created my own interface which extends from the package which looks like this.

I can also make a pull request if needed for this solution, please let me know ;)

```
export interface TFunction<
  NestedKey extends NamespaceKeys<
    IntlMessages,
    NestedKeyOf<IntlMessages>
  > = never
> {
  <
    TargetKey extends MessageKeys<
      NestedValueOf<
        {
          '!': IntlMessages;
        },
        [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
      >,
      NestedKeyOf<
        NestedValueOf<
          {
            '!': IntlMessages;
          },
          [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
        >
      >
    >
 ... more lines ....
```

**Comment by amannn** [comment]
This is currently not supported by design, please see these previous discussions:
- https://github.com/amannn/next-intl/discussions/128
- https://github.com/amannn/next-intl/issues/92

**Comment by adarshaacharya** [comment]
> export interface TFunction<
>   NestedKey extends NamespaceKeys<
>     IntlMessages,
>     NestedKeyOf<IntlMessages>
>   > = never
> > {
>   <
>     TargetKey extends MessageKeys<
>       NestedValueOf<
>         {
>           '!': IntlMessages;
>         },
>         [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
>       >,
>       NestedKeyOf<
>         NestedValueOf<
>           {
>             '!': IntlMessages;
>           },
>           [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
>         >
>       >
>     >

@fitimbytyqi  can you share your whole interface of this.


```ts
export type TFunction = ReturnType<typeof useTranslations<never>>;
```

Hre's what I'm using currently but its not that good.

**Comment by fitimbytyqi** [comment]
> > export interface TFunction<
> > NestedKey extends NamespaceKeys<
> > IntlMessages,
> > NestedKeyOf
> > > = never
> > > {
> > > <
> > > TargetKey extends MessageKeys<
> > > NestedValueOf<
> > > {
> > > '!': IntlMessages;
> > > },
> > > [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
> > > >,
> > > NestedKeyOf<
> > > NestedValueOf<
> > > {
> > > '!': IntlMessages;
> > > },
> > > [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
> > > >
> > > >
> > > >
> 
> @fitimbytyqi can you share your whole interface of this.
> 
> ```ts
> export type TFunction<
>   NestedKey extends NamespaceKeys<
>     IntlMessages,
>     NestedKeyOf<IntlMessages>
>   > = never,
> > = ReturnType<
>   typeof useTranslations<
>     NestedKey extends never ? NestedKeyOf<IntlMessages> : NestedKey
>   >
> >;
> ```
> 
> Here's what I'm using currently but its not that good.

Sure, here is the long version of it.

```typescript
import { ReactElement, ReactNode } from 'react';
import {
  Formats,
  MessageKeys,
  NamespaceKeys,
  NestedKeyOf,
  NestedValueOf,
  RichTranslationValues,
  TranslationValues,
} from 'next-intl';

export interface TFunction<
  NestedKey extends NamespaceKeys<
    IntlMessages,
    NestedKeyOf<IntlMessages>
  > = never,
> {
  <
    TargetKey extends MessageKeys<
      NestedValueOf<
        {
          '!': IntlMessages;
        },
        [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
      >,
      NestedKeyOf<
        NestedValueOf<
          {
            '!': IntlMessages;
          },
          [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
        >
      >
    >,
  >(
    key: TargetKey,
    values?: TranslationValues,
    formats?: Partial<Formats>
  ): string;
  rich<
    TargetKey extends MessageKeys<
      NestedValueOf<
        {
          '!': IntlMessages;
        },
        [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
      >,
      NestedKeyOf<
        NestedValueOf<
          {
            '!': IntlMessages;
          },
          [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
        >
      >
    >,
  >(
    key: TargetKey,
    values?: RichTranslationValues,
    formats?: Partial<Formats>
  ): string | ReactElement | ReactNode;
  raw<
    TargetKey extends MessageKeys<
      NestedValueOf<
        {
          '!': IntlMessages;
        },
        [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
      >,
      NestedKeyOf<
        NestedValueOf<
          {
            '!': IntlMessages;
          },
          [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
        >
      >
    >,
  >(
    key: TargetKey
  ): any;
}
```

**Comment by adarshaacharya** [comment]
> > > export interface TFunction<
> > > NestedKey extends NamespaceKeys<
> > > IntlMessages,
> > > NestedKeyOf
> > > > = never
> > > > {
> > > > <
> > > > TargetKey extends MessageKeys<
> > > > NestedValueOf<
> > > > {
> > > > '!': IntlMessages;
> > > > },
> > > > [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
> > > > > ,
> > > > > NestedKeyOf<
> > > > > NestedValueOf<
> > > > > {
> > > > > '!': IntlMessages;
> > > > > },
> > > > > [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
> > 
> > 
> > @fitimbytyqi can you share your whole interface of this.
> > ```ts
> > export type TFunction<
> >   NestedKey extends NamespaceKeys<
> >     IntlMessages,
> >     NestedKeyOf<IntlMessages>
> >   > = never,
> > > = ReturnType<
> >   typeof useTranslations<
> >     NestedKey extends never ? NestedKeyOf<IntlMessages> : NestedKey
> >   >
> > >;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's what I'm using currently but its not that good.
> 
> Sure, here is the long version of it.
> 
> ```ts
> import { ReactElement, ReactNode } from 'react';
> import {
>   Formats,
>   MessageKeys,
>   NamespaceKeys,
>   NestedKeyOf,
>   NestedValueOf,
>   RichTranslationValues,
>   TranslationValues,
> } from 'next-intl';
> 
> export interface TFunction<
>   NestedKey extends NamespaceKeys<
>     IntlMessages,
>     NestedKeyOf<IntlMessages>
>   > = never,
> > {
>   <
>     TargetKey extends MessageKeys<
>       NestedValueOf<
>         {
>           '!': IntlMessages;
>         },
>         [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
>       >,
>       NestedKeyOf<
>         NestedValueOf<
>           {
>             '!': IntlMessages;
>           },
>           [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
>         >
>       >
>     >,
>   >(
>     key: TargetKey,
>     values?: TranslationValues,
>     formats?: Partial<Formats>
>   ): string;
>   rich<
>     TargetKey extends MessageKeys<
>       NestedValueOf<
>         {
>           '!': IntlMessages;
>         },
>         [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
>       >,
>       NestedKeyOf<
>         NestedValueOf<
>           {
>             '!': IntlMessages;
>           },
>           [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
>         >
>       >
>     >,
>   >(
>     key: TargetKey,
>     values?: RichTranslationValues,
>     formats?: Partial<Formats>
>   ): string | ReactElement | ReactNode;
>   raw<
>     TargetKey extends MessageKeys<
>       NestedValueOf<
>         {
>           '!': IntlMessages;
>         },
>         [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
>       >,
>       NestedKeyOf<
>         NestedValueOf<
>           {
>             '!': IntlMessages;
>           },
>           [NestedKey] extends [never] ? '!' : `!.${NestedKey}`
>         >
>       >
>     >,
>   >(
>     key: TargetKey
>   ): any;
> }
> ```

thanks !

I think this type utility should be exported from library itself, very useful and typesafe.

**Comment by fitimbytyqi** [comment]
@adarshaacharya You are welcome, that would be nice but they don't plan on doing it, so we can use this as an alternative.

**Comment by danieljosue1233** [comment]
IntlMessages ???

**Comment by fplu** [comment]
Unfortunately, the code given in this thread seems to be outdated (it doesn't work for me as well @danieljosue1233 ).
Nevertheless, this thread is well referenced by Google, so here's an up to date solution I've found by checking the return value of `useTranslations` that works for me.

```ts
import {
  Formats,
  MarkupTranslationValues,
  RichTranslationValues,
  TranslationValues,
} from 'next-intl';

export type TFunction = {
  <TargetKey>(key: TargetKey, values?: TranslationValues, formats?: Formats): string;
  rich<TargetKey>(key: TargetKey, values?: RichTranslationValues, formats?: Formats): React.ReactNode;
  markup<TargetKey>(key: TargetKey, values?: MarkupTranslationValues, formats?: Formats): string;
  raw<TargetKey>(key: TargetKey): any;
  has<TargetKey>(key: TargetKey): boolean;
};
```

**Comment by fitimbytyqi** [comment]
Thank you for providing an updated solution, I haven't upgraded the package yet, but once I do I'll test this type out 👍

**Comment by FINDarkside** [comment]
The code above works, but one problem is that the value returned by `useTranslations` is not assignable to `TFunction`. Is there some reason to not just do this:
```ts
import type { createTranslator, Messages } from "next-intl";
export type TFunction = ReturnType<typeof createTranslator<Messages>>;
```
It seems to work at least for me.

**Comment by firehawk89** [comment]
@FINDarkside this worked for me too, thank you!

**Comment by danijeldzakula** [comment]
@FINDarkside it works for me. Thanks!

**Comment by giraffesyo** [comment]
This extends it to accept a type parameter like this
```ts
export const getMonitorPages = (t: TFunction<'sidebar'>): TNavigationItem[] => [
  {
    name: t('cost'),
   }
]
```	
Where the `<'sidebar'>` part is optional.


```ts
import type { createTranslator, Messages } from 'next-intl'

// Unified translation function type
// When scope is provided, it returns a translator for that specific scope
// When scope is not provided, it returns a translator for the entire Messages object
export type TFunction<scope extends keyof Messages | undefined = undefined> =
  scope extends keyof Messages
    ? ReturnType<typeof createTranslator<Messages[scope]>>
    : ReturnType<typeof createTranslator<Messages>>
```


Alternatively, if you want to add more support than top-level:

```ts
import type { createTranslator, Messages } from 'next-intl'

// Helper type to get deeply nested properties using dot notation
type GetNestedType<T, K extends string> = K extends keyof T
  ? T[K]
  : K extends `${infer First}.${infer Rest}`
    ? First extends keyof T
      ? GetNestedType<T[First], Rest>
      : never
    : never

// Helper type to generate paths only for object properties (namespaces)
type ObjectPaths<T, Prefix extends string = ''> = T extends object
  ? {
      [K in keyof T]: K extends string
        ? T[K] extends object
          ? T[K] extends string
            ? never // Exclude string properties
            : `${Prefix}${K}` | ObjectPaths<T[K], `${Prefix}${K}.`>
          : never
        : never
    }[keyof T]
  : never

// Type for all valid namespace paths in Messages (only object fields)
type NamespacePaths = ObjectPaths<Messages>

// Unified translation function type
// When path is provided, it returns a translator for that specific namespace
// When path is not provided, it returns a translator for the entire Messages object
// Only allows scoping to object properties (namespaces), not string properties
export type TFunction<path extends NamespacePaths | undefined = undefined> =
  path extends string
    ? ReturnType<typeof createTranslator<GetNestedType<Messages, path>>>
    : ReturnType<typeof createTranslator<Messages>>
```
