### ISSUE TITLE
When the url is written as a parameter, accessing /en?sku=123 causes the web page to crash

### ISSUE THREAD

**Issue by lynn1286** [amannn/next-intl#502]
### Description

When I access /en?sku=123 on the official case, it will always redirect and eventually crash the browser. Please note that there is no problem accessing /?sku=123.

https://github.com/amannn/next-intl/assets/40122311/5a62b8d3-c430-49a3-85ef-5d5b3417ba1e

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/github/amannn/next-intl/tree/main/examples/example-next-13

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

I hope to be able to access normally

**Comment by amannn** [comment]
This was fixed as part of https://github.com/amannn/next-intl/pull/149.
