### ISSUE TITLE
t.raw is not a function

### ISSUE THREAD

**Issue by mismosmi** [amannn/next-intl#52]
**Describe the bug**
Hi,
first off I'm really sorry if I waste your time on this, it is probably just my confusion.
I use `next-intl@1.3.3` and try to use `t.raw` to access an array of strings from my translation to render a list of product features but `t.raw` seems to be undefined. 

**To Reproduce**
I reproduced this using `use-intl` instead of `next-intl` as mocking next/router in codesandbox sucks.
https://codesandbox.io/s/hidden-pine-rsmnl?file=/src/App.js

1. See error

**Expected behavior**
I'd expect `t.raw` to be there and return the raw array so I can render my list from the input strings.

**Comment by mismosmi** [comment]
Sorry, this does not actually reproduce the issue I'm seeing,

**Comment by mismosmi** [comment]
This *does* actually reproduce the issue:
https://codesandbox.io/s/next-intl-template-forked-mxw1y?file=/src/pages/index.js
again, sorry!

**Comment by mismosmi** [comment]
It doesn't, something's wrong with my setup.

**Comment by mismosmi** [comment]
There is some kind of state where this issue appears however, I did see the error message in codesandbox but after a refresh it was gone. I ended up running `npm install` and then `npm run dev` again in my project and now the function's there as well.
Whatever.

**Comment by amannn** [comment]
The function was only introduced recently in v1.5.1 (https://github.com/amannn/next-intl/pull/51). The version you mentioned above didn't contain the feature.
