### ISSUE TITLE
Always resetting the cookie when a PWA is installed

### ISSUE THREAD

**Issue by maiconsanson** [amannn/next-intl#527]
### Description

Based on the [docs](https://next-intl-docs.vercel.app/docs/routing/middleware#locale-detection), the main strategy to detect the locale is:

1. A locale prefix is present in the pathname (e.g. /de/about)
2. **A cookie is present that contains a previously detected locale**
3. The [`accept-language header`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) is matched against the available locales
5. The `defaultLocale` is used

This happens very well when accessing a browser by URL.

But the strategy fails if I access my app, **which is a PWA**, from installed on mobile.
The `NEXT_LOCALE` cookie is resetting when the app opens based on the `accept-language header`, even if I have this cookie value already. 

**Debugging my phone**
If I access the root URL `/`, the previous `NEXT_LOCALE` is ignored. The locale is always `en` because I'm using it as the default language on my phone.

There is no problem with the app, only the `NEXT LOCALE` cookie is resetting. Other cookies are preserved and retrieved. In case I change my cellphone locale to Portuguese, the cookie is always `pt` no matter what.

<img width="892" alt="Screenshot 2023-09-22 at 20 15 13" src="https://github.com/amannn/next-intl/assets/1965455/bf560d9f-e472-49fb-8e7b-eb6596e2616c">

**Important**
- `"next": "14.1.0"`
- `"next-intl": "3.5.1"`
- `"@serwist/next': '8.4.3"`
- `'@serwist/sw': '8.4.3'`
- It was tested with 2 Android phones with Chrome with the same result.
- Before some `next-intl` update (I don't know which version) it did not happen. 

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/maiconsanson/next-intl-pwa-ignoring-cookie

### Reproduction description

Steps to reproduce:
1. Configure your mobile device to the English locale `en`.
2. **Install the PWA (mobile) on Chrome**.
3. Open the app and change the locale by clicking on the link "Mude para Português".
3. Close the PWA.
4. Open the app again and notice that the locale is `en`, not the previous `pt` selected.

Repeat these steps directly on the browser and you seed that works normally.

Here is the production link to see in action:
https://intl-unable-find-locale.vercel.app/

### Expected behaviour

The expected behavior is that the saved `NEXT_LOCALE` cookie value be used to define language when the PWA is installed.

**Comment by remcomulders** [comment]
I've had the same issue. I see you change locales using the `<Link>`. What worked for me was adding `prefetch={false}` on the `<Link>` component. The cookie gets changed while prefetching the different locales.

**Comment by maiconsanson** [comment]
> I've had the same issue. I see you change locales using the `<Link>`. What worked for me was adding `prefetch={false}` on the `<Link>` component. The cookie gets changed while prefetching the different locales.

@remcomulders Thanks for the reply! But even if setting prefetch to false, it doesn't work as expected **when the PWA is installed** on mobile. The cookie locale is always overridden.

https://github.com/maiconsanson/next-intl-pwa-ignoring-cookie/blob/main/src/app/components/Link/index.js

**Comment by amannn** [comment]
Also make sure to upgrade to the latest version, e.g. [3.4.5](https://github.com/amannn/next-intl/blob/main/CHANGELOG.md#345-2024-01-19) included a fix in regard to cookies.

**Comment by maiconsanson** [comment]
> Also make sure to upgrade to the latest version, e.g. [3.4.5](https://github.com/amannn/next-intl/blob/main/CHANGELOG.md#345-2024-01-19) included a fix in regard to cookies.

I've upgraded all the packages to the latest, and I'm still facing the issue that only happens with the `NEXT_LOCALE` cookie and no one else, so I'm assuming that the problem is with the package.

Do you have any clue on how I could isolate the problem? 

I can set a different cookie with the same value to prove that it remains intact and only one `NEXT_LOCALE` is resetting.  
What do you think?

**Comment by maiconsanson** [comment]
@amannn  I can confirm. It's because of the `SameSite='Strict'` restriction.

Any hit of the app that starts outside of it will not be able to load the cookie for the first time by using `strict`.

That's why any installed PWA won't get the cookie value loaded and always is reset.

The solution is to change from `SameSite='Strict'` to `SameSite='Lax'`.

At the following URL, you will see that I settled two more cookies: `FAKE_LOCALE_STRICT` and `FAKE_LOCALE_LAX`.
The only cookie that loads at the first hit is the settled with `SameSite='Lax'` (FAKE_LOCALE_LAX). 
The behavior is noticed by clicking on this link or installing the PWA:

https://intl-unable-find-locale.vercel.app/en

Mystery solved.

**Comment by amannn** [comment]
You're absolutely right @maiconsanson, thanks for investigating! #817 will address this, a fix should be out shortly.

**Comment by codelawani** [comment]
Thank you so much for putting this solution out here 🙏🏾.
