### ISSUE TITLE
`next-intl/link` does not export types

### ISSUE THREAD

**Issue by csi-lk** [amannn/next-intl#534]
### Description

Small one, for example

```tsx
import type { LinkProps } from "next/link";
```

works

```tsx
import type { LinkProps } from "next-intl/link";
```

does not

As per the docs:

> This component wraps [next/link(opens in a new tab)](https://nextjs.org/docs/app/api-reference/components/link) and automatically prefixes the href with the current locale as necessary.

Should it re-export the types?

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

n/a

### Reproduction description

```tsx
import type { LinkProps } from "next-intl/link";
```

`Module '"next-intl/link"' has no exported member 'LinkProps'`

### Expected behaviour

That I can use next-intl/link as a drop in replacement

**Comment by amannn** [comment]
You can extract the props like so:

```tsx
import {ComponentProps} from 'react';
import Link from 'next-intl/link';

type LinkProps = ComponentProps<typeof Link>
```

Exporting the types separately is currently not intended since this works well in my opinion via `ComponentProps`.

Hope this helps!

**Comment by daywison-flapper** [comment]
@amannn the href prop is missing when i use dynamic pathnames, so i can't use ComponentProps to access href prop. :(
It's very strange, in template sounds good, but when I use ComponentProps I can't see href  prop.
![image](https://github.com/amannn/next-intl/assets/150825771/ecbf0814-db51-4e19-9faa-820962dd5630)
![image](https://github.com/amannn/next-intl/assets/150825771/d192fe98-46cd-4a3c-a911-ed842db8d43f)

**Comment by amannn** [comment]
@daywison-flapper Please see "How can I compose the link with its href prop?" in [the docs for `Link`](https://next-intl-docs.vercel.app/docs/routing/navigation#link) after switching to "Localized pathnames".
