### ISSUE TITLE
Add support for number range formatting

### ISSUE THREAD

**Issue by vimtor** [amannn/next-intl#540]
### Is your feature request related to a problem? Please describe.

I want to format a range of numbers using the existing number range format API:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatRange

### Describe the solution you'd like

Either an option to the `.number` method in the `Formatter` object or a new `numberRange` method.

### Describe alternatives you've considered

I've considered using the API directly, but it is only supported in Node.js 19. The latest version available in Vercel is Node.js 18.

**Comment by vimtor** [comment]
Yes, @amannn! That would be a great addition :)

Regarding the polyfill, I assume the polyfill will be included with the library, right? If that is the case, it would work 100%

**Comment by vimtor** [comment]
Yes! I would love to contribute to this feature.

Would it be better to wait until the RSC integration is merged, right?

**Comment by amannn** [comment]
Superseded by https://github.com/amannn/next-intl/issues/774. We can still add this if there's need for this functionality.
