### ISSUE TITLE
Persisting searchParams on swithch locale

### ISSUE THREAD

**Issue by madaher-dev** [amannn/next-intl#550]
### Description

I am building a nexts app using the app router. I followed the same setup as in https://next-intl-docs.vercel.app/examples/app-router
Everything is working fine untill i wanted to persist the searchParamas (i use the paramas to persist some state) 
I modified the LocaleSwitcher in the example with the following code
```

"use client";
import { useLocale, useTranslations } from "next-intl";
import { usePathname, useRouter } from "next-intl/client";
import { useTransition } from "react";
import { useSearchParams } from "next/navigation";

export default function LocaleSwitcher() {
  const t = useTranslations("LocaleSwitcher");
  const [isPending, startTransition] = useTransition();
  const locale = useLocale();
  const router = useRouter();
  const pathname = usePathname();

  // Get the current query parameters
  const searchParams = useSearchParams();

  const allParams = searchParams.toString();

  function onSelectChange(event) {
    const nextLocale = event.target.value;

    let newPathname = pathname + "?" + allParams;

    startTransition(() => {
      router.replace(newPathname, { locale: nextLocale });
    });
  }

  const locales = ["en", "ar" /* other languages */];
  return (
    <label>
      <p className="sr-only">{t("label")}</p>
      <select
        className="inline-flex appearance-none bg-transparent py-3 pl-2 pr-6"
        defaultValue={locale}
        disabled={isPending}
        onChange={onSelectChange}
      >
        {locales.map((cur) => (
          <option key={cur} value={cur}>
            {t(cur)}
          </option>
        ))}
      </select>
      <span className="pointer-events-none absolute right-2 top-[8px]">⌄</span>
    </label>
  );
}

```
Now if i am on this page http://localhost:30002/?location=test&city=Beirut&currency=USD and switch to Arabic i am routed normally to http://localhost:30002/ar?location=test&city=Beirut&currency=USD
But if i want to switch back to english i am routed to http://localhost:30002/en?location=test&city=Beirut&currency=USD
and the page give 
This page isn’t working localhost redirected you too many times
I tried removing the page.jsx outside the locale router that has a redirect but i get same results
Also please note that http://localhost:30002/?location=test&city=Beirut&currency=USD works fine

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/advanced-digital-technologies/lokalee-new-web/tree/staging

### Reproduction description

Steps to reproduce:
1. Open reproduction npm run dev 
2. Add some searchParams to the url ex: location=test&foo=bar
3. Switch to arabic
4. Switch back to english

### Expected behaviour

http://localhost:30002/en?location=test&city=Beirut&currency=USD should redirect to http://localhost:30002/?location=test&city=Beirut&currency=USD

**Comment by amannn** [comment]
Thank you for the bug report! I've just fixed this in `next-intl@3.0.0-rc.3` (see [the 3.0 RC announcement](https://next-intl-docs.vercel.app/blog/next-intl-3-0))

**Comment by madaher-dev** [comment]
Thank you for an amazing library <3

**Comment by lmac-1** [comment]
Thanks @madaher-dev, this comment just helped me solve how to correctly handle query params in my `LocaleSwitcher` component. I'm just wondering if this should be added to some of the examples.

@amannn would you like me to make a PR to update the example [here](https://github.com/amannn/next-intl/blob/main/examples/example-app-router/src/components/LocaleSwitcherSelect.tsx) or somewhere else in the repo? More than happy to do so 🤗

**Comment by amannn** [comment]
Sounds like a good idea, thanks!

Would you mind updating the corresponding expandable section in [the `useRouter` docs](https://next-intl-docs.vercel.app/docs/routing/navigation#userouter) as well?

**Comment by Mimachh** [comment]
Hello, your job is really amazing.
However I'm facing an issue. I actually have nested route params "/store/[storeId]/products/[id]", and the locale switcher does not work as excepted. I tried this 
`      router.replace(
        // @ts-expect-error -- TypeScript will validate that only known `params`
        // are used in combination with a given `pathname`. Since the two will
        // always match for the current route, we can skip runtime checks.
        {pathname, params},
        {locale: nextLocale}
      );`

But it does not redirect me well. Have you got solution ?

**Comment by thiagop90** [comment]
With component Link:

`import { LanguagesIcon } from 'lucide-react'
import { useSearchParams } from 'next/navigation'
import { useLocale } from 'next-intl'

import { Link, usePathname } from '@/i18n/routing'

import { Button } from './ui/button'

export function LocaleSwitcher() {
  const locale = useLocale()
  const otherLocale = locale === 'en' ? 'pt' : 'en'
  const pathname = usePathname()

  const searchParams = useSearchParams()

  const allParams = searchParams.toString()
  const newPathname = `${pathname}?${allParams}`

  return (
    <Button asChild variant="ghost" size="icon" className="size-10">
      <Link href={newPathname} locale={otherLocale}>
        <LanguagesIcon className="size-4" />
      </Link>
    </Button>
  )
}
`

**Comment by thiagop90** [comment]
with component link:

`import { LanguagesIcon } from 'lucide-react'
import { useSearchParams } from 'next/navigation'
import { useLocale } from 'next-intl'

import { Link, usePathname } from '@/i18n/routing'

import { Button } from './ui/button'

export function LocaleSwitcher() {
  const locale = useLocale()
  const otherLocale = locale === 'en' ? 'pt' : 'en'
  const pathname = usePathname()

  const searchParams = useSearchParams()

  const allParams = searchParams.toString()
  const newPathname = `${pathname}?${allParams}`

  return (
    <Button asChild variant="ghost" size="icon" className="size-10">
      <Link href={newPathname} locale={otherLocale}>
        <LanguagesIcon className="size-4" />
      </Link>
    </Button>
  )
}`

**Comment by KinanGH98** [comment]
Hey! I ran into this issue too, where searchParams would disappear when switching locales with next-intl. Here’s how I fixed it:

```
const pathname = usePathname();
const router = useRouter();
const searchParams = useSearchParams();

function handleLocaleChange(locale) {
    // Preserve search params.
    const params = new URLSearchParams(searchParams);
    const newPath = params.toString() ? `${pathname}?${params.toString()}` : pathname;

    router.replace(newPath, { locale });
}
```
This way, your query params stay put when changing the language. Hope it helps!
