### ISSUE TITLE
Error: missing_message when use generateMetaData async function

### ISSUE THREAD

**Issue by xasanof17** [amannn/next-intl#555]
### Description

**I have used the source code to write layout.tsx and this error**
![image](https://github.com/amannn/next-intl/assets/93818267/dfe2b959-252e-4a2a-ab11-3372a7fb615c)
**there is my generateMetadata function =>**
![code](https://github.com/amannn/next-intl/assets/93818267/78098836-d73b-4d64-98bc-cf30807697f1)
**so there is getMessages function**
![code](https://github.com/amannn/next-intl/assets/93818267/3d418748-14d5-4dcc-b2ab-852a792105cf)
**but app is working. There is simple to use LocaleLayout [metadata](https://github.com/amannn/next-intl/blob/feat/next-13-rsc/examples/example-next-13/src/app/%5Blocale%5D/layout.tsx) me to written like this. but warning not stopping by show**

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/xasanof17/greencard/tree/main/app

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on [locale] directory
3. See error on layout.tsx
4. I think vercel's error for dynamic translation

### Expected behaviour

I want to fix this error and use dynamic translations with different objects

**Comment by amannn** [comment]
I unfortunately have errors running your reproduction:

```
❯ npm run dev

> greencard@0.0.1 dev
> i18nexus pull && next dev

error: required option '-k, --api-key <apiKey>' not specified
```

I tried removing `i18nexus pull` from the `dev` script, but your app fails to render:

<img width="1010" alt="Screenshot 2023-10-09 at 12 07 23" src="https://github.com/amannn/next-intl/assets/4038316/927b878d-b784-4dfa-bd5b-52bd782ca3f5">

**Comment by ParfenenkovEdit** [comment]
Got the same issue
