### ISSUE TITLE
NextIntlLink Does Not Trigger "hashchange" Event on Clicking a Link with Hash/ID

### ISSUE THREAD

**Issue by Israeltheminer** [amannn/next-intl#556]
### Description

When utilizing NextIntlLink from next-intl/link to navigate between sections of a page using hash links (e.g., #section1), the "hashchange" event is not being triggered as expected. This issue is critical for functionalities that rely on detecting hash changes in the URL, such as scroll-spy utilities, dynamic section highlighting, and single-page applications (SPAs) that need to manage state based on URL hash fragments.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-xn388f?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A30%2C9

### Reproduction description

Steps to reproduce:

1. Setup Next.js Project
2. Install Dependencies
3. Implement NextIntlLink:
4. Add "hashchange" Event Listener:
5. Run the Project

### Expected behaviour

A function attached to the "hashchange" event is only called when the hash is changed from the browser search bar, but not when a link with a hash is clicked.

**Comment by Israeltheminer** [comment]
Just ran a test with the Link component from `'next/link'` and it has the same behavior, might explain why this issue exists 🤔

**Comment by amannn** [comment]
Yep, that seems to be the case! `Link` from `next-intl` only wraps `next/link`, therefore we inherit all the functionality from that component. You might want to report this issue upstream.

**Comment by hypong** [comment]
I am facing the same issue. Anyone knows how to fix that ?

**Comment by sayhicoelho** [comment]
Facing the same issue here. Any updates??!

**Comment by wadehammes** [comment]
Same issue, was racking my brain for an hour on this.
