### ISSUE TITLE
Redirect with "asNeeded" in middleware always add locale to url

### ISSUE THREAD

**Issue by TommySorensen** [amannn/next-intl#557]
### Description

When using `redirect`returned from `createLocalizedPathnamesNavigation` with `localePrefix: 'as-needed',` in the middleware, then the locale is always added to the url which it should not. It should never be added on the default locale.
This seems like a bug.

```js
redirect({
    pathname: '/categories',
    params: { slug: ['hello'] }
})
```

I tried to create a codeSandbox, but it seems like the button calling the server actions never fires because of something with codesandbox.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-cw69w9?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Faction.ts%3A1%2C1

### Reproduction description

Click the button that calls the redirect function. 

### Expected behaviour

There should not be a locale in the url after redirect if you are on EN locale

**Comment by amannn** [comment]
There seems to be a bug in the reproduction where the scripts don't load on the client side:

<img width="770" alt="Screenshot 2023-10-10 at 13 55 23" src="https://github.com/amannn/next-intl/assets/4038316/b58e6b6f-dc9f-40d9-9c57-55c20e22bbed">

I also see that when I download the Sandbox. Can you try to fix that? I noticed Next.js is slightly outdated.

As a side note, in your redirect you're missing the `slug` in the `pathname`.
