### ISSUE TITLE
Does not re-render when namespace changes

### ISSUE THREAD

**Issue by mismosmi** [amannn/next-intl#57]
**Describe the bug**
Internationalized messages are not updated when the namespace provided in `useTranslations` changes.

**To Reproduce**

https://codesandbox.io/s/nice-shadow-ksq1z?file=/src/App.js

Klick 'NamespaceA' and 'NamespaceB' buttons.

**Expected behavior**
The title-message should be updated accordingly.

**Comment by mismosmi** [comment]
I can probably fix this and provide a PR if you're interested but though I'd report it first :)

**Comment by amannn** [comment]
Thanks for the report! If you're interested in setting up a PR, that would be really nice! 🙂 

I'd suspect the bug originates from the caching here: 

https://github.com/amannn/next-intl/blob/08af70d59d3600ce005a82abcb6971cbef241248/packages/use-intl/src/useTranslations.tsx#L158-L159

The cache key should probably include the `namespace` too.
