### ISSUE TITLE
Typescript errors using new localized path apis

### ISSUE THREAD

**Issue by jonschmidt** [amannn/next-intl#581]
### Description

I have implemented the new localized pathnames for server components in my nextjs app, which is 👏 . But the one thing that I am having trouble with is that I am getting typescript errors. 

From the error, it seems that the library is expecting a specific set of params, but is receiving generics. 

For the record, the code still works as expected, so the only problem is the error (which I am just ignoring for now).

Here is my abbreviated code

```
  const pathname = usePathname();
  const router = useRouter();
  const params = useParams();
  
  return (
    <a href="#"  onClick={() => router.replace({ pathname, params }, { locale: "de" })}>Switch to German </a>
  )
```

And the TS error

> Argument of type '{ pathname: "/" | "/contact" | "/cookies" | "/depression-test" | "/find-a-therapist" | "/find-a-therapist/[city_slug]" | "/find-a-therapist/[city_slug]/[profile_slug]" | "/find-help-with/[category_slug]" | ... 13 more ... | "/profile/[uri]"; params: Record<...> | null; }' is not assignable to parameter of type '"/" | "/contact" | "/cookies" | "/depression-test" | "/find-a-therapist" | "/for-companies" | "/for-therapists" | "/imprint" | "/our-story" | "/press" | "/privacy" | "/resources" | ... 26 more ... | ({ ...; } & { ...; })'.
  Types of property 'params' are incompatible.
    Type 'Record<string, string | string[]> | null' is not assignable to type '{ city_slug: ParamValue; } | { city_slug: ParamValue; profile_slug: ParamValue; } | { category_slug: ParamValue; } | { language: ParamValue; } | { ...; } | undefined'.
      Type 'null' is not assignable to type '{ city_slug: ParamValue; } | { city_slug: ParamValue; profile_slug: ParamValue; } | { category_slug: ParamValue; } | { language: ParamValue; } | { ...; } | undefined'.ts(2345)
      
      
      

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-zcymvq

### Reproduction description

Implement the new localized path navigation and make sure to have wildcard params.

Implement the recommended method for changing the locale and maintaining the current page

```
import {useParams} from 'next/navigation';
import {usePathname, useRouter} from '../navigation';
 
const pathname = usePathname();
const router = useRouter();
const params = useParams();
 
router.replace({pathname, params}, {locale: 'de'});
```

Notice the typescript warning for params.

### Expected behaviour

I would think we would not receive typescript warnings for a recommended implementation. but if there is no easy way aound it, then perhaps its worth mentioning it in the docs?

**Comment by aalin** [comment]
I couldn't find the code that gave the error in the codesandbox link you pasted.
However, it seems like params can be null. You probably just need to make sure `params` is not null and that it has all the required parameters for that path (or just cast it to any by doing `useParams() as any`). I think the error message  is correct for most situations.

**Comment by jonschmidt** [comment]
https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-7n8zmv?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Fpage.tsx
![image](https://github.com/amannn/next-intl/assets/513206/c5503fae-f095-45ba-a068-cfb20a3d7d96)

This is quite bizarre, but if I open that link in an incognito window, I do not get the error 🤔

**Comment by aalin** [comment]
You can solve this by doing `const params = useParams() as any;`, or you can make sure that `params` contains the `friend` property when `pathname` is `"/hello/[friend]"`

**Comment by amannn** [comment]
Thank you for helping out here @aalin! Casting to `any` should indeed be fine in this case. I've adjusted the docs accordingly in https://github.com/amannn/next-intl/commit/de285f6f78de15c51a62e2cdd29e0debcc2d415b.
