### ISSUE TITLE
Serve Default Locale Content at Root Path without Redirect

### ISSUE THREAD

**Issue by asterixcapri** [amannn/next-intl#594]
### Is your feature request related to a problem? Please describe.

Currently, when setting up internationalization with next-intl, users visiting the root path / are redirected to the default locale's specific path, such as /en for English. This results in an additional redirect which may not be necessary or desired, particularly for SEO purposes or user experience.

### Describe the solution you'd like

I would like next-intl to have the ability to serve the default locale content directly at the root path (/) without any redirect to a locale-specific path. This would mean that when a user visits the root path, they would see the content for the default locale set in the configuration but the URL would remain as /.

### Describe alternatives you've considered

An alternative could be to handle this behavior manually with custom server-side logic, but this seems counterintuitive and might introduce unnecessary complexity. Another option could be to have a special flag or setting in the next-intl configuration to enable this kind of behavior.

**Comment by ameistad** [comment]
I'm using version 3.0.0-rc.7 and had the same problem. I took a look at the source code for the middleware and it works as expected if I set  `localePrefix: 'as-needed'`in the config.

**Comment by amannn** [comment]
Yep, `localePrefix: 'as-necessary’` is the solution here and also mentioned in the middleware docs.

Thanks for sharing your solution @ameistad!

**Comment by asterixcapri** [comment]
Thank you for your attention to my previous post. I realize now that I may not have communicated my requirements clearly. Here is the specific directory structure I am looking to implement:

**www.site.com/** - Root path serving the home page content in the default locale (English in this case) without redirecting to /en.
**www.site.com/it** - Home page in Italian.
**www.site.com/en/getting-here** - Content in English for "Getting Here".
**www.site.com/it/come-arrivare** - The same content in Italian.

The goal is to have the root path serve the default locale's content directly without any redirection, while other paths retain the locale in their structure for clarity and SEO benefits.

Could you please provide guidance on configuring next-intl to accommodate this structure?

Thank you
Alex

**Comment by amannn** [comment]
The `next-intl` middleware doesn't support this out-of-the-box, but you could probably add a rewrite on top if you generally want locale prefixes but want to serve the default locale at `/` too.

**Comment by joelschneider** [comment]
+1

I think this would be extremely useful (if not absolutely necessary) if you want to build a localized marketing website with next-intl. Having your main content on a sub-folder like "/en" is prohibitively bad for SEO (and will look weird for website visitors).

I was trying to set a localized website up similarly to Notion, which also has the EN locale at the root per default, but all other languages in a subfolder (e.g. https://www.notion.so/product for EN vs https://www.notion.so/de-de/product for DE).

Seems like a rewrite is the only possible way to make this happen 🥲

**Comment by amannn** [comment]
I think Notion uses a pattern akin to the [`localePrefix: 'as-needed'`](https://next-intl-docs.vercel.app/docs/routing/middleware#locale-prefix-as-needed) (e.g. `/product`, not `/en/product`). The original request above was about something slightly different.

**Comment by joelschneider** [comment]
Mea culpa, you are completely right! 🙏 I misread the previous comment. Thanks for replying so quickly :)

**Comment by redonkulus** [comment]
@amannn 

> but you could probably add a rewrite on top if you generally want locale prefixes but want to serve the default locale at / too

Do you have an example of how/where to do this?
