### ISSUE TITLE
500 Error with Next-intl Middleware on Vercel Deployment: EDGE_FUNCTION_INVOCATION_FAILED 

### ISSUE THREAD

**Issue by Zakisb** [amannn/next-intl#603]
### Description

Encountering a server-side error when deploying a Next.js 14 application with next-intl middleware to Vercel. The deployment fails with a 500 status code, specifically citing EDGE_FUNCTION_INVOCATION_FAILED as the reason. Additionally, a ReferenceError: __dirname is not defined occurs within the ua-parser-js module, as well as in the user-agent and middleware files of next-intl. This error is not present during local development and only manifests upon deployment to Vercel.

Note that previously i worked with next-intl and deployed without a problem. i don't know if it's something to do with the latest next 14 version or next-intl

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/Zakisb/aimplifyy

### Reproduction description

Deploy to vercel

### Expected behaviour

I expected the web app to be deployed.

**Comment by amannn** [comment]
Can you upgrade to [the release candidate](https://next-intl-docs.vercel.app/blog/next-intl-3-0) and see if the issue persists? The examples in this repo have been updated to Next.js 14 and can be deployed to Vercel flawlessly.

**Comment by Zakisb** [comment]
Now during the build i'm getting this error
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin' is not defined by "exports" in /Users/zakisb/Desktop/aimplifyy/node_modules/next-intl/package.json

**Comment by Zakisb** [comment]
Updated. now i'm getting this as error
[
![Uploading Screenshot 2023-11-07 at 7.28.17 PM.png…]()
](url)

**Comment by Zakisb** [comment]
Still the same problem 
ReferenceError: __dirname is not defined
    at (node_modules/next/dist/compiled/ua-parser-js/ua-parser.js:1:17315)
    at (node_modules/next/dist/compiled/ua-parser-js/ua-parser.js:1:17444)
    at (node_modules/next/dist/server/web/spec-extension/user-agent.js:27:59)
    at (node_modules/next/server.js:8:0)
    at (node_modules/next-intl/dist/production/middleware/middleware.js:1:68)
    at (node_modules/next-intl/dist/production/middleware.js:1:68)
    it's insane.... is there a way to provide a clear middleware in the docs please?

**Comment by amannn** [comment]
> Updated. now i'm getting this as error

The latest release candidate is `next-intl@3.0.0-rc.9`, as mentioned at the bottom of https://next-intl-docs.vercel.app/blog/next-intl-3-0. `getTranslations` was introduced only recently.

**Comment by Zakisb** [comment]
![Screenshot 2023-11-07 at 8 33 14 PM](https://github.com/amannn/next-intl/assets/28612240/75c25069-b1fa-4678-95fc-765378cbee0a)
In the build logs, i'm getting this warning. i think that's what's causing the error. sorry if that's a dumb question but is it because i'm not using typescript?

**Comment by amannn** [comment]
I unfortunately don't have any background on that warning, but it shouldn't be related to the usage of JavaScript.

I'll close this issue since there doesn't seem to be an issue with `next-intl`, I hope you understand.
