### ISSUE TITLE
Plural translations (with count paramater) produce "does not match server-rendered HTML" ("ua" locale)

### ISSUE THREAD

**Issue by nikitastryuk** [amannn/next-intl#605]
### Description

Plural translations (with count paramater) which uses "Intl.PluralRules" API determined incorrectly on server ("ua" locale).

Issue
`{
  "test": "{count, plural, one {# user} other {# users}}"
}`

`<p>{t('test', { count: 21 })}</p>`

#other is returned from server-rendered html and then transformed to #one on client side.

<img width="1216" alt="image" src="https://github.com/i18next/next-i18next/assets/32720808/3dd344f4-0353-486f-849e-a53cbb49ef66">

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

[Codesandbox](https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-q433vz?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A2%2C1)

## To Reproduce

1. Go to [Codesandbox](https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-q433vz?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A2%2C1)
2. Insert `/ua` to url
3. Press Enter
4. See Hydration error
5. Press enter more times (with url focused) to see blinking translations

### Expected behaviour

Plural translations should behave the same on both server and client.

**Comment by nikitastryuk** [comment]
UPD after some debugging and investigation:

It started working with `uk` instead of `ua`. Looks like `Intl.PluralRules` works with codes from this [list](https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html) only. Not really obvious. 

But still not sure why server side initial result is different.

**Comment by amannn** [comment]
Node.js and browsers seem to have subtle differences when it comes to the implementation of `Intl`. We saw a similar issue here: https://github.com/amannn/next-intl/issues/528

**Comment by amannn** [comment]
This seems to be out of control for `next-intl` and is related to the underlying runtime. You might have to provide polyfills for a consistent environment.
