### ISSUE TITLE
Symbols/foreign letters not working with localized pathnames

### ISSUE THREAD

**Issue by Entropy-10** [amannn/next-intl#607]
### Description

When using localized pathnames, if you currently try to use symbols or foreign letters it causes the url to generate incorrectly and cause a 404 not found error.

`navigation.ts`
```ts
export const pathnames = {
    '/': '/',
    '/test': {
        en: '/test',
        ja: '/テスト'
    }
} satisfies Pathnames<typeof locales>
```

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

[![Edit next-intl-bug-template (app) (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-xskh6r?file=%2Fsrc%2Fnavigation.ts&embed=1)

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on `Go to Japanese Test Page`
3. See incorrect url and 404 not found error

### Expected behaviour

Expected: `http://localhost:3000/ja/テスト` 
Actual Result: `http://localhost:3000/ja/%E3%83%86%E3%82%B9%E3%83%88`.

**Comment by amannn** [comment]
Thanks for the report!

Also the rewrite in the middleware doesn't seem to handle this URL correctly: https://xskh6r-3000.csb.app/ja/テスト

**Comment by AdamZaczek** [comment]
Localized pathnames are super important for any platform relying on content. We've been trying to get around this, with no success. Looking forward to the fix!

**Comment by amannn** [comment]
Contributions are welcome here in case someone wants to look into it.

I think this can be tackled as following:
1. Add a failing test in [the middleware test suite](https://github.com/amannn/next-intl/blob/main/packages/next-intl/test/middleware/middleware.test.tsx)
2. Adapt [the middleware](https://github.com/amannn/next-intl/blob/main/packages/next-intl/src/middleware/middleware.tsx) accordingly
3. Add a failing test in [the localized navigation test suite](https://github.com/amannn/next-intl/blob/main/packages/next-intl/test/navigation/createLocalizedPathnamesNavigation.test.tsx)
4. Adapt `createLocalizedPathnamesNavigation` accordingly ([`react-client` implementation](https://github.com/amannn/next-intl/blob/main/packages/next-intl/src/navigation/react-client/createLocalizedPathnamesNavigation.tsx), [`react-server` implementation](https://github.com/amannn/next-intl/blob/main/packages/next-intl/src/navigation/react-server/createLocalizedPathnamesNavigation.tsx))

See also [the contributors guidelines](https://github.com/amannn/next-intl/blob/main/CONTRIBUTORS.md#development).

**Comment by amannn** [comment]
I had a moment to look into this, would someone like to try out the prerelease from https://github.com/amannn/next-intl/pull/959?



Many thanks to @reilnuud for sharing a workaround here! Note that as part of upgrading, this workaround needs to be removed as defined pathnames are expected to be decoded.

**Comment by sahandsn** [comment]
any update on the issue?
