### ISSUE TITLE
Opt out from rewrite

### ISSUE THREAD

**Issue by mochetts** [amannn/next-intl#618]
### Is your feature request related to a problem? Please describe.

I have another middleware that performs a rewrite to `/app` when the request host is `app.myhost.com`. This rewrite is colliding with the rewrite that `next-intl`  performs. 

Given that NextJS only allows 1 middleware rewrite in the request lifecycle. Isn't it too much for the library to consume that single intent?

Is there a way to solve this without using a rewrite within next-intl?

Is there a way to solve this without needing to change anything in next-intl?

### Describe the solution you'd like

Add a way to opt out from the rewrite and do a redirect instead

### Describe alternatives you've considered

Been trying to solve this issue by parsing and massaging the response that the next-intl middleware returns with no success.

**Comment by amannn** [comment]
There was a similar request recently here, maybe this helps: https://github.com/amannn/next-intl/discussions/573. Generally, the middleware is composable, allowing e.g. rewrites on top before processing a request.

Rewrites seem to be a common request, I've added [an example for rewrites to the middleware docs of the release candidate](https://next-intl-docs-git-feat-next-13-rsc-next-intl.vercel.app/docs/routing/middleware#example-additional-rewrites), which are expected to be published soon. Hope this helps!
