### ISSUE TITLE
`createLocalizedPathnamesNavigation` requires `pathnames` for Shared pathnames strategy

### ISSUE THREAD

**Issue by rawand-faraidun** [amannn/next-intl#634]
### Description

As explained in the [Strategy 1: Shared pathnames](https://next-intl-docs.vercel.app/docs/routing/navigation#shared-pathnames), `createSharedPathnamesNavigation` from `'next-intl/navigation'` does not require `pathnames` in the parameter object and the example is like this:
```
// navigation.ts
import {createSharedPathnamesNavigation} from 'next-intl/navigation';
 
export const locales = ['en', 'de'] as const;
 
export const {Link, redirect, usePathname, useRouter} =
  createSharedPathnamesNavigation({locales});
```

but while using it I get this error:
```
Argument of type '{ locales: string[]; }' is not assignable to parameter of type '{ locales: string[]; pathnames: Pathnames<string[]>; }'.
  Property 'pathnames' is missing in type '{ locales: string[]; }' but required in type '{ locales: string[]; pathnames: Pathnames<string[]>; }'.ts(2345)
createLocalizedPathnamesNavigation.d.ts(8, 5): 'pathnames' is declared here.
```

I believe the `pathnames` should be optional

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-39xvcp?file=%2Fsrc%2Fnavigation.ts%3A3%2C31

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Open `src/navigation.ts`
3. See error: in line 5
 * I have also added a comment that tells the error

### Expected behaviour

I believe the `createLocalizedPathnamesNavigation` parameter type should be like this:
```
{
    locales: string[];
    pathnames?: Pathnames<string[]>;
}
```

**Comment by amannn** [comment]
`pathnames` only need to be provided for localized pathnames, not for shared pathnames. I think you’re looking for `createSharedPathnamesNavigation`.

**Comment by rawand-faraidun** [comment]
I have followed this [Strategy 1: Shared pathnames](https://next-intl-docs.vercel.app/docs/routing/navigation#shared-pathnames) and yes I was looking for that but I must have imported a wrong one, but there is `createSharedPathnamesNavigation` exported from `next-intl/navigation`

**Comment by amannn** [comment]
Yep, both `createSharedPathnamesNavigation` as well as `createLocalizedPathnamesNavigation` are exported from `next-intl/navigation`. As far as I understand, you're looking for the former one.

I'll close this issue then.
