### ISSUE TITLE
Bug:  `useMessages` is not callable within an async component

### ISSUE THREAD

**Issue by LiuCaptain** [amannn/next-intl#635]
### Description

I saw an introduction to 'Server&Client Components' in the document：
![image](https://github.com/amannn/next-intl/assets/43247357/058de262-9cf5-4888-90ec-fb4affda3a4a)

But when I was using it, I reported an error：
![image](https://github.com/amannn/next-intl/assets/43247357/c0aba61d-47bf-4781-b37d-efb4c300e0da)

This is my code：
![image](https://github.com/amannn/next-intl/assets/43247357/5c13198a-e199-4ce8-bbc1-27a50e7b1f54)

So can I only import messages through import()?

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

not have

### Reproduction description

as mentioned above，thank you !

### Expected behaviour

Please tell me what to do, thank you very much!

**Comment by di-sukharev** [comment]
what if i have an async component?

**Comment by erwanriou** [comment]
use import { getMessages } from "next-intl/server"

`const messages = await getMessages();`
