### ISSUE TITLE
Localized pathnames don't work with Dynamic params

### ISSUE THREAD

**Issue by Benlasc** [amannn/next-intl#643]
### Description

Hello, I used the github code: next-intl/examples/example-app-router to show you my problem (see the codesandbox link below).

In the src/config.ts file I defined a url with a dynamic parameter id : 

/customer/[id]': {
  en: '/customer/[id]',
  de: '/customer-de/[id]'.

When the user is on the /en/customer/100 url and chooses the 'de' locale, I'd like the url to become /de/customer-de/100.

The problem is that I have an error on the line "router.replace(pathname, {locale: nextLocale})" in the "LocaleSwitcherSelect.tsx" file:

Error: Insufficient params provided for localized pathname.
Template: /customer-de/[id]
Params: undefined

Is this a bug that needs to be fixed or an error on my part?

Thank you.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-yy3xtl?file=%2Fsrc%2Fconfig.ts%3A12%2C24

### Reproduction description

Steps to reproduce:

1. Go to the url /en/customer/100
2. Change the locale from English to German
3. See the error message:

Error: Insufficient params provided for localized pathname.
Template: /customer-de/[id]
Params: undefined

### Expected behaviour

When the user is on the /en/customer/100 url and chooses the 'de' locale, I'd like the url to become /de/customer-de/100.

**Comment by amannn** [comment]
Hey, you probably want to check "How can I change the locale for the current page?" in [the `useRouter` docs](https://next-intl-docs.vercel.app/docs/routing/navigation#userouter).

Hope this helps!

**Comment by Benlasc** [comment]
OK, thank you, I've finally replaced it:

    startTransition(() => {
      router.replace(pathname, {locale: nextLocale});
    });

with this:

    startTransition(() => {
      router.replace({pathname: '/customer/[id]', params: {id: '100'}}, {location: nextLocale});
    });
    
Thanks for the help

**Comment by amannn** [comment]
Looks good! 🙌

**Comment by axelpezzo** [comment]
Hello guys, I've the same issue as you.

I've implemented a LanguageSwitcher on the Header which change the website language.

When I'm on the path /en/shop/category-x/product-y (solved by a DynamicPath pattern) and I switch from english to another language I got the error: "Insufficient params provided for localized pathname" and nothing happens on the page.

If I console log the pathname returned by usePathname hook I got the folder pattern /shop/[...slug] as excpected.

The solution proposed by @Benlasc is hardcoded for that product how can I solve this in order to handle correctly all the dynamic routes inside the Website?

**Comment by evilive3000** [comment]
```typescript
"use client";

import { useParams } from "next/navigation";
import { usePathname, useRouter } from "@/navigation";

export default function LanguageSwitcher(props: { locales: string[] }) {
  const router = useRouter();
  const pathname = usePathname();
  const params = useParams();

  const changeLanguage = (lang: string) => {
    /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
    router.push({ pathname, params: params as any }, { locale: lang });
  };

  return (
    <div className="flex">
      {props.locales.map((lang) => (
        <button key={lang} onClick={() => changeLanguage(lang)}>
          {lang.toUpperCase()}
        </button>
      ))}
    </div>
  );
}
```

I encountered a similar problem. It turned out that you can get the current parameters for pathname using the `useParams` hook. After that, everything is simple. I hope this solution saves someone some time 😉

**Comment by Mimachh** [comment]
> ```ts
>     /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
>     router.push({ pathname, params: params as any }, { locale: lang });
> ```

Thanks, you're a boss.

**Comment by Exp1ry** [comment]
How can we achieve this using a Link component?

**Comment by AlanJereb** [comment]
> ```ts
> "use client";
> 
> import { useParams } from "next/navigation";
> import { usePathname, useRouter } from "@/navigation";
> 
> export default function LanguageSwitcher(props: { locales: string[] }) {
>   const router = useRouter();
>   const pathname = usePathname();
>   const params = useParams();
> 
>   const changeLanguage = (lang: string) => {
>     /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
>     router.push({ pathname, params: params as any }, { locale: lang });
>   };
> 
>   return (
>     <div>
>       {props.locales.map((lang) => (
>         <button key={lang} onClick={() => changeLanguage(lang)}>
>           {lang.toUpperCase()}
>         </button>
>       ))}
>     </div>
>   );
> }
> ```
> 
> I encountered a similar problem. It turned out that you can get the current parameters for pathname using the `useParams` hook. After that, everything is simple. I hope this solution saves someone some time 😉

For anyone encountering an error `Error: Insufficient params provided for localized pathname.` even when doing the above suggestion, make sure, that if you are defining `[...rest]` inside your pathnames, **put [...rest] onto the end of definition**.

🟥 Wrong:
```
export const pathnames = {
  // If all locales use the same pathname, a
  // single external path can be provided.
  '/': '/',
  '/blog': '/blog',
  '[...rest]': '[...rest]',
  
  // If locales use different paths, you can
  // specify each external path per locale.
  '/blog/[slug]': {
    en: '/blog/[slug]',
    it: '/blog/[slug]',
    es: '/blog/[slug]',
    fr: '/blog/[slug]',
  },
} satisfies Pathnames<typeof locales>;
```

🟩 Correct:
```
export const pathnames = {
  // If all locales use the same pathname, a
  // single external path can be provided.
  '/': '/',
  '/blog': '/blog',
  
  // If locales use different paths, you can
  // specify each external path per locale.
  '/blog/[slug]': {
    en: '/blog/[slug]',
    it: '/blog/[slug]',
    es: '/blog/[slug]',
    fr: '/blog/[slug]',
  },

  '[...rest]': '[...rest]',
} satisfies Pathnames<typeof locales>;
```

**Comment by patateskafa** [comment]
For those who came across the same issue using next-intl Link component, I think the path param mechanism is sort of bugged (using next-intl `3.12.2`), or I'm missing an obvious point, at least for localized pathnames `useParams()` always grab `id` as the param passed to a `Link` wrapper and nothing else, i.e.:

Compiles but doesn't work:
```
<Link
      href={{
        pathname: "/posts/[postId]",
        params: { postId: post.id },
      }}>

-----------------------

export const pathnames = {
  "/posts": {
    en: "/posts",
    tr: "/yazilar",
  },
  "/posts/[postId]": {
    en: "/posts/[postId]",
    tr: "/yazilar/[postId]",
  },
} satisfies Pathnames<typeof locales>;
```

Works:
```
<Link
      href={{
        pathname: "/posts/[id]",
        params: { id: post.id },
      }}>

-----------------------

export const pathnames = {
  "/posts": {
    en: "/posts",
    tr: "/yazilar",
  },
  "/posts/[id]": {
    en: "/posts/[id]",
    tr: "/yazilar/[id]",
  },
} satisfies Pathnames<typeof locales>;
```

**Comment by meJohnnyRobert** [comment]
i am having a similar issue and I'd appreciate if I can get a bit of help solving it:

<img width="952" alt="Screenshot at May 26 00-31-22" src="https://github.com/amannn/next-intl/assets/115624777/53cf6156-a4b6-4c83-a24b-35439047a465">

Here is my code:

```js
// src/navigation.ts

import { createLocalizedPathnamesNavigation, Pathnames } from "next-intl/navigation";

export const locales = ["en", "ro"] as const;
export type Locale = typeof locales;
export const localePrefix = "always";

export type LocalizedPathnames = Pathnames<typeof locales> & {
  '/user/[id]': { en: string; ro: string };
};

// Define the pathnames object with the new type
export const pathnames: LocalizedPathnames = {
  "/": "/",
  "/login": { en: "/login", ro: "/autentificare" },
  "/signup": { en: "/signup", ro: "/inregisrare" },
  "/jobs": { en: "/jobs", ro: "/joburi" },
  "/account-recovery": "/account-recovery",
  "/password-reset": "/password-reset",
  "/urgent-employment-list": "/urgent-employment-list",
  "/my-applications": "/my-applications",
  "/scheduled-interviews": "/scheduled-interviews",
  "/messages": "/messages",
  "/employment-offers": "/employment-offers",
  "/jobs-saved-for-later": "/jobs-saved-for-later",
  "/my-profile": "/my-profile",
  "/subscription": "/subscription",
  "/documentation": "/documentation",
  "/bug-report": "/bug-report",
  "/contact-support": "/contact-support",
  "/download-our-app": "/download-our-app",
  "/settings": "/settings",
  "/user/[id]": { en: "/user/[id]", ro: "/utilizator/[id]" },
};

export const {
  Link,
  redirect,
  usePathname,
  useRouter,
  getPathname,
} = createLocalizedPathnamesNavigation({ locales, pathnames });
```

```js
// components/sidebar/job-seeker-sidebar.tsx

'use client';

import React from 'react';
import { useRouter, usePathname, pathnames, getPathname } from '@/src/navigation';

interface JobSeekerSidebarProps { }

const JobSeekerSidebar: React.FC<JobSeekerSidebarProps> = () => {
  const router = useRouter();
  const pathname = usePathname();
  const t = useTranslations("sidebar");
  const { user } = useUserSessionStore();
  const locale = useLocale() as 'en' | 'ro'; // Casting locale to the expected type

  const handleButtonClick = (path: keyof typeof pathnames, params?: { [key: string]: string }) => {
    // Check if the path includes the [id] placeholder
    const hasIdPlaceholder = path.includes('[id]');
  
    // Get the localized path based on the current locale
    let localizedPath = getPathname({
      locale,
      href: path,
      ...(hasIdPlaceholder && params),
    });
  
    // Navigate to the constructed path
    router.push(localizedPath);
  };

  return (
          <IconButton
            icon={<FaRegUser />}
            label={t('myProfile')}
            onClick={() =>
              user?.id
                ? handleButtonClick('/user/[id]', { id: user.id })
                : handleButtonClick('/user/[id]')
            }
            isActive={pathname === `/user/${user?.id}`}
          />
  );
};

export default JobSeekerSidebar;
```

**Comment by zithir** [comment]
For us, when using `router.push` or `router.replace`, the problem was comming from the mismatch in param name in route in and pathnames localization.

We had a path with **orderId**:

```
app/order-history/[orderId]/page.tsx
```

While in the pathnames the entry  used just **id**

```
const pathnames = {
  "order-history/[id]": {
    en: `${pathnames.purchaseHistory}/[id]`,
    fi: "/ostohistoria/[id]",
    sv: "/order-history-sv/[id]",
  },
...
}
```

Which results in 


```
const pathname = usePathname(); // returns "order-history/[id]"
const params = useParams(); // returns { locale: "en": orderId: "foo"}
...
router.push({ pathname, prams }, {locale: "fi")) // throws error

```

Making the two param names aligned either way (using `id` or `orderId`) fixed that.
