### ISSUE TITLE
custom folder structure

### ISSUE THREAD

**Issue by vaishnavi-jadhav-amla** [amannn/next-intl#650]
### Description

Need to use localization for a custom path. I am working on a multi-tenant application using pathname as domainName/customfolder/{locale}/product/id. Currently, if we use nextintl middleware this does not work and leads to a page not found issue as middleware tries to bind the locale just after the domain name.

I have attached the screenshot for reference

![image](https://github.com/amannn/next-intl/assets/84833114/a330462c-54c1-430c-8ca2-b7237c3495fb)

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

NA

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

it should redirect along with custom folders

**Comment by upardhi** [comment]
@amannn : Experiencing a similar challenge here. Could you kindly provide a solution or suggest any viable alternatives?

Our focus is on developing a multi-tenant application.

**Comment by amannn** [comment]
I agree there's a piece missing here currently. I've opened https://github.com/amannn/next-intl/issues/653 to collect this issue together with similar ones, also to share solutions that can be used today.

**Comment by amannn** [comment]
I'll close this now in favor of #653. This issue is mentioned there and will be taken care of.
