### ISSUE TITLE
Allow Navigation with Link without client-side JavaScript

### ISSUE THREAD

**Issue by Emrin** [amannn/next-intl#664]
### Is your feature request related to a problem? Please describe.

Next's default Link component does not require client-side JavaScript to work.
When using the next-intl Link, routing works for the default locale but not for the others:
![image](https://github.com/amannn/next-intl/assets/23482165/d8b1afcb-f2ef-4975-a583-ab437e41fe6b)
For example, while using `localePrefix: "never"` along with localized pathnames and after disabling JS on the client, theres an infinite redirection loop.

### Describe the solution you'd like

Next-Intl's Link to not cause infinite redirection without Client-Side JS.

### Describe alternatives you've considered

Not using `localePrefix: "never"` is an alternative.

**Comment by amannn** [comment]
This is closely related: https://github.com/amannn/next-intl/issues/444

Are you sure that you're seeing an infinite redirection loop? The link should include the locale prefix, but if you click it, it should redirect from the middleware to the non-prefixed version (and stay there).

If you see an infinite redirect, can you provide a reproduction?
