### ISSUE TITLE
Link component causing runtime error since upgrading to version 3.1+

### ISSUE THREAD

**Issue by brandanking-decently** [amannn/next-intl#665]
### Description

Since upgrading to version 3.1.0+ the Link component generated by the createSharedPathnamesNavigation is providing the following error when the Link is inside a radix ui component that uses slots.

`Error: Objects are not valid as a React child (found: object with keys {$$typeof, _payload, _init}). If you meant to render a collection of children, use an array instead.`

This error didn't exist in the release candidates of the next-intl package.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-tl8gq7?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A15%2C53

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on open button
3. See error: Error: Objects are not valid as a React child (found: object with keys {$$typeof, _payload, _init}). If you meant to render a collection of children, use an array instead.

### Expected behaviour

Revert next-intl to next-intl@3.0.0-rc.6 to see component working as expected

**Comment by amannn** [comment]
This is an interesting case. In your case, `Link` renders as a Server Component—however, you're using `<DropdownMenuItem asChild>`, which expects a Client Component.

The fix depends on your app, but in the simplified demo, `page.tsx` can be marked with `'use client';` to fix this. It would probably also work to only wrap the respective `DropdownMenuItem` along with `Link` in a Client Component.

Hope this helps!

**Comment by EfstathiadisD** [comment]
Sorry for this. I don't understand why it doesn't work on mine. I can give you access to a repo if you want. but seriously I did it step by step and it doesn't work.. From what I can see the `getRequestConfig` is never being called.

I am not sure what is going on. It prob something stupid I am doing but I cannot see it..

**Comment by brandanking-decently** [comment]
> This is an interesting case. In your case, `Link` renders as a Server Component—however, you're using `<DropdownMenuItem asChild>`, which expects a Client Component.
> 
> The fix depends on your app, but in the simplified demo, `page.tsx` can be marked with `'use client';` to fix this. It would probably also work to only wrap the respective `DropdownMenuItem` along with `Link` in a Client Component.
> 
> Hope this helps!

Hi, the asChild has no restrictions on whether the component is a client component or not, as if I just used the regular next/link component it works fine. Also it worked fine like this the the release candidates previously, it also works if I wrapped the Link component from next-intl in simple div tag.

**Comment by sunxyw** [comment]
any updates?

**Comment by stefvw93** [comment]
The same error occurs when directly using React `Children` api to process the `Link`, for example `Children.count`, `Children.array` all result in the invalid React child error.

**Comment by amannn** [comment]
@stefvw93 I think there was a necessary change along the release candidate process where `Link` used to always be a Client Component, but now it's either a Server or Client Component, depending on where you import it from.

The issue is caused by the Radix `asChild` API, which is based on `cloneElement`—an API that only works for Client Components. A fix has been mentioned here: https://github.com/amannn/next-intl/issues/665#issuecomment-1826271563. I don't think this is something that `next-intl` can internally handle, but a restriction resulting from the React Server Components architecture.

Hope this helps!
