### ISSUE TITLE
Use 308 redirect for defaultLocale when localePrefix: 'as-necessary'.

### ISSUE THREAD

**Issue by wrightjeff** [amannn/next-intl#666]
### Is your feature request related to a problem? Please describe.

I am currently migrating an existing multi-language site to next-intl.  The existing site has been indexed with some urls prefixed with /en (the defaultLocale) and others not using the /en prefix.  For the new site, we have oped to use localePrefix: 'as-necessary'.  We would like a 308 redirect for pages that had been indexed previously with the /en prefix for SEO.

Additionally, we are using the /language prefix when specifying alternate languages in the slug, as they may otherwise be redirected to another version depending on the clients language preference.
ie:  
`<link rel="alternate" href="https://www.site.com/en/slug" hreflang="en">
`

For these reasons, I think a 308 redirect would be more appropriate than a 307 redirect for the defaultLocale when localePrefix: 'as-necessary'

Previous discussion here:  https://github.com/amannn/next-intl/issues/591

### Describe the solution you'd like

I would like for the redirect to be a 308 vs a 307 when redirecting to the defaultLocale, when localePrefix is set to 'as-necessary'

### Describe alternatives you've considered

Patching next-intl to reflect my preference.

**Comment by amannn** [comment]
You can certainly add additional 308 redirects by [composing the middleware](https://next-intl-docs.vercel.app/docs/routing/middleware#composing-other-middlewares) either by:
1. Redirecting certain requests before they reach the `next-intl` middleware …
2. … or by overwriting the response status code in certain cases if the `next-intl` middleware returns a redirect

Alternatively, you can set up redirects in `next.config.js`.

`next-intl` will not add permanent redirects for the `as-necessary` strategy for now, to allow users to change routing strategies without running into cache issues.

Hope this helps!
