### ISSUE TITLE
Add `scroll` property in options of router.push() method

### ISSUE THREAD

**Issue by louisthomaspro** [amannn/next-intl#672]
### Is your feature request related to a problem? Please describe.

"next-intl": "3.1.4"

I would like to use `{ scroll: false }` in router.push method. In my case, I am intercepting a route to show a modal. This will prevent the background content to scroll to top.

### Describe the solution you'd like

When exporting `useRouter` navigation with `export const { useRouter } = createSharedPathnamesNavigation({ locales })`, the `router.push` method don't have the `scroll` option. It only has `locale`.

Can you please add this option from the original Nextjs router.push method pls ?

### Describe alternatives you've considered

Better stick with orginal nextjs method.

**Comment by amannn** [comment]
I think this is an upstream bug, I've added https://github.com/vercel/next.js/pull/59001 to handle this. For the time being, you can add `// @ts-expect-error` here, as the `scroll: false` is already supported by `next-intl`.

**Comment by amannn** [comment]
This is fixed in the latest version of Next.js. Thanks for the report!
