### ISSUE TITLE
Alternate links are not added to head section (App Router)

### ISSUE THREAD

**Issue by WhidRubeld** [amannn/next-intl#676]
### Description

The documentation says that the flag for installing alternative links is set by default: https://next-intl-docs.vercel.app/docs/routing/middleware#disable-alternate-links.

But that's not true. Links are not placed in head.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-54f7xy

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Inspect iframe code
3. View head parameters (empty)

### Expected behaviour

Set the alternate link for an alternate language in head section.

**Comment by sovetski** [comment]
It is not included in the header in SSG mode

**Comment by lucaslosi** [comment]
same here, no alternates added anywhere on the page

**Comment by lucaslosi** [comment]
not working here also.

![Image](https://github.com/user-attachments/assets/2ce4a23d-6139-4291-9110-726391a8050a)

I'm using the next-intl middleware with the alternateLink option set to true

**Comment by amannn** [comment]
@lucaslosi In case you're using Next.js 15, please see https://github.com/amannn/next-intl/issues/1442
