### ISSUE TITLE
useLocale returns locale from path params instead of provider value in client components

### ISSUE THREAD

**Issue by cbodin** [amannn/next-intl#688]
### Description

`useLocale` will always return the locale path parameter in client components even though `NextIntlClientProvider` is configured with a hard-coded locale. 

I cannot find anything related to this behaviour in the documentation so this should probably be documented and/or add an option to useLocale to retrieve the locale from the provider and not the path parameters for client components.

https://github.com/amannn/next-intl/blob/4369c7612b860ab31a173e7f045a839aa742f711/packages/next-intl/src/react-client/useLocale.tsx#L9-L18

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-w4q7qq

### Reproduction description

1. Open up the `/_next/info` page and view the resulting locales.
2. Open up the `/en/info` page and view the resulting locales.
3. Remove the `notFound();` call in `src/app/[locale]/layout.tsx`.
4. Open up the `/_next/info` page and view the resulting locales.

### Expected behaviour

The universal "useLocale" hook should return the expected locale configured in the provider in client components.
All displayed locales should be "en" in client components.

This ensures that components can be re-used in 404:s from _next/* paths.

**Comment by amannn** [comment]
Thank you so much for the great bug report!

I agree, this is indeed a bit confusing. https://github.com/amannn/next-intl/pull/691 will fix this.

**Comment by cbodin** [comment]
Thanks @amannn, works perfectly now!
