### ISSUE TITLE
useTranslations in class components

### ISSUE THREAD

**Issue by vkosovskikh** [amannn/next-intl#69]
**Is your feature request related to a problem? Please describe.**
I want to use `useTranslations` in class components but seems like I can't do this out of the box.

**Describe the solution you'd like**
May be add a hoc `withNextIntl` or something like that.

**Comment by amannn** [comment]
Hello @vkosovskikh,

if you need to use hooks from this library in class components I'd advise you to implement such a HOC in your code base ([instructions](https://reactjs.org/docs/higher-order-components.html)). HOCs have some drawbacks in comparison to hooks and I wouldn't want to increase the API surface of this library to include this.

I hope you can understand!
