### ISSUE TITLE
Timezone does not work when using Date Skeletons

### ISSUE THREAD

**Issue by PrinceGupta1999** [amannn/next-intl#693]
### Description

When using date Skeleton the timezone set in `i18n.ts` does not seem to be used.

When using the {date, date, full} specifier in messages, the timezone in i18n.ts is used for formatting dates.
When using {date, date, ::yyyy} or {date, date, ::MMMM} the system timezone is used.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-2r2fnp?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A5%2C57

### Reproduction description

Change the timezone in `i18n.ts` to `Asia/Kolkata` (GMT +05:30)
Use the message in en.json
```json
{
    "date": {
      "full": "Full Date: {date, date, full}",
      "month": "Month: {date, date, ::MMMM}",
      "year": "Year: {date, date, ::yyyy}"
    }
}
```
Set a date
```ts
const date = new Date('2024-01-01T00:00:00.000+0530');
```

Print the dates
```tsx
<div className="flex flex-col">
        <div>{tDate('full', {date})}</div>
        <div>{tDate('month', {date})}</div>
        <div>{tDate('year', {date})}</div>
</div>
```
For the full case: Monday, January 1, 2024 is printed (which is correct)
However for month: December is printed and year: 2023 is printed (which are incorrect)

### Expected behaviour

Irrespective of the date format being used the timezone specified in i18n.ts should be used

**Comment by amannn** [comment]
Thank you for the great bug report! I've added a reproduction in https://github.com/amannn/next-intl/pull/695.

I think this is an upstream bug in the message parser: https://github.com/formatjs/formatjs/issues/4279. Hopefully they can provide a fix.

In the meantime, please use [named formats](https://next-intl-docs.vercel.app/docs/usage/dates-times#dates-and-times-within-messages) as they're not subject to this bug.

**Comment by PrinceGupta1999** [comment]
Thanks a lot. Looking forward to the fix
