### ISSUE TITLE
How to handle date?

### ISSUE THREAD

**Issue by andrevenancio** [amannn/next-intl#70]
I can't figure out how to handle time. I've been using "javascript-time-ago" to display messages based off a timestamp. Like "1h ago" or "in 2hours".

But I'm sure I can deprecate this module and only use next-intl right?

**Comment by amannn** [comment]
Hi @andrevenancio,

yes, there's [`useIntl().formatRelativeTime`](https://github.com/amannn/next-intl/blob/main/docs/usage.md#formatrelativetime) to achieve this.

Did you find something unclear or misleading in the docs?

**Comment by andrevenancio** [comment]
Hey @amannn Somehow I've missed that. I think the way its organised you have to really read from beginning to end instead of just reading vertically trying to find something quick. Not necessarly your fault but mine :)

However, I have some questions on how to format it? so if I wanted to changee it to different languages "in 2hours" how can I configure the "in" from english to whatever language I'm targeting?

Also in regards to the `now` we're supposed to put in the Provider. How do you suggest we do this? since I have my Provider on the _app.ts ? Is it just a now={Date.now()} or does that Date.now() need to come from the server? You mention that with cache headers our chances of having a mismatch increase, what's your best practices that you recommend?

I really like this library. I guess my only suggestion is maybe some more examples. But again this might be me trying to solve things too quickly without properly absorving knowledge scattered on the docs :)

**Comment by andrevenancio** [comment]
For example:
```
import {useNow} from 'next-intl';

function Component() {
  const now = useNow();

  const dateTime = parseISO('2020-11-20T10:36:01.516Z');
  intl.formatRelativeTime(dateTime, now);
}
```

Where is this `intl` coming from?

**Comment by amannn** [comment]
> if I wanted to changee it to different languages "in 2hours" how can I configure the "in" from english to whatever language I'm targeting?

This is currently not possible. `next-intl` uses a built-in browser API for this feature which doesn't allow to customize this.

>  Is it just a now={Date.now()} or does that Date.now() need to come from the server? You mention that with cache headers our chances of having a mismatch increase, what's your best practices that you recommend?

From [the docs of `formatRelativeTime`](https://github.com/amannn/next-intl/blob/main/docs/usage.md#formatrelativetime):

```js
<NextIntlProvider
  // This value can be generated in data fetching functions of individual pages or `App.getInitialProps`.
  now={now}
  ...
>
  <App />
</NextIntlProvider>
```

> This value will be used as the default for the formatRelativeTime function as well as for the initial render of useNow.
> Important: When you use getStaticProps and no updateInterval, this value will be stale. Therefore either regenerate these pages regularly with revalidate, use getServerSideProps instead or configure an updateInterval.

Does that leave any questions open?

> I guess my only suggestion is maybe some more examples.

What kind of examples are missing? Did you see or have a look at the example app in the repo?

> Where is this intl coming from?

Good point, the import was missing here.

--

It seems like these are some issues with the docs. I've just created a new ticket look into these: https://github.com/amannn/next-intl/issues/72. I'm really grateful about feedback for the docs, so please leave any comments you have there!

**Comment by andrevenancio** [comment]
thank you for working on it and your patience guiding me through this.
