### ISSUE TITLE
Allow Redirect Type

### ISSUE THREAD

**Issue by brandanking-decently** [amannn/next-intl#709]
### Is your feature request related to a problem? Please describe.

Allow the redirect type to be set in the redirect function, currently all urls are redirected with a replace which isn't always applicable

### Describe the solution you'd like

Allow redirect type the same way as the Next function allows https://nextjs.org/docs/app/api-reference/functions/redirect

### Describe alternatives you've considered

Only alternative would be to use next redirect which could lead to chaining redirects

**Comment by amannn** [comment]
Thanks for the report! This will be addressed in https://github.com/amannn/next-intl/pull/714
