### ISSUE TITLE
Documentation update suggestion

### ISSUE THREAD

**Issue by andrevenancio** [amannn/next-intl#71]
on the documentation for time-zones you have `t('ordered', {orderDate: parseISO('2020-11-20T10:36:01.516Z')});`

But there's no reference to where that parseISO comes from. I'm suspecting its from `date-fns`. Could we use the equivalent in plain javascript? `Date.parse()` instead?

**Comment by amannn** [comment]
Thanks for the report, I've added an item about this in #72

**Comment by andrevenancio** [comment]
fair point! in that case, could you add the import on the snippet so its easier to pick up where its coming from?

**Comment by amannn** [comment]
Yep, definitely – it's already fixed in the docs improvement branch: https://github.com/amannn/next-intl/pull/73.
