### ISSUE TITLE
[Docs]: Next.js App Router internationalized navigation

### ISSUE THREAD

**Issue by scazan** [amannn/next-intl#710]
### Link to page

https://next-intl-docs.vercel.app/docs/routing/navigation

### Describe the problem

The docs are out of date as `createSharedPathnamesNavigation` no longer exists in the latest versions.

**Comment by amannn** [comment]
It definitely exists in the latest versions. Are you using an old version of `next-intl`?

**Comment by scazan** [comment]
Hmm.. I was on v3.3.1 when I posted this and was getting an error. Now with 3.3.2 released a couple days ago it seems to work!

Whatever happened, good news!

Thanks!
