### ISSUE TITLE
Default language not working with turbo in Next.js 14

### ISSUE THREAD

**Issue by abiddraws** [amannn/next-intl#718]
### Description

I have encountered an issue when using turbo with Next.js 14 where the default language is not working as expected. I have configured two languages ['en', 'ar'], but when using the --turbo flag in the scripts, the website only displays content in the 'ar' language.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/abiddraws/MyNextJs

### Reproduction description

Steps to reproduce:
1. clone the github repository
2. pnpm install
3. pnpm dev
4. You can see only in arabic

### Expected behaviour

I should be able to see both in Arabic and English , when I change url
base-url/en => english
base-url/ar => arabic

**Comment by fliodhais** [comment]
Was just here to see if my problem might exist here as well but I found some issues trying to recreate your bug. Mainly just cause there's no supabase configs that'll let the maintainers easily identify your issue. Would recommend adding that.

**Comment by abiddraws** [comment]
@fliodhais Hi, thank you for the review. I have removed Supabase from my code, The problem persists even without Supabase.

**Comment by fliodhais** [comment]
Cool, now that I can actually run the dev server. It appears that my initial idea
>Was just here to see if my problem might exist here as well
was true and there is an issue with the way that turbopack (instead of webpack) interacts with `next-intl`.

As I have done in my own project, I would recommend replacing the `dev` script from `next dev --turbo` to `next dev`. 

As [Turbopack](https://nextjs.org/docs/architecture/turbopack) is still experimental, this issue should probably be brought up on https://github.com/vercel/turbo.

**Comment by abiddraws** [comment]
@amannn As per the document [turbopack](https://nextjs.org/docs/architecture/turbopack) you need to add `"dev": "next dev --turbo"` script to the package.json file. which is not added in 
[example-app-router](https://github.com/amannn/next-intl/blob/main/examples/example-app-router/package.json#L6)

**Comment by amannn** [comment]
I ran the example via `pnpm run dev --turbo`.

**Comment by amannn** [comment]
I had a moment to have a look at your project. It seems like Turbopack has problems importing the correct messages file:

<img width="634" alt="image" src="https://github.com/amannn/next-intl/assets/4038316/7aab0721-aa87-4f66-89e1-94820e66a70c">

… however, Turbopack loads the `ar` messages.

If you change the import to `messages: (await import('./messages/en.json')).default,`, then this works.

I'm honestly not sure why you're affected by this issue and the example in this repo isn't.

I'm going to close this, as this seems to be a bug in Turbo. Maybe you want to have a look if there's an existing bug report for this on their side!

**Comment by abiddraws** [comment]
@amannn Thanks for the thorough review!, For me the above solution didnt work, hower I identified that the problem lay within the `messages` prop passed to `<NextIntlClientProvider />`.

When I changed my  [code](https://github.com/abiddraws/MyNextJs/blob/main/app/%5Blocale%5D/layout.tsx#L23) to like this it worked as expected.
```
import enMessages from "../../messages/en.json";
import arMessages from "../../messages/ar.json";


let messages: any = enMessages;
  if (locale === "ar") {
    messages = arMessages;
  }
```
