### ISSUE TITLE
[Docs]: Example: Integrating with Supabase Authentication

### ISSUE THREAD

**Issue by amannn** [amannn/next-intl#719]
### Link to page

https://next-intl-docs.vercel.app/docs/routing/middleware

### Describe the problem

`@supabase/auth-helpers-nextjs` [is deprecated](https://supabase.com/docs/guides/auth/auth-helpers/nextjs):

> We generally recommend using the new @supabase/ssr package instead of auth-helpers. @supabase/ssr takes the core concepts of the Auth Helpers package and makes them available to any server framework. Check out the [migration doc](https://supabase.com/docs/guides/auth/server-side/migrating-to-ssr-from-auth-helpers) to learn more.

It would be helpful if we update our example in the docs too. I don't have any experience with Supabase, therefore it would be helpful if someone who actively uses Supabase could adapt this.

@wscourge Since you've provided https://github.com/amannn/next-intl/pull/673, do you by chance know how to upgrade?

**Comment by wscourge** [comment]
I'll keep in mind doing it once done in my project.

**Comment by abiddraws** [comment]
Hi, Any update on this ? @wscourge have you given it a try?

**Comment by wscourge** [comment]
Nope. Have you?

**Comment by flixlix** [comment]
Just made this PR, hope it helps: #856
