### ISSUE TITLE
question: if i have app with alot of pages and alot of translations .... 

### ISSUE THREAD

**Issue by zakidze** [amannn/next-intl#731]
### Description

if i have app with alot of pages and alot of translations will it load only the required translation for each page

example i have home page , about page, contact page

will home translations string loads when accssing about page?

say i everypage is static and just 1 page is dynamic product/[id]
does the whole translatiosns get loaded only for the this page ? or just the product strings???,

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

-

### Reproduction description

----

### Expected behaviour

----

**Comment by amannn** [comment]
In Server Components currently [all messages are loaded](https://next-intl-docs.vercel.app/docs/usage/configuration#i18nts) and on the client side you can [pick which ones to load](https://next-intl-docs.vercel.app/docs/environments/server-client-components#option-3-providing-individual-messages). Note that [automatic tree-shaking of messages is under consideration](https://github.com/amannn/next-intl/issues/1).
