### ISSUE TITLE
`useTranslations` is not callable within an async component.

### ISSUE THREAD

**Issue by szandrzej** [amannn/next-intl#733]
### Description

Hi!
At first - thanks for appdir support, great work!
I am recently struggling with a lot of 500s, due to mentioned error message, which is weird because there is no async component, who is calling `useTranslaction`.
![Zrzut ekranu 2023-12-19 o 14 32 25](https://github.com/amannn/next-intl/assets/6654872/e0c28292-8108-4058-8b6b-4a271947cdaa).
Occurs only on prod environments, staging and prod, both hosted on Vercel.

Is it a bug? 

### Mandatory reproduction URL (CodeSandbox or GitHub repository)
https://gist.github.com/szandrzej/36494ef4b9fe384fe5abfdbae9fad050

### Reproduction description

Steps to reproduce:
Occasionally entering page, visible in sentry logs as it's mostly visited by monitor

### Expected behaviour

No 500s

**Comment by hyepod** [comment]
Hello @szandrzej 

I have exactly the same problem.
Locally there are no errors, but in prod I have a lot of 500 errors (and I also see them on Sentry)
But it's random, when I just refresh the page and it works.

How do you handle this? Did you correct the error?

**Comment by szandrzej** [comment]
Unfortunately not

**Comment by szandrzej** [comment]
what about you?

**Comment by mngrs** [comment]
@szandrzej 
I'm still stuck.
What did you use instead?

**Comment by darenmalfait** [comment]
Not sure if related, but I had 500 errors in production (only when built, not dev). 

The issue was Next15 and async pages.

I had to await the props for it to work
```
export default async function HomePage(props: { params: Promise<{locale: string}> }) {
	// need to await this before using getTranslations
	await props.params
	const t = await getTranslations('pages.home')
```
