### ISSUE TITLE
Provide a way how to disable accept-language detection

### ISSUE THREAD

**Issue by MilosMosovsky** [amannn/next-intl#735]
### Is your feature request related to a problem? Please describe.

We are running a website that has mixed `domain` and `prefix` locales. To describe the problem in a more detailed way, our website is using several major markets ccTLDs to force locale eg `example.de` will force user to `de` language and visiting `example.fr` will force to `fr` locale. With this setup we also provide multiple different locales on our main website `example.com` that should be always in an english. 

In the language picker user should be able to navigate to `example.com/it` to switch to the `it` locale. 

This works great with localeDetection and custom middleware however the problem is with the `accept-language` detection which occurs here https://github.com/amannn/next-intl/blob/8009a9534444f7fcc11225d7c3054942079af2ab/packages/next-intl/src/middleware/resolveLocale.tsx#L88

What happens at the moment is that when user visits our homepage, `example.com` with `accept-language: it` header it will automatically switch to `it` locale because of header, but instead we would like to show a modal to switch language. 

### Describe the solution you'd like

This could be done either by making priorities more granular either with `.env` vars or split `localeDetection` to a map of config for each pro strategy.

Best could be to extract strategies to an adapters something like 

```
localeDetection: [pathNameStrategy, cookieStrategy, headerStrategy, defaultLocaleStrategy]
```

In this way everyone could also switch order/prio of strategies and enable/disable the wanted ones. 

### Describe alternatives you've considered

UPDATE: 

I've temporarily solved it by
```
export default function middleware(req: NextRequest) {
  const newRequest = new NextRequest(req)
  newRequest.headers.set('accept-language', 'en')

  return intlMiddleware(newRequest);
}
```

But anyways, the above suggestion about adapters would make more sense. 

I am happy to open PR if agreed.

**Comment by amannn** [comment]
Have you tried [`localeDetection: false`](https://next-intl-docs.vercel.app/docs/routing/middleware#disable-automatic-locale-detection)?

**Comment by MilosMosovsky** [comment]
> Have you tried [`localeDetection: false`](https://next-intl-docs.vercel.app/docs/routing/middleware#disable-automatic-locale-detection)?

@amannn Sure! But with `localeDetection: false` it doesn't read/set cookies, and what's more important it ignores `localePrefix` so when I visit `example.com/it` it's still in the english and it completely ignores all locale detection. 

Imho if there is localePrefix setup it shouldn't ignore it even with `localeDetection: false`. I believe `localeDetection` from it's name assumes "detecting a locale" or better to say `guessing a locale` (IP/headers) while force setting cookie, or providing the locale in the url is already a detected language (either by google links or by whatever else) and should be always respected.

The way how it behaves at the moment  is basically either you can switch languages or no, which seems weird. `localePrefix` should be always respected even if all 3 strategies will determine different language, what's in the `localePrefix` should always force override that ... that's for SEO purposes similar issue just appeared today here https://github.com/amannn/next-intl/issues/745

It's great that library provides locale/cookie detection, that's it purpose, but it shouldn't try to outsmart developer config by parsing client information and setting that language, and if yes - make it unplug-gable. 

I've had another case which is broken on other app - we are storing preferredLocale in database, and localeDetection is overriding that configuration.

**Comment by amannn** [comment]
> what's more important it ignores `localePrefix` so when I visit `example.com/it` it's still in the english and it completely ignores all locale detection.

Do you have a reproduction for that? I can't see this behavior in `example-app-router` in this app after setting `localeDetection: false`. It would certainly be a bug if that's the case. It's also [documented](https://next-intl-docs.vercel.app/docs/routing/middleware#locale-detection) that a locale prefix in the pathname should always take precedence.

**Comment by michael-land** [comment]
Can the accept-language detection be disabled while retaining the capability to read a user's previous selection from a cookie?

**Comment by amannn** [comment]
@michael-land Currently not out-of-the-box, but you can [compose the middleware](https://next-intl-docs.vercel.app/docs/routing/middleware#composing-other-middlewares) with some custom logic to achieve this:

```tsx
import {NextRequest} from 'next/server';
import createIntlMiddleware from 'next-intl/middleware';

export default async function middleware(request: NextRequest) {
  const defaultLocale = request.cookies.get('NEXT_LOCALE')?.value || 'en';

  const handleI18nRouting = createIntlMiddleware({
    locales: ['en', 'de'],
    defaultLocale,
    localeDetection: false
  });

  return handleI18nRouting(request);
}
```

**Comment by zipme** [comment]
> @michael-land Currently not out-of-the-box, but you can [compose the middleware](https://next-intl-docs.vercel.app/docs/routing/middleware#composing-other-middlewares) with some custom logic to achieve this:
> 
> ```tsx
> import {NextRequest} from 'next/server';
> import createIntlMiddleware from 'next-intl/middleware';
> 
> export default async function middleware(request: NextRequest) {
>   const defaultLocale = request.cookies.get('NEXT_LOCALE')?.value || 'en';
> 
>   const handleI18nRouting = createIntlMiddleware({
>     locales: ['en', 'de'],
>     defaultLocale,
>     localeDetection: false
>   });
> 
>   return handleI18nRouting(request);
> }
> ```

This would still have issue if `localePrefix` is set to `"as-needed"`
