### ISSUE TITLE
Support for esmodules for withNextIntl 

### ISSUE THREAD

**Issue by kyeshmz** [amannn/next-intl#739]
### Is your feature request related to a problem? Please describe.

I need support for esmodules for using create t3app, things like env.mjs in the create t3 app help typesaftey of envs that I have across different environments.

### Describe the solution you'd like

Support for esmodules

### Describe alternatives you've considered

Not supporting, which is what is currently happening.

**Comment by amannn** [comment]
> Support for esmodules for withNextIntl

Do you mean providing your Next.js config in `next.config.mjs`? This is supported, here's an example: https://github.com/amannn/next-intl/blob/main/examples/example-app-router-playground/next.config.mjs

**Comment by kyeshmz** [comment]
That works! Might be handy to put it into docs, but for this issue, I am closing as resolved.
