### ISSUE TITLE
static export error after version v.3.0.0-rc.4 (nextjs 13.5 || 14)

### ISSUE THREAD

**Issue by el-j** [amannn/next-intl#743]
### Description

I have a nice multi-language page, with `static export` from nextjs. 
i need to stay with static export and cannot use e.g. `middleware.ts`. 

errors start with versions:
**v.3.0.0-rc.5**: some error output but still builds:

```
s [Error]: ENVIRONMENT_FALLBACK
    at /Users/path/.next/server/chunks/381.js:9:10607
    at p.useTranslations (/Users/path/.next/server/chunks/381.js:9:10863)
    at /Users/path/.next/server/chunks/381.js:1:51358
    at Translate (/Users/path/.next/server/chunks/667.js:1:25599)
    at nd (/Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:35308)
    at nd (/Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:48158)
    at nh (/Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:50922)
    at ny (/Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:53901)
    at nd (/Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:45663)
    at nh (/Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:27:50922) {
  code: 'ENVIRONMENT_FALLBACK',
  originalMessage: undefined
}
```
<img width="578" alt="image" src="https://github.com/amannn/next-intl/assets/2795534/06738a74-47ec-480e-98bd-cfee3fc95767">

newer versions errors and do not do export and build anymore:
tested versions: 
**v3.0.0-rc.10**
**v3.0.1**
**v3.4.0** 
```
StaticGenBailoutError: Page with `dynamic = "error"` couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering
    at staticGenerationBailout (/Users/path/.next/server/chunks/885.js:1:76640)
    at headers (/Users/path/.next/server/chunks/585.js:1:140493)
    at /Users/path/.next/server/chunks/585.js:1:135208
    at /Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:107:5254
    at s (/Users/path/.next/server/chunks/585.js:1:135932)
    at e (/Users/path/.next/server/chunks/585.js:1:136024)
    at m (/Users/path/.next/server/chunks/585.js:1:137579)
    at ev (/Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:11059)
    at /Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:21907
    at Object.toJSON (/Users/path/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:91:25224) {
  code: 'NEXT_STATIC_GEN_BAILOUT'
}
```

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-59lk54?file=%2Fpackage.json%3A1%2C1

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. open package.json
3. change next-intl version to newer then `3.0.0-rc.4`
4. open terminal
5. run `npm i` to upgrade modules
6. run `dev` or `build`
8. See error: 
<img width="488" alt="image" src="https://github.com/amannn/next-intl/assets/2795534/a6de3f9e-d6e9-4fa0-b2ac-56e48cd81b66">

### Expected behaviour

with 3.0.0-rc.4:
<img width="847" alt="image" src="https://github.com/amannn/next-intl/assets/2795534/1256c210-62c0-458d-89b6-fe158cd67e05">

i need the static export from nextjs but want to upgrade my next-intl dependency.

**Comment by amannn** [comment]
Hey, thank you for the question! The section [Changes to `NextIntlClientProvider`](https://next-intl-docs.vercel.app/blog/next-intl-3-0#changes-to-nextintlclientprovider) in the changelog for 3.0 is relevant to you:

> (...) **Using `NextIntlClientProvider` with the App Router**

> If you're using `NextIntlClientProvider` _with the App Router_, there has been a slight change to the semantics. If you're rendering `NextIntlClientProvider` within a Server Component, the component will pass defaults for `locale`, `now` and `timeZone` to the client side.

> If you're already providing these options, then you're set.

> If you're not, be aware that this will by default opt the corresponding page into dynamic rendering. If your app relies on static rendering, you can avoid this by passing all of the mentioned options, or by enabling static rendering explicitly (see the previous section).

Adapting the call to `NextIntlClientProvider` in your layout fixes this for me:

```tsx
<NextIntlClientProvider
  timeZone="Europe/Vienna"
  now={new Date()}
  locale={locale}
  messages={messages}
>
  {children}
</NextIntlClientProvider>
```

Hope this helps!

**Comment by el-j** [comment]
@amannn thank u very much. that was fast and indeed that helped!  But now it is even more problematic as the <Link> component creates a renderloop after static export...

i have prepared the sandbox to show the issue. useing the next-intl-Link component and the standard NextJs-Link component. 

please open the sandbox. 
<img width="1189" alt="image" src="https://github.com/amannn/next-intl/assets/2795534/dae53fa5-e977-4760-a509-282d8c7a97e0">

in the preview `start:3000` there is the running static export. hover over the `next-intl Link` (_go to sub_). 
you will see the render loop in the console as u can see from the screenshot. as well as the Link does not do anything onClick. Same issue in the subpage for the go back.


any idea why this happens? do you need a new issue for this?
(nextjs 14.0.4, next-intl: 3.4.0)

[codesandbox](https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-59lk54?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A1%2C1-28%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqfujd3g00073b6ivnz85m79%2522%252C%2522sizes%2522%253A%255B73.02238410348204%252C26.97761589651796%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqfujd3f00023b6iuwuidngh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqfujd3f00043b6iwtzerrie%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqfujd3g00063b6ihnsx32gg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B56.53818969684852%252C43.46181030315148%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqfujd3f00023b6iuwuidngh%2522%253A%257B%2522id%2522%253A%2522clqfujd3f00023b6iuwuidngh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqfujd3f00013b6idzkz96m8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqfujd3f00013b6idzkz96m8%2522%257D%252C%2522clqfujd3g00063b6ihnsx32gg%2522%253A%257B%2522id%2522%253A%2522clqfujd3g00063b6ihnsx32gg%2522%252C%2522activeTabId%2522%253A%2522clqgozaf002333b6iy9hgrqzv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clqgort7j01853b6ii9yln86m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fen%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3001%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqgozaf002333b6iy9hgrqzv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fen%2522%257D%255D%257D%252C%2522clqfujd3f00043b6iwtzerrie%2522%253A%257B%2522id%2522%253A%2522clqfujd3f00043b6iwtzerrie%2522%252C%2522activeTabId%2522%253A%2522clqgoyr6g01zs3b6id7kq0hp0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522clqgoojnm012s3b6irb3tsbjv%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clqgoy3hc01u93b6i7y0c3346%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqgoyr6g01zs3b6id7kq0hp0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by amannn** [comment]
You're calling `createSharedPathnamesNavigation` within a component, this causes a new `Link` component to be created on each render, causing the infinite loop.

You can fix this by moving the call outside of your component.
