### ISSUE TITLE
[Docs]: I couldn't find the demo mentioned in the documentation

### ISSUE THREAD

**Issue by flowerofmycountry** [amannn/next-intl#749]
### Link to page

https://next-intl-docs.vercel.app/docs/routing/middleware#usage-without-middleware-static-export

### Describe the problem

![image](https://github.com/amannn/next-intl/assets/42023882/33c99d9b-4db7-4a3f-96da-2b2ba16d5948)

I couldn't find the demo mentioned in the documentation

**Comment by amannn** [comment]
The App Router example is listed as the first example on the examples page:

<img width="580" alt="image" src="https://github.com/amannn/next-intl/assets/4038316/252b9c3f-9505-4cec-b038-0a8c2a8b2720">

It's scrolled into view if you follow the link: https://next-intl-docs.vercel.app/examples#app-router
