### ISSUE TITLE
Invalid CSS path

### ISSUE THREAD

**Issue by quannv** [amannn/next-intl#766]
### Description

Generated css file path in head contain the invalid character [locale]

<link rel="stylesheet" href="/_next/static/css/app/[locale]/layout.css?v=1704816344500" data-precedence="next_static/css/app/[locale]/layout.css">

<img width="988" alt="Monosnap Book the bus, car, ferry, train for you ride 2024-01-09 22-57-09" src="https://github.com/amannn/next-intl/assets/1892676/d0cb4bb4-915e-46fc-9f24-237ced686b35">

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-zcymvq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr6jgyfy00073b6mbaeo1plr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr6jgyfy00023b6m2l3k46nf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr6jgyfy00043b6mp43ru9m3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr6jgyfy00063b6mxnkbxh6a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr6jgyfy00023b6m2l3k46nf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6jgyfx00013b6mh984lzc0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr6jgyfy00023b6m2l3k46nf%2522%252C%2522activeTabId%2522%253A%2522clr6jgyfx00013b6mh984lzc0%2522%257D%252C%2522clr6jgyfy00063b6mxnkbxh6a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6jgyfy00053b6mddof1yc0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fen%2522%257D%255D%252C%2522id%2522%253A%2522clr6jgyfy00063b6mxnkbxh6a%2522%252C%2522activeTabId%2522%253A%2522clr6jgyfy00053b6mddof1yc0%2522%257D%252C%2522clr6jgyfy00043b6mp43ru9m3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6jgyfy00033b6mcrhwftrk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clr6jgyfy00043b6mp43ru9m3%2522%252C%2522activeTabId%2522%253A%2522clr6jgyfy00033b6mcrhwftrk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Reproduction description

Steps to reproduce:
1. Open codesandbox link
2. Inspect website by chrome developer tool
3. See head block

### Expected behaviour

clean css file path

**Comment by quannv** [comment]
Just create global.css file in root app dir, import css file into layout file
I have updated the sandbox link: https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-kvqzrq?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Flayout.tsx%3A10%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr6jgyfy00073b6mbaeo1plr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr6jgyfy00023b6m2l3k46nf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr6jgyfy00043b6mp43ru9m3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr6jgyfy00063b6mxnkbxh6a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr6jgyfy00023b6m2l3k46nf%2522%253A%257B%2522id%2522%253A%2522clr6jgyfy00023b6m2l3k46nf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6jgyfx00013b6mh984lzc0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr6jgyfx00013b6mh984lzc0%2522%257D%252C%2522clr6jgyfy00063b6mxnkbxh6a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6jgyfy00053b6mddof1yc0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fen%2522%257D%255D%252C%2522id%2522%253A%2522clr6jgyfy00063b6mxnkbxh6a%2522%252C%2522activeTabId%2522%253A%2522clr6jgyfy00053b6mddof1yc0%2522%257D%252C%2522clr6jgyfy00043b6mp43ru9m3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6jgyfy00033b6mcrhwftrk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clr6jgyfy00043b6mp43ru9m3%2522%252C%2522activeTabId%2522%253A%2522clr6jgyfy00033b6mcrhwftrk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by amannn** [comment]
I'm not sure what you mean by "invalid CSS path" in the issue title.

Next.js creates this CSS path:

<img width="378" alt="Screenshot 2024-01-12 at 09 01 32" src="https://github.com/amannn/next-intl/assets/4038316/b8e388f9-075f-4ea5-99bf-b9a0cb57ceab">

… and it seems to be working in Chrome for me. 

Also note that after the building your project, the CSS import will look like this:

<img width="305" alt="Screenshot 2024-01-12 at 09 07 04" src="https://github.com/amannn/next-intl/assets/4038316/ad640a8f-e5fc-4279-9d3f-84ca59107811">

next-intl doesn't control anything about the path that Next.js generates, I don't think there's anything we can do here.
