### ISSUE TITLE
Ability to change X-NEXT-INTL-LOCALE header name

### ISSUE THREAD

**Issue by marcincodes** [amannn/next-intl#780]
### Is your feature request related to a problem? Please describe.

In my application I'm already using using header to pass local between server and client. It's called `x-locale` and it's exactly the same as `X-NEXT-INTL-LOCALE`. But right now I need to pass both headers.

I'm happy to help contribute this feature and submit PR if you are willing to approve such feature

### Describe the solution you'd like

Add ability to change header name in next.config similar as we are changing path to i18n file

### Describe alternatives you've considered

Add both `x-locale` and `X-NEXT-INTL-LOCALE` header

**Comment by amannn** [comment]
Thank you for offering your help for contribution @marcincodes! 

> In my application I'm already using using header to pass local between server and client

`x-next-intl-locale` is meant as a workaround for passing the locale between the middleware and React Server Components (some more on this in [the static rendering section](https://next-intl-docs.vercel.app/docs/getting-started/app-router#static-rendering) in the docs).

What is your use case for providing the `x-locale` header? Note that you can [compose the middleware](https://next-intl-docs.vercel.app/docs/routing/middleware#composing-other-middlewares) to read from a custom header to assign e.g. the `defaultLocale` dynamically.

`x-next-intl-locale` is really a workaround that is currently necessary and I hope to [remove it eventually](https://github.com/amannn/next-intl/issues/663). Therefore, I'm not looking for configuration options in regard to this—I hope you can understand!

**Comment by marcincodes** [comment]
We are using `x-locale` to communicate user locale to backend and setup translation in on server side.

If that's a workaround and long term goal is to get rid of it I fully understand you don't want to make such configuration.

Thanks for your response and for your work on next-intl!

**Comment by amannn** [comment]
I see! Thanks, I'll close this for the time being then as long as there's a way for you to integrate with your custom header.
