### ISSUE TITLE
The document website is down 

### ISSUE THREAD

**Issue by MuLoo** [amannn/next-intl#787]
### Description

https://next-intl-docs.vercel.app/  cannot be accessed

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

none

### Reproduction description

Steps to reproduce:
1. click  https://next-intl-docs.vercel.app/

### Expected behaviour

https://next-intl-docs.vercel.app/  can accessed again

**Comment by amannn** [comment]
Seems to [work fine](https://downforeveryoneorjustme.com/next-intl-docs.vercel.app?proto=https)?

**Comment by MuLoo** [comment]
> Seems to [work fine](https://downforeveryoneorjustme.com/next-intl-docs.vercel.app?proto=https)?

![CleanShot 2024-01-19 at 09 51 49@2x](https://github.com/amannn/next-intl/assets/23740140/a12a52b5-535c-489d-bc25-62fbd2c484cf)

**Comment by amannn** [comment]
So strange, I can't reproduce that at all.

<img width="760" alt="Screenshot 2024-01-19 at 08 36 07" src="https://github.com/amannn/next-intl/assets/4038316/e5a79998-9a24-45dc-8627-68a7b54744b3">

The website is hosted on Vercel, [they don't report an incident either](https://www.vercel-status.com/).

**Comment by MuLoo** [comment]
> So strange, I can't reproduce that at all.
> 
> <img alt="Screenshot 2024-01-19 at 08 36 07" width="760" src="https://private-user-images.githubusercontent.com/4038316/297988107-e5a79998-9a24-45dc-8627-68a7b54744b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTAxMzAsIm5iZiI6MTcwNTY0OTgzMCwicGF0aCI6Ii80MDM4MzE2LzI5Nzk4ODEwNy1lNWE3OTk5OC05YTI0LTQ1ZGMtODYyNy02OGE3YjU0NzQ0YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMDczNzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDg0ZmY5ZjU3ZDM4M2ExNDgzYjM5MDdlZmFhM2M3YWI4MjNmNzI0NmYwMWM3OTM3ZmU5NzVhYzk4MTcyODMwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wx5uQJRpE_rkfO9xzodQ_fILaeifF4Xya8e_gpexR-4">
> The website is hosted on Vercel, [they don't report an incident either](https://www.vercel-status.com/).

It’s really strange, it seems to be related to the VPN node.
When I use the Hong Kong node, I can’t access it. 
Switch to the Japan node, everything is normal. 
Anyway, Thank you for your work, bro, love you, hope you are well ❤️
