### ISSUE TITLE
Iteration key with rich text

### ISSUE THREAD

**Issue by matheus-rosin** [amannn/next-intl#79]
**Describe the bug**

When using `t.rich` for rendering rich text, and inside translation there is more than one occurrence of same element with same amount of element children or same string content, a React warning concerning repeated keys with weird key is shown in console.

![image](https://user-images.githubusercontent.com/26561457/150025411-93e586ce-b6cc-45df-9559-f43da0196c36.png)

**To Reproduce**

Any attempt, like

```jsx
// Anything = '<b>first</b> lorem ipsum <b>first</b>'

return (
  <div>
    {t.rich('Anything', { bold: text => <b>{text}</b> })}
  </div>
)
```

**Comment by matheus-rosin** [comment]
Thinking now, I believe it has not to do with repeated elements, but with elements that have other elements inside it.

So, in the example of the screenshot, `ol`'s have `li`'s inside it; if translation content has same tag with same amount of children, this will happen, because of the way keys are being generated (element name + content).

**Comment by matheus-rosin** [comment]
If that is true, it means that if, for some reason, I have a translation like `<b>repeated</b> lorem ipsum <b>repeated</b>` should get repeated keys (`brepeated`)

**Comment by matheus-rosin** [comment]
Just updated issue description according this new thought

**Comment by amannn** [comment]
Thanks for the report, this is a good point! I'll have a fix published shortly.
