### ISSUE TITLE
How to remove "/en" from domain?

### ISSUE THREAD

**Issue by matt18465** [amannn/next-intl#795]
### Is your feature request related to a problem? Please describe.

currently library forces me to add "en" even though it's default language

https://localhost:3000/en

### Describe the solution you'd like

https://localhost:3000/

### Describe alternatives you've considered

there is no alternative

**Comment by amannn** [comment]
You’re looking for this: https://next-intl-docs.vercel.app/docs/routing/middleware#locale-prefix
