### ISSUE TITLE
Recent Next version has problems with next-intl?

### ISSUE THREAD

**Issue by BearCooder** [amannn/next-intl#802]
### Description

Hello,

it seems that there is a problem with next-intl and the recent version of Next.js? Every page is not accessible and throwing not found errors.
In my reproduction repo I try to use next-intl but I always get the `404 This page could not be found.` error. When I open the browser console there are multiple reports of ```Error: NEXT_NOT_FOUND lockdown-install.js:1:94626```

But all routes are working when i just remove my next-intl. 

This is actually very strange because I have a project with the same setup for next intl (but with Next v13 not 14) that is working.
I provided a minimal as possible repository with the error.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/BearCooder/error-example

### Reproduction description

Steps to reproduce:
1. run npm run dev
2. See error: … 

### Expected behaviour

No  error of ```Error: NEXT_NOT_FOUND lockdown-install.js:1:94626```__

**Comment by aXenDeveloper** [comment]
Your `middleware.ts` should be in root folder.
