### ISSUE TITLE
Locale is reseted from selected to accept-language's locale when localePrefix is 'never'

### ISSUE THREAD

**Issue by aleeghb** [amannn/next-intl#811]
### Description

When user navigates from external site to our site then locale is reseted to accept-language's locale because NEXT_LOCALE cookie has a `SameSite: Strict` and browser don't send cookie in this case. Also `localePrefix` is `never` and thats why next-intl set locale to accept-language's locale (or to default locale).

This is not reproducible if `Lax` is used.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

-

### Reproduction description

I can't give you reproduction example, I've tried but it's not working (basic functional). Unfortunately, I don't have time to figure out why.

### Expected behaviour

Shouldn't reset  the locale.

**Comment by amannn** [comment]
Yep, this is correct, thanks for the report! Will be fixed in #817.
