### ISSUE TITLE
Next.JS big Middleware size when using next-intl (possible messages leak into middleware bundle)

### ISSUE THREAD

**Issue by apavlinovic** [amannn/next-intl#814]
### Description

Hi, I was trying to deploy my Next.js site on Vercel, and its failing due to the middleware.ts file being too big:

Error: The Edge Function "src/middleware" size is 2.47 MB and your plan size limit is 1 MB. Learn More: https://vercel.link/edge-function-size

I tried looking around a bit and couldn't seem to grasp why the middleware would need to be that large.

My middleware is purely just the next-intl middleware, nothing else:

import createMiddleware from 'next-intl/middleware';
import { languages } from '@/types';

export default createMiddleware({
  locales: languages,
  defaultLocale: 'en',
});

export const config = {
  matcher: ['/((?!api|_next|_vercel|.*\\..*).*)'],
};
I'm using:

    "next": "13.5.4",
    "next-intl": "^3.0.0-rc.7",
    "react": "^18.2.0",
    "react-dom": "^18",
Mandatory reproduction URL (CodeSandbox or GitHub repository)
https://github.com/t2pellet/tenzin.live

Reproduction description
Steps to reproduce:

Use next-intl middleware in middleware.ts
Try to deploy to Vercel
Expected behaviour
The middleware.ts file should be a smaller/more reasonable size

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/t2pellet/tenzin.live

### Reproduction description

Reproduction description
Steps to reproduce:

Use next-intl middleware in middleware.ts
Try to deploy to Vercel

### Expected behaviour

The middleware.ts file should be a smaller/more reasonable size

**Comment by apavlinovic** [comment]
Sorry, I am trying to reopen https://github.com/amannn/next-intl/issues/599 as I don't think this is a NextJS issue, but a problem with next intl's requirement to import translation files in the i18n-config file. Please read this:

@amannn I think this needs to be reopened. It is not nextjs, it is the fact that we are including messages on every request in the i18n configuration of Next Intl. Basically, when you write

```
export default getRequestConfig(async ({ locale }) => {
   return {
     .... you ask to import JSON files here in the docs
   }
}
```

Where you import JSON files, those JSON files are bundled by webpack, since you explicitly ask us to import them. This is causing the bloat in middleware size – this is not a NextJS problem, it's a next-intl problem!

**Comment by amannn** [comment]
@apavlinovic Can you upgrade `next` and `next-intl` to the latest version in your app to see if it makes a difference?

The middleware doesn't import anything from `i18n.ts`, so this shouldn't make a difference.

**Comment by apavlinovic** [comment]
Hey @amannn I am not sure that's true...

So my middleware looks like this:

`export function middleware() {}`

and it's size is:

`ƒ Middleware                                        290 kB`

I've went through the code in middlewareImpl, and you are reading the messages from an in-memory dictionary, which is defined in i18n.ts. Every JSON file you imported ends up there, and since you are reading it on every request, it looks like it is getting bundled with middleware.ts, making next-intl unusable for real world usage?

I am on next-intl "3.5.2", next "14.1.0", and this behaviour is consistent for older Next JS versions like 13.5.4. It is not a Next JS problem, Next JS is doing the correct thing here, it is bundling imported strings with the middleware. You mentioned in 

FYI, this is my i18n-config file:

`export default getRequestConfig(async ({ locale = "xxx" }) => {
    return {
        namespaces: [
            "bestAttackersPerType",
            "bestGymDefenders",
            "bestPerTypeList",
            "bestRaidAttackers",
            "buddyDistancesList",
            "chargeMovesList",
            "chargeMovesListPvP",
            "common",
            "comparer",
            "disclaimer",
            "fastMovesList",
            "fastMovesListPvP",
            "home",
            "move",
            "pokedex",
            "pokemonPage",
            "regionAndTypeList",
            "shinyChecklist",
            "typeChart",
            "whosThatPokemon",
            "pokemonTyping",
            "navigationLinks",
            "countersPage",
            "pokemonIvChartPage",
            "pokemonMovesPage",
            "evolutionChartComponent",
            "ivChartSpecialEncounters",
            "moveCard",
            "typeDescriptions",
            "countersComponent",
            "pokemonPvpPage",
        ],
        messages: {
            bestAttackersPerType: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */
                        `../messages/${locale}/bestAttackersPerType.json`
                    )
                ).default,
            },
            bestGymDefenders: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/bestGymDefenders.json`
                    )
                ).default,
            },
            bestPerTypeList: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/bestPerTypeList.json`
                    )
                ).default,
            },
            bestRaidAttackers: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/bestRaidAttackers.json`
                    )
                ).default,
            },
            buddyDistancesList: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */
                        `../messages/${locale}/buddyDistancesList.json`
                    )
                ).default,
            },
            chargeMovesList: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/chargeMovesList.json`
                    )
                ).default,
            },
            chargeMovesListPvP: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */
                        `../messages/${locale}/chargeMovesListPvP.json`
                    )
                ).default,
            },
            common: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/common.json`
                    )
                ).default,
            },
            comparer: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/comparer.json`
                    )
                ).default,
            },
            disclaimer: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/disclaimer.json`
                    )
                ).default,
            },
            fastMovesList: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/fastMovesList.json`
                    )
                ).default,
            },
            fastMovesListPvP: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/fastMovesListPvP.json`
                    )
                ).default,
            },
            home: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/home.json`
                    )
                ).default,
            },
            move: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/move.json`
                    )
                ).default,
            },
            pokedex: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/pokedex.json`
                    )
                ).default,
            },
            pokemonPage: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */
                        `../messages/${locale}/pokemonPage.json`
                    )
                ).default,
            },
            regionAndTypeList: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/regionAndTypeList.json`
                    )
                ).default,
            },
            shinyChecklist: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/shinyChecklist.json`
                    )
                ).default,
            },
            typeChart: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/typeChart.json`
                    )
                ).default,
            },
            whosThatPokemon: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/whosThatPokemon.json`
                    )
                ).default,
            },
            pokemonTyping: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/pokemonTyping.json`
                    )
                ).default,
            },
            navigationLinks: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/navigationLinks.json`
                    )
                ).default,
            },
            countersPage: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/countersPage.json`
                    )
                ).default,
            },
            pokemonIvChartPage: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */
                        `../messages/${locale}/pokemonIvChartPage.json`
                    )
                ).default,
            },
            pokemonMovesPage: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */

                        `../messages/${locale}/pokemonMovesPage.json`
                    )
                ).default,
            },
            evolutionChartComponent: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */
                        `../messages/${locale}/evolutionChartComponent.json`
                    )
                ).default,
            },
            ivChartSpecialEncounters: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */
                        `../messages/${locale}/ivChartSpecialEncounters.json`
                    )
                ).default,
            },
            moveCard: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/moveCard.json`
                    )
                ).default,
            },
            typeDescriptions: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/typeDescriptions.json`
                    )
                ).default,
            },
            countersComponent: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/countersComponent.json`
                    )
                ).default,
            },
            pokemonPvpPage: {
                ...(
                    await import(
                        /* webpackMode: "lazy-once" */ `../messages/${locale}/pokemonPvpPage.json`
                    )
                ).default,
            },
        },
    };
});
`

webpackMode doesn't make any difference, but removing messages from this configuration makes a difference. There is nothing in my project saying that messages should be included in this file, but Next.JS is still including it! If you don't believe me, check this out.

Verification that this is being loaded:

- I've used webpack's [magic comments](https://webpack.js.org/api/module-methods/) to force webpack to bundle the i18n configuration file under the name webpackChunkName: **"all-i18n-data"**
- 
- I've searched for that chunk name in my .next folder, and found it fetched in webpack-5626e5b0ee7d32f5.js bundle
 ![Screenshot 2024-01-25 at 13 22 40](https://github.com/amannn/next-intl/assets/1139507/96fdd8db-51c2-4106-a830-558098f53b56)

- The webpack-5626e5b0ee7d32f5.js bundle is used in the middleware-build-manifest.json 

![Screenshot 2024-01-25 at 13 23 18](https://github.com/amannn/next-intl/assets/1139507/6988d6a4-61c4-49a7-b275-6d62b6dc5e8d)

This is directly impacting the size of middleware.js, and introducing a massive performance penalty to anyone using next-intl and Next.JS middleware.ts. I don't think you can include the messages in this way, you need to remove them from request config when a middleware is calling your getRequestConfig method. 

Or at least provide a way to know who is calling it, so that we as users of your library can load the messages based on the caller.

**Comment by apavlinovic** [comment]
To add to this issue, we’ve noticed that the getRequestConfig is hit even when API routes are called, which is quite insane. We’ve noticed errors in our log due to a missing check if the locale exists in the list of locales, and we think it backtracks to api route calls!

**Comment by amannn** [comment]
I unfortunately don't see the content from `i18n.ts` you've posted above in the reproduction you've mentioned at https://github.com/t2pellet/tenzin.live/blob/next/src/i18n.ts. Is this the app where you're see the issue?

Here's btw. an example build output from `example-app-router` from this repo, where the middleware has a reasonable size:

![Screenshot 2024-01-29 at 07 46 45](https://github.com/amannn/next-intl/assets/4038316/92a1c074-6887-4ca6-96f3-b8d465ee0f2b)

You might want to compare your implementation with that one.

To continue here, we'd need a reliable reproduction where the issue is visible.

**Comment by polly3d** [comment]
I had the same problem. My language file is very large. Each file is larger than 1M. So it's really big in middleware. Here's the screenshot:

![Image](https://github.com/user-attachments/assets/88e08230-d7d9-4a80-8d87-1325acee8804)

All my configurations are the same as in the documentation. [docs](https://next-intl.dev/docs/getting-started/app-router/with-i18n-routing)

**Comment by apavlinovic** [comment]
@polly3d are you using a ... (spread) operator in your configuration? That was the issue for me

**Comment by polly3d** [comment]
Which configuration?
Here's the configuration in i18n folder:
```js
// request.ts
import { getRequestConfig } from "next-intl/server";
import { routing } from "./routing";

export default getRequestConfig(async ({ requestLocale }) => {
  // This typically corresponds to the `[locale]` segment
  let locale = await requestLocale;

  // Ensure that a valid locale is used
  if (!locale || !routing.locales.includes(locale as any)) {
    locale = routing.defaultLocale;
  }

  return {
    locale,
    messages: (await import(`../locales/${locale}.json`)).default,
  };
});

```
```js
// routing.ts
import { defineRouting } from "next-intl/routing";
import { createNavigation } from "next-intl/navigation";

export const routing = defineRouting({
  // A list of all locales that are supported
  locales: ["en", "es"],
  localePrefix: "as-needed",
  // Used when no locale matches
  defaultLocale: "en",
});

// Lightweight wrappers around Next.js' navigation APIs
// that will consider the routing configuration
export const { Link, redirect, usePathname, useRouter, getPathname } =
  createNavigation(routing);

```

The middleware:
```js
import createMiddleware from "next-intl/middleware";
import { routing } from "./i18n/routing";

export default createMiddleware(routing);

export const config = {
  matcher: [
    // Skip Next.js internals and all static files, unless found in search params
    "/((?!_next|monitoring|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest|xml|txt)).*)",
    // Always run for API routes
    "/(api|trpc)(.*)",
  ],
};
```

Here's the screenshot of the translation files:

![Image](https://github.com/user-attachments/assets/fe57277d-0b1f-4b34-86eb-c9b86556b891)
