### ISSUE TITLE
[Docs]: middleware with jwt token from backend services

### ISSUE THREAD

**Issue by ehsanrezaeee** [amannn/next-intl#820]
### Describe the problem

when i am trying to use jwt token that i receive from my backend golang and set them in cookies, i use Next js middleware to protect my routes. however there is a missing docs about using cookie authorization and redirecting user to specific route using **NextResponse.redirect()** with next intl and its middleware

invoking NextResponse.redirect(new URL()) wont redirect users

**Comment by amannn** [comment]
Closing in favor of the additional discussion you've opened: https://github.com/amannn/next-intl/discussions/821
