### ISSUE TITLE
NEXT_LOCALE cookie has value "undefined" when navigated through useRouter without passed locale as argument

### ISSUE THREAD

**Issue by MatejStojanovicc** [amannn/next-intl#826]
### Description

When navigating through screens using useRouter.push (localePrefix set to "never"), if locale object is not passed as argument, NEXT_LOCALE cookie has value **undefined** when landing on navigated page. If user changes to non-default language and navigates to page -> language will be changed to default, since NEXT_LOCALE has value undefined.

Use router navigation to test page:
![image](https://github.com/amannn/next-intl/assets/98949392/3f3ebb95-8da9-40b3-bcb0-745577d39735)

Request headers that shows NEXT_LOCALE cookie has value of undefined:
![image](https://github.com/amannn/next-intl/assets/98949392/740138e7-becd-498b-b1c2-f1d9a985cf43)

### Video reproduction
[use-router-bug.webm](https://github.com/amannn/next-intl/assets/98949392/8d512d68-4ee7-44b4-844a-ea84242e5e15)

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

Codesandbox: https://codesandbox.io/p/devbox/flamboyant-wozniak-rd3zcl
Vercel: https://use-router-bug-nine.vercel.app/
Github: https://github.com/MatejStojanovicc/use-router-bug

### Reproduction description

Steps to reproduce
1. Open app on [vercel](https://use-router-bug-nine.vercel.app/) or [codesandbox]( https://codesandbox.io/p/devbox/flamboyant-wozniak-rd3zcl) 
2. Install dependencies (pnpm install) and run dev server (pnpm dev) - if using codesandbox, it will automatically start
3. Open http://localhost:3000/ in browser - it will open / page. **If using codesandbox, ctrl+click localhost url to open in new tab, since Codesandbox blocks Cookies):** 
![image](https://github.com/amannn/next-intl/assets/98949392/625a1428-9ffd-46b5-bc57-c584d6b5786e)
4. Open network tab to inspect network activity
5. Click Navigate to Test page
6. Observe Cookie header under "Request headers" 
7. Go to homepage, try to change language by clicking either Change to EN or Change to DE -> same thing happens

### Expected behaviour

NEXT_LOCALE cookie is passed even when locale object is not passed as second argument in useRouter push method. Passing locale (or making a wrapper around useRouter which will append locale on every method) might be a tedious and unnecessary procedure.

```
  const router = useRouter();
  const locale = useLocale();
      <span
        onClick={() =>
          router.push("/test", {
            locale,
          })
        }
      >
        Navigate to Test page
      </span>
```

**Comment by amannn** [comment]
Hey, thanks for the great bug report—this was definitely an oversight! This will be fixed in https://github.com/amannn/next-intl/pull/828.
