### ISSUE TITLE
Spliting messages in different files loses Typescript safety check

### ISSUE THREAD

**Issue by GasparAdragna** [amannn/next-intl#832]
### Description

We decided to split the messages on our project as it was getting to big to handle, but by doing so we are getting errors everywhere because this line in the global.d.ts is wrong now.

`type Messages = typeof import("./messages/es.json");`
`declare interface IntlMessages extends Messages {}`

What is the correct way to use multiple files and dont lose typescript safety check?

Thanks

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-zcymvq

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

When using multiple files and following the docs, it should not lose typescriot safety check

**Comment by SalahAdDin** [comment]
@GasparAdragna I was about to report the same issue.

**Comment by SalahAdDin** [comment]
### Description

We decided to work with this package to handle the website internationalization.

We implemented [splitting files](https://next-intl-docs.vercel.app/docs/usage/configuration#messages) to have it more organized, It follows like this:
![image](https://github.com/amannn/next-intl/assets/5034215/57138a5b-3505-47eb-9296-7e8fcb0f51cf)

We wrote the types and the configuration as the documentations says:
```ts
type Messages = typeof import("./src/locales/en/home.json");

declare type IntlMessages = object & Messages;
``` 
`globals.d.ts`

```ts
import { notFound } from "next/navigation";

import { getRequestConfig } from "next-intl/server";

import { isValidLocale } from "./common/types";

export default getRequestConfig(async ({ locale }) => {
  if (!isValidLocale(locale)) notFound();

  const messages = {
    home: { ...(await import(`./locales/${locale}/home.json`)).default },
  };

  return {
    messages,
  };
});
``` 
`i18n.ts`

As you can see, importing files dynamically produces an error type:
```
Unsafe assignment of an `any` value.
Unsafe member access .default on an `any` value.
```

How can we solve it?

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/devbox/next-intl-bug-template-app-forked-v8pgz2

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Go to the configuration file, i. e., `i18n.ts`
3. See error: 
```
Unsafe assignment of an `any` value.
Unsafe member access .default on an `any` value.
```


### Expected behaviour

It should not give any error when linting types.

**Comment by GasparAdragna** [comment]
I have my messages declared in `i18n.ts` as follows:

<img width="679" alt="image" src="https://github.com/amannn/next-intl/assets/38141596/d16653e9-a5d5-4837-9143-dcc741c28317">

And it does work but i lost all type check safety:

<img width="1078" alt="image" src="https://github.com/amannn/next-intl/assets/38141596/e2ead5e3-7f63-48a7-9b39-5ed04c168c3c">

**Comment by amannn** [comment]
The answer here depends on how you merge the messages.

**Merge into a single namespace**

```tsx
const messages = {
  ...(await import(`../../messages/${locale}/login.json`)).default,
  ...(await import(`../../messages/${locale}/dashboard.json`)).default
}
```

```tsx
type Messages = typeof import('./messages/login.json') &
  typeof import('./messages/dashboard.json');
declare interface IntlMessages extends Messages {}
```

**Merge with separate namespaces**

```tsx
const messages = {
  login: (await import(`../../messages/${locale}/login.json`)).default,
  dashboard: (await import(`../../messages/${locale}/dashboard.json`)).default
}
```

```tsx
type Messages = {
  login: typeof import('./messages/login.json'),
  dashboard: typeof import('./messages/dashboard.json')
}
declare interface IntlMessages extends Messages {}
```

**Comment by SalahAdDin** [comment]
> The answer here depends on how you merge the messages.
> 
> **Merge into a single namespace**
> 
> ```tsx
> const messages = {
>   ...(await import(`../../messages/${locale}/login.json`)).default,
>   ...(await import(`../../messages/${locale}/dashboard.json`)).default
> }
> ```
> 
> ```tsx
> type Messages = typeof import('./messages/login.json') &
>   typeof import('./messages/dashboard.json');
> declare interface IntlMessages extends Messages {}
> ```
> 
> **Merge with separate namespaces**
> 
> ```tsx
> const messages = {
>   login: (await import(`../../messages/${locale}/login.json`)).default,
>   dashboard: (await import(`../../messages/${locale}/dashboard.json`)).default
> }
> ```
> 
> ```tsx
> type Messages = {
>   login: typeof import('./messages/login.json'),
>   dashboard: typeof import('./messages/dashboard.json')
> }
> declare interface IntlMessages extends Messages {}
> ```

Isn't it duplicating code?

**Comment by amannn** [comment]
One imports a type, the other the actual JSON—so nope, no duplication! Hope this helps.

**Comment by SalahAdDin** [comment]
@amannn It does not work:
![image](https://github.com/amannn/next-intl/assets/5034215/fac098d3-efc7-4d7c-bc41-0d2001278b24)

**Comment by amannn** [comment]
The errors you're seeing are stylistic warnings reported by ESLint rules—the solution works regardless. If you're not sure what those errors mean, I'd suggest turning the relevant rules off.

See also "Marie Kondo Your Lint Config" in this article: https://overreacted.io/writing-resilient-components/

**Comment by SalahAdDin** [comment]
> The errors you're seeing are stylistic warnings reported by ESLint rules—the solution works regardless. If you're not sure what those errors mean, I'd suggest turning the relevant rules off.
> 
> See also "Marie Kondo Your Lint Config" in this article: https://overreacted.io/writing-resilient-components/

I can fix the issues on the global types, but again, the types on splitting files are not working.

**Comment by SalahAdDin** [comment]
> The errors you're seeing are stylistic warnings reported by ESLint rules—the solution works regardless. If you're not sure what those errors mean, I'd suggest turning the relevant rules off.
> 
> See also "Marie Kondo Your Lint Config" in this article: https://overreacted.io/writing-resilient-components/

@amannn They are typescript linting errors, they should not be happening.

**Comment by SalahAdDin** [comment]
> The answer here depends on how you merge the messages.
> 
> **Merge into a single namespace**
> 
> ```tsx
> const messages = {
>   ...(await import(`../../messages/${locale}/login.json`)).default,
>   ...(await import(`../../messages/${locale}/dashboard.json`)).default
> }
> ```
> 
> ```tsx
> type Messages = typeof import('./messages/login.json') &
>   typeof import('./messages/dashboard.json');
> declare interface IntlMessages extends Messages {}
> ```
> 
> **Merge with separate namespaces**
> 
> ```tsx
> const messages = {
>   login: (await import(`../../messages/${locale}/login.json`)).default,
>   dashboard: (await import(`../../messages/${locale}/dashboard.json`)).default
> }
> ```
> 
> ```tsx
> type Messages = {
>   login: typeof import('./messages/login.json'),
>   dashboard: typeof import('./messages/dashboard.json')
> }
> declare interface IntlMessages extends Messages {}
> ```

@GasparAdragna Did this fix the issue for you?
