### ISSUE TITLE
[Docs]: next.config.js Unexpected token 'export'`

### ISSUE THREAD

**Issue by MateuszWasik** [amannn/next-intl#837]
### Link to page

https://next-intl-docs.vercel.app/docs/getting-started/app-router

### Describe the problem

Hello,

I encountered an issue while following the `Getting Started with App Router` tutorial in my Next.js application, specifically in the step involving the configuration of the `next.config.js` file. I believe there is an error in the tutorial that led to a runtime error during `npm run dev`.

Here's a brief description of the problem:

**Error Message**: I received the following error message during development:

`SyntaxError: Unexpected token 'export'`

**Code in Question:** The error was related to the last line of the code provided in the tutorial, as shown below:

```
const createNextIntlPlugin = require('next-intl/plugin');

const withNextIntl = createNextIntlPlugin();

/** @type {import('next').NextConfig} */
const nextConfig = {};

export default withNextIntl(nextConfig);
```

**Solution**: To resolve the issue, I had to modify the code to use CommonJS module syntax as follows:

```
const createNextIntlPlugin = require('next-intl/plugin');

const withNextIntl = createNextIntlPlugin();

/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = withNextIntl(nextConfig);
```

I recommend updating the tutorial documentation to use CommonJS syntax to prevent similar issues for other users who might face this problem. This will ensure a smoother experience for those following the tutorial.

Once it's accepted I am willing to create a PR with a fix.

**Comment by amannn** [comment]
Hey @MateuszWasik, you're absolutely right, thanks for pointing this out! I've addressed this in #838.

**Comment by MateuszWasik** [comment]
Hello @amannn ! Thanks :) Have a great day!

**Comment by amannn** [comment]
Thanks, same to you @MateuszWasik! 🙂
