### ISSUE TITLE
Support for returnObjects

### ISSUE THREAD

**Issue by prabu-ssb** [amannn/next-intl#84]
**Current Behaviour**
At the moment trying to resolve a key which has an array as its value throws a MISSING_MESSAGE (plus INSUFFICIENT_PATH) error. 

**Feature Requested**
Support for `returnObjects: true`. At its most basic level, arrays, but will be great if it can support objects too. If the message bundle has --

```json
{
  "items": [
    "item1",
    "item2"
  ]
}
```

then it should be possible to retrieve the list of translations for the key

```react
const t = useTranslations('bundle');
const items = t('items',  { returnObjects: true });
// => [ "item1", "item2" ]
```

This feature is provided currently by next-i18next, next-translate etc., but next-intl seems to be much easier to setup and use. Something like this would be very handy for large scale applications like ours.

**Comment by amannn** [comment]
Hi @prabu-ssb,

thanks for your report! You can use [the `t.raw` API](https://next-intl-docs.vercel.app/docs/usage/messages#raw-messages) for this.
