### ISSUE TITLE
Changing language not working with parallel and intercepted routes

### ISSUE THREAD

**Issue by MatejStojanovicc** [amannn/next-intl#841]
### Description
Trying to change language on a route, which is intercepted, doesn't apply new language throughout the app and shows parallel route content. NEXT_LOCALE cookie value is updated correctly, but it is not appended in application -> locale stays the same.

Folder structure with parallel & intercepted route:
![image](https://github.com/amannn/next-intl/assets/98949392/15689e6d-91cf-43ab-a4f5-46a73312bc72)

Changing language on subroute [/test/[id]](https://next-intl-intercepted-parallel-route-bug.vercel.app/test/12) when languge is EN results in triggered paralell route content:

![image](https://github.com/amannn/next-intl/assets/98949392/a11c3bcf-730b-4ed6-8b45-54d4b43ddaba)

After closing modal, language is not changed, but NEXT_LOCALE value is updated:

![image](https://github.com/amannn/next-intl/assets/98949392/528dbd6f-df00-48e0-b313-58ec3d99d343)

### Video reproduction
[intercepted-route-bug.webm](https://github.com/amannn/next-intl/assets/98949392/e8fe3c90-89ff-4297-9f2e-b972a25b255c)

### Mandatory reproduction URL (CodeSandbox or GitHub repository)
Codesandbox: [https://codesandbox.io/s/github/MatejStojanovicc/next-intl-intercepted-parallel-route-bug](url)
Vercel: [https://next-intl-intercepted-parallel-route-bug.vercel.app/](url)
Github: [https://github.com/MatejStojanovicc/next-intl-intercepted-parallel-route-bug](url)

### Reproduction description

1. Open app on [vercel](https://next-intl-intercepted-parallel-route-bug.vercel.app/) or [codesandbox](https://codesandbox.io/s/github/MatejStojanovicc/next-intl-intercepted-parallel-route-bug)
2. Install dependencies (pnpm install) and run dev server (pnpm dev) - if using codesandbox, it will automatically start
3. Open http://localhost:3000/ in browser - it will open / page. **If using codesandbox, ctrl+click localhost url to open in new tab, since Codesandbox blocks cookies, so NEXT_LOCALE won't work anyway)**: 
![image](https://github.com/amannn/next-intl/assets/98949392/efa7d8b4-60b4-4eb5-98f6-4c9dc5a7833e)
4. Open Test details page, /test/12, for example: [https://next-intl-intercepted-parallel-route-bug.vercel.app/test/12](url)
5. Open network tab to inspect network activity
6. Change the app to another language -> if current locale is EN -> click Change to DE and vice versa
7. Observer NEXT_LOCALE cookie value under Application -> Cookies
8. Close modal (click anywhere outside it)
9. After this. **any further attempt to change the language will do nothing** on /test[id]

Results: Changing language shows parallel route @modal content and language is not changed in app, even though NEXT_LOCALE cookie has appended new language value correctly.

### Expected behaviour
Language is changed throughout app correctly and parallel route content (Modal) is not showed when changing route on /test[id]

**Comment by amannn** [comment]
This might be related to https://github.com/amannn/next-intl/issues/255. Parallel and intercepted routes unfortunately were quite buggy for a longer period in Next.js, not sure how stable they are now.

Are you able to isolate if this is a Next.js or a `next-intl` issue?

**Comment by MatejStojanovicc** [comment]
Yea, they were definitely buggy (even unusable for quite time).
I've spent last two days researching and trying to isolate the problem, but unfortunately, without any luck. Only thing I've concluded is when I remove parallel route and use classic /test[id] subroute and try to change language -> it works. 

But interesting thing is, why does NEXT_LOCALE cookie value change properly, but isn't appended on app (i.e. re-render doesn't happen and locale stays the same). Could it be some problem between syncing cookie and locale values?  
And the only time intercepted route's content "pops" in details screen is when trying to change language, any other state change won't trigger that.

**Comment by amannn** [comment]
Right, I see!

> But interesting thing is, why does NEXT_LOCALE cookie value change properly

That's likely related to https://github.com/amannn/next-intl/pull/790.

**Comment by MatejStojanovicc** [comment]
Hmmm could be, yes. So you're saying it will be deployed in next version or it is already up? Tried updating to 3.6.0-alpha.1
and this still happens

**Comment by amannn** [comment]
That change was already deployed in [3.4.5](https://github.com/amannn/next-intl/blob/main/CHANGELOG.md#345-2024-01-19). What I tried to say is that I think this is the explanation for why the cookie value is changed as expected, even if Next.js doesn't update.

**Comment by TommySorensen** [comment]
@amannn With Next.js `14.1.1-canary.52` and next-intl `3.7.0` currently nested routes in does not work with next-intl. The latest canary version of nextjs has a lot of parallel routes fixes which i need, but the following error is caused somehow by next-intl on subroutes. I will open a new issue with this asap

<img width="1008" alt="image" src="https://github.com/amannn/next-intl/assets/4134473/bf8c029e-410c-4022-a29b-a88d1323f062">
