### ISSUE TITLE
[Docs]: Revalidation on translated path

### ISSUE THREAD

**Issue by LouisCuvelier** [amannn/next-intl#846]
### Describe the problem

Hi,

Versions concerned :
```
"next": "14.1.0",
"next-intl": "3.5.4",
```

I'm using the [localized pathnames strategy ](https://next-intl-docs.vercel.app/docs/routing/navigation#localized-pathnames) to do the routing. Here's an example : 
```
.
└── [locale]/
    └── news/
        └── [slug]
```
In `navigation.ts`, localized path is set like this : 
```js
{
  '/news/[slug]': {
    en: '/news/[slug]',
    fr: '/infos/[slug]',
    it: '/notizia/[slug]',
  },
}
```

Theses pages are generated at build time thanks to [`generateStaticParams()`](https://nextjs.org/docs/app/api-reference/functions/generate-static-params). But, when I'm trying to revalidate the page with [`revalidatePath('/fr/infos/some-url')`](https://nextjs.org/docs/app/api-reference/functions/revalidatePath) it doesn't work.

After a lot of investigation, I came to this result :

For pages that are statically generated : 
- This doesn't work : `revalidatePath('/fr/infos/some-url')`
- This does work : `revalidatePath('/fr/news/some-url')`

For pages that are dynamic : 
- This doesn't work : `revalidatePath('/fr/news/some-url')`
- This does work : `revalidatePath('/fr/infos/some-url')`

I found this by looking at the `prerender-manifest.json` generated after a Next's build. I tested to revalidate the `dataRoute` and it worked.
```json
{
    "/fr/news/article-french": {
      "experimentalBypassFor": [
        { "type": "header", "key": "Next-Action" },
        {
          "type": "header",
          "key": "content-type",
          "value": "multipart/form-data"
        }
      ],
      "initialRevalidateSeconds": false,
      "srcRoute": "/[locale]/news/[slug]",
      "dataRoute": "/fr/news/article-french.rsc"
    },
}
```

Maybe it's worth to add something in the doc about how revalidation is working when we are using localized folder names ?
Or maybe there is a fix to do in code ?

**Comment by amannn** [comment]
That's an interesting point, thanks for bringing this up! 

Some background: Localized pathnames are implemented via rewrites at the middleware level and delegate to an internal pathname. Are you saying that `revalidatePath` works either at an internal or external pathname based on if the page was dynamically rendered? This sounds like an inconsistency, I'm wondering if this should be addressed on the Next.js side. Do you know if there are existing reports on the Next.js side?

But in regard to your question, I think an expandable section at the bottom of https://next-intl-docs.vercel.app/docs/routing/middleware#localizing-pathnames would be helpful that covers if users need to invalidate internal or external URLs. Would you be interested in adding this? (see the "Edit this page" link in the bottom right corner)

**Comment by LouisCuvelier** [comment]
Thanks for the background explanation. With this in mind, it's maybe related to this issue : https://github.com/amannn/next-intl/issues/846. So, yes, It looks like it is effectively a Next issue.

Sure for the doc, I'll edit it when I have some time in the week 😉
