### ISSUE TITLE
Requests to `.next` files are redirected to `.next/[locale]` causing 404 not found

### ISSUE THREAD

**Issue by Aperrix** [amannn/next-intl#851]
## Description
I'm trying to use next-intl with Primereact but the middleware redirect requests to `.next` files (302 redirects) to `.next/[locale]` path (who turn into 404 not found).

Maybe it's just a matcher problem ? I don't really know if it's a bug or a misunderstanding from me.

![image](https://github.com/amannn/next-intl/assets/26674548/80ab191c-5fa0-4407-a40e-94b4138f10f0)

## Config
- Packages
```json
"next"          : "14.1.0",
"next-intl"     : "^3.5.4",
"primereact"    : "^10.4.0",
"react"         : "^18.2.0",
"react-dom"     : "^18.2.0",
```
- Middleware
```ts
export default createMiddleware({
  // A list of all supported locales
  locales: LOCALES,

  // Used when no locale matches
  defaultLocale: DEFAULT_LOCALE,

  // Use "accept-language" header
  localeDetection: true,
})

const CONFIG = {
  matcher: [
    // Enable a redirect to a matching locale at the root
    "/",

    // Set a cookie to remember the previous locale for
    // all requests that have a locale prefix
    `/(${LOCALES.join("|")})/:path*`,

    // Enable redirects that add missing locales
    // (e.g. `/pathnames` -> `/en/pathnames`)
    "/((?!_next|_vercel|.*\\..*).*)",
  ],
}

export {
  CONFIG as config,
}
```

**Comment by V1RE** [comment]
Checkout the [Matcher config](https://next-intl-docs.vercel.app/docs/routing/middleware#matcher-config) part of the docs, if you open the "Can I avoid hardcoding the locales in the matcher config?" thing it shows you your current setup won't work

**Comment by Aperrix** [comment]
> Checkout the [Matcher config](https://next-intl-docs.vercel.app/docs/routing/middleware#matcher-config) part of the docs, if you open the "Can I avoid hardcoding the locales in the matcher config?" thing it shows you your current setup won't work

It work like a charm, thank you ! 😍
