### ISSUE TITLE
Link component that is not 'use client'

### ISSUE THREAD

**Issue by rijk** [amannn/next-intl#855]
### Is your feature request related to a problem? Please describe.

I stumbled upon this because [the docs don't mention](https://next-intl-docs.vercel.app/docs/routing/navigation#link) that `<Link>` (more specifically: [`<BaseLink>`](https://github.com/amannn/next-intl/blob/main/packages/next-intl/src/navigation/shared/BaseLink.tsx)) is `'use client'` and thus requires a `NextIntlClientProvider`.

Having to wrap content in a provider every time I want to use a localized link (most of my tree is server rendered otherwise), is a bit clunky.

### Describe the solution you'd like

I haven't looked into the code deeply, but at first glance I don't think the client functionality is actually needed to provide the core functionality of swapping the href, especially since most of the hooks this package relies on are already built to work on the server.

### Describe alternatives you've considered

It would be good if this is not possible (or in the mean time) to at least update the docs to mention this requirement.

**Comment by amannn** [comment]
Can you share the code that caused an issue for you? `Link` shouldn’t require the presence of the provider.

**Comment by rijk** [comment]
Basically just something like this:

```tsx

export default async function Page() {
  return (
    <div>
      <Link
        href={{
          pathname: '/products/[collection]',
          params: { collection: 'face' },
        }}
      >
        Test
      </Link>
    </div>
  )
}
```

Gives me the following error:

<img width="537" alt="image" src="https://github.com/amannn/next-intl/assets/159500/f5214e5c-14fb-4539-bd59-37f71cf12a5e">

**Comment by rijk** [comment]
I think it's because BaseLink is marked `use client`, that the hooks like `useLocale` are automatically switched to their `react-client` counterparts (which use context).

**Comment by amannn** [comment]
Can you share a reproduction using [the bug report template](https://github.com/amannn/next-intl/issues/new?assignees=&labels=bug%2Cunconfirmed&projects=&template=bug_report.yml)? [The App Router example](https://next-intl-example-app-router.vercel.app/en) doesn't use `NextIntlClientProvider` but `Link` works in this app.

**Comment by rijk** [comment]
I am unable to:

<img width="602" alt="image" src="https://github.com/amannn/next-intl/assets/159500/3870e84a-fa5d-4685-85eb-612b1a114b67">

**Comment by amannn** [comment]
That CSB pricing change is really unfortunate. Additionally, StackBlitz [doesn't support all Next.js APIs](https://twitter.com/sulco/status/1757378234964906345), therefore I've now removed all references to CSB and added a minimal [App Router example](https://github.com/amannn/next-intl/tree/main/examples/example-app-router-minimal) to this repo which can be used for reproductions now.

Hope this helps!

**Comment by rijk** [comment]
Yes thanks, I've cloned the example am trying to reproduce — I see it's working fine in the example so I'm a bit puzzled why it's not in my app.

**Comment by rijk** [comment]
By the way, this is a wonderful library!

**Comment by rijk** [comment]
Ah!! I found it :D 

The reason was in my app the param is called `[lang]` instead of `[locale]`, I did not realize that matters even if you call `unstable_setRequestLocale()`.

**Comment by amannn** [comment]
Ah I see, glad you figured it out! 🙌
