### ISSUE TITLE
Optional translations

### ISSUE THREAD

**Issue by amannn** [amannn/next-intl#88]
**Is your feature request related to a problem? Please describe.**

It would be good if some translations could be marked as optional, so no error is reported.

**Describe the solution you'd like**

Either an API to ask if a translation is available to conditionally render it, or an API to suppress the error in this case.

Probably `t.has(…)` would be the best option here as it can be used to check for translations before using either `t`, `t.rich`, `t.raw` etc.

**Describe alternatives you've considered**

Adding empty strings in the messages if the label is not relevant for a particular scenario (i.e. `"message": ""`).

If you're using [the VSCode integration for `next-intl` via i18n Ally](https://next-intl-docs.vercel.app/docs/workflows/vscode-integration), you can add empty messages for new keys via `"i18n-ally.keepFulfilled": true`.

I'm currently unsure if `next-intl` needs built-in support for this, or if it can be solved with tooling. I guess the question is: "Is this translation missing currently or is it not intended at all?".

This could also be solved via a combination of [`useMessages`](https://next-intl-docs.vercel.app/docs/usage/configuration#retrieve-global-configuration) and `lodash/get`, e.g. in a custom hook.

**Comment by Crayon-ShinChan** [comment]
Can we have these two features:
1. If the translation does not exist, fallback to see the defaultLocale json file and use the word there
2. Fallback to a specific language not always defaultLocale, If the translation from `zh-TW` does not exist, fallback to show words in `zh`

**Comment by Crayon-ShinChan** [comment]
> Can we have these two features:
> 
> 1. If the translation does not exist, fallback to see the defaultLocale json file and use the word there
> 2. Fallback to a specific language not always defaultLocale, If the translation from `zh-TW` does not exist, fallback to show words in `zh`

I use this code to implement the logic:
```ts
import merge from "deepmerge";
import { getRequestConfig } from "next-intl/server";

export default getRequestConfig(async ({ locale }) => {
  const localeMessages = (await import(`./messages/${locale}.json`)).default;
  const localeGeneralMessages =
    locale.split("-").length > 1
      ? (await import(`./messages/${locale.split("-")[0]}.json`)).default
      : {};
  const defaultMessages = (await import(`./messages/en.json`)).default;
  const messages = merge.all([
    defaultMessages,
    localeGeneralMessages,
    localeMessages,
  ]);

  return {
    messages,
  };
});
```

It can run successfully, but give me the type warning for `async ({ locale }) `
```
Argument of type '({ locale }: GetRequestConfigParams) => Promise<{ messages: object; }>' is not assignable to parameter of type '(params: GetRequestConfigParams) => RequestConfig | Promise<RequestConfig>'.
  Type 'Promise<{ messages: object; }>' is not assignable to type 'RequestConfig | Promise<RequestConfig>'.
    Type 'Promise<{ messages: object; }>' is not assignable to type 'Promise<RequestConfig>'.
      Type '{ messages: object; }' is not assignable to type 'RequestConfig'.
        Types of property 'messages' are incompatible.
          Type 'object' is not assignable to type 'AbstractIntlMessages'.
            Index signature for type 'string' is missing in type '{}'.ts(2345)
```
anyone know how to solve this?

**Comment by amannn** [comment]
Merging messages from another locale as a fallback is absolutely fine and also mentioned in [the messages docs](https://next-intl-docs.vercel.app/docs/configuration#messages) ("How can I use messages from another locale as fallbacks?").

**Comment by alejandroTecDam** [comment]
> > Can we have these two features:
> > 
> > 1. If the translation does not exist, fallback to see the defaultLocale json file and use the word there
> > 2. Fallback to a specific language not always defaultLocale, If the translation from `zh-TW` does not exist, fallback to show words in `zh`
> 
> I use this code to implement the logic:
> 
> ```ts
> import merge from "deepmerge";
> import { getRequestConfig } from "next-intl/server";
> 
> export default getRequestConfig(async ({ locale }) => {
>   const localeMessages = (await import(`./messages/${locale}.json`)).default;
>   const localeGeneralMessages =
>     locale.split("-").length > 1
>       ? (await import(`./messages/${locale.split("-")[0]}.json`)).default
>       : {};
>   const defaultMessages = (await import(`./messages/en.json`)).default;
>   const messages = merge.all([
>     defaultMessages,
>     localeGeneralMessages,
>     localeMessages,
>   ]);
> 
>   return {
>     messages,
>   };
> });
> ```
> 
> It can run successfully, but give me the type warning for `async ({ locale }) `
> 
> ```
> Argument of type '({ locale }: GetRequestConfigParams) => Promise<{ messages: object; }>' is not assignable to parameter of type '(params: GetRequestConfigParams) => RequestConfig | Promise<RequestConfig>'.
>   Type 'Promise<{ messages: object; }>' is not assignable to type 'RequestConfig | Promise<RequestConfig>'.
>     Type 'Promise<{ messages: object; }>' is not assignable to type 'Promise<RequestConfig>'.
>       Type '{ messages: object; }' is not assignable to type 'RequestConfig'.
>         Types of property 'messages' are incompatible.
>           Type 'object' is not assignable to type 'AbstractIntlMessages'.
>             Index signature for type 'string' is missing in type '{}'.ts(2345)
> ```
> 
> anyone know how to solve this?

I've solved the issue like this, but I only have two elements, maybe you can do two steps
```
const messages = merge(defaultMessages, localeMessages);
```

**Comment by philipbjorge** [comment]
My usecase:

Our backend is returning a `State` (e.g. Washington, Oregon, etc.)
We will have translations for all of the common states.

However, it is possible that a new value comes down the line.
I would like to be able to show a translated key if its present, otherwise just fall back to displaying the value returned by the API.

---

As far as I can tell, this isn't supported by this library?

**Comment by amannn** [comment]
@philipbjorge Have you considered using [select](https://next-intl-docs.vercel.app/docs/usage/messages#selecting-enum-based-values) for this use case?

```
"state": "{state, select, WA {Washington} OR {Oregon} other {{state}}"
```

**Comment by philipbjorge** [comment]
Mmm interesting solution... We have 900 selections, so I feel like that string might become unwieldy. I think we might go with something like this since the key name is well-defined.

```
  const getTranslationWithFallback = (key: string, fallback: string) => {
    const translated = tc(key, false);
    if (translated.startsWith("common.")) {
      return fallback;
    }
    return translated;
  };

{getTranslationWithFallback(`biomes.${biome}`, biome)}
```

**Comment by 3li7u** [comment]
Hello there 
Does anyone know if we can define a default value for dynamic value variables
like in this example:
`"message": "Hello {name}!"` => `t('message', {name: 'Jane'}); // "Hello Jane!"`
Is it possible to provide a default value in case I don't pass the variable from t
`"message": "Hello {name=Jane}!"` => `t('message'); // "Hello Jane!"`

**Comment by alkorlos** [comment]
My usecase:

In the loop, are displayed several similar blocks with a title and description. Two of them have no description, which is by design and it is fine.
`t.has(...)` would be very useful in this case.

Thank you for your work!

**Comment by tholander** [comment]
I took the opportunity here to create a PR that implement a `t.has` function. I'm not really used to open PR on open source repositories so let me know if there's anything wrong

**Comment by amannn** [comment]
@tholander Awesome, thanks! Will have a look early next week.

**Comment by brunorafaeI** [comment]
I believe that the best solution for this problem, in addition to the proposal of t.has(), would be to add the possibility of passing a 'fallback' attribute. If it doesn't find a match, it would use the value provided in the fallback. This would solve many use cases, for example:

```ts
const t = useTranslations("Common")
const { id, columnWidth, columnType, ColumnTitle } = ColumnItem

t(`columns.${columnType}.title`, { fallback: ColumnTitle })
```

**Comment by amannn** [comment]
@brunorafaeI

> The only problem is when the user decides to change the column name and put it in English; they will always have the translated version!

That indeed sounds a bit brittle to me, I guess an explicit check of whether the user has provided a preference should be considered. Do you even need `t.has` for this use case?

```js
const title = ColumnTitle || t(`columns.${columnType}.title`);
```

Alternatively, you can also incorporate an additional fallback with `t.has`:

```js
const title = ColumnTitle || (
  t.has(`columns.${columnType}.title`)
    ? t(`columns.${columnType}.title`)
    : 'Fallback column title'
);
```

**Comment by brunorafaeI** [comment]
I will try to be more explicit, let's say I am receiving this data from the API:

> @brunorafaeI
> 
> > The only problem is when the user decides to change the column name and put it in English; they will always have the translated version!
> 
> That indeed sounds a bit brittle to me, I guess an explicit check of whether the user has provided a preference should be considered. Do you even need `t.has` for this use case?
> 
> ```js
> const title = ColumnTitle || t(`columns.${columnType}.title`);
> ```
> 
> Alternatively, you can also incorporate an additional fallback with `t.has`:
> 
> ```js
> const title = ColumnTitle || (
>   t.has(`columns.${columnType}.title`)
>     ? t(`columns.${columnType}.title`)
>     : 'Fallback column title'
> );
> ```

I will try to be more explicit, let's say I am receiving this data from the API :
```json
{
  "columns": [
    {
      "id": 1,
      "title": "Users",
      "width": "130px",
      "type": "users",
      "index": 0
    },
    {
      "id": 2,
      "title": "Period",
      "width": "203px",
      "type": "period",
      "index": 2
    },
    {
      "id": 3,
      "title": "Status",
      "width": "148px",
      "type": "status",
      "index": 1
    }
  ]
}
```
And the structure of my translation files corresponds to this here (fr.json):
```json
{
  "Common": {
    "columns": {
      "users": {
        "title": "{fallback, select, Users {Utilisateurs} other {{fallback}}}"
      },
      "period": {
        "title": "{fallback, select, Period {Période} other {{fallback}}}"
      },
      "status": {
        "title": "{fallback, select, Status {Status} other {{fallback}}}"
      }
    }
  }
}
```

If the user decides to change the column title to 'Personnes', it will work because 'Personnes' does not match 'Users', so what will be displayed will be what is in the fallback (title registered in the database). The problem arises when they decide to change it to English, for example, 'Users'; they will still see the translation instead of 'Users' because of the match.


PS: _Do you agree with me that what is being displayed to the user is the translation, that is, 'Utilisateurs', but the value registered in the database is 'Users'?_


### Example of use:
```ts
const t = useTranslations("Common")
const { id, columnWidth, columnType, ColumnTitle } = ColumnItem

t(`columns.${columnType}.title`, { fallback: ColumnTitle })
```

Therefore, I can't use this conditionnal : 
```ts
const title = ColumnTitle || t(`columns.${columnType}.title`);
```

The goal of using a 'fallback' attribute would also be to avoid the ternary conditional using 't.has()', but I believe the solution will be to introduce a new column in the database table (has_edited) to identify if there has been a change in the title. In this case, I will use the ternary, but at least like this:


```ts
const t = useTranslations("Common")
const { id, columnWidth, columnType, ColumnTitle, hasEdited } = ColumnItem

const  title = hasEdited ? ColumnTitle : t(`columns.${columnType}.title`)
```

This way, I won't need to adapt all my translation files to support the template with the select function:

```
"{fallback, select, Status {Status} other {{fallback}}}"
```

**Comment by amannn** [comment]
> I believe the solution will be to introduce a new column in the database table (has_edited) to identify if there has been a change in the title

That sounds reasonable to me too. This sounds more like a data problem to me than something that can be solved with a different API in `next-intl` as far as I can tell.
