### ISSUE TITLE
unstable_setRequestLocale does not work with generateStaticParams 

### ISSUE THREAD

**Issue by flagg2** [amannn/next-intl#891]
### Description

Greetings, 

I am currently using next-intl for i18n in my production app. I am trying to move from dynamic rendering to static/ssg where possible. I tried using unstable_setRequestLocale for this purpose, but no matter how much I try, I get the error

```
{
    description: "Page couldn't be rendered statically because it used 'headers'. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
    digest: 'DYNAMIC_SERVER_USAGE'
  }
```

I am using this minimal example to get the error

```
import { unstable_setRequestLocale } from "next-intl/server";
import { ReactNode } from "react";
import { Link } from "../../navigation";

type Props = {
  children: ReactNode;
  params: { locale: string };
};

export async function generateStaticParams() {
  return [{ lang: "en" }];
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: Props) {
  unstable_setRequestLocale(locale);
  return (
    <html lang={locale}>
      <head>
        <Link href="/test" />
        <title>next-intl-bug-repro-app-router</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
```

(The issue persists as long as there is the <Link /> component

Is this a bug, or am I doing something wrong? Thank you.

### Mandatory reproduction URL

https://github.com/flagg2/next-intl-ssg-issue

### Reproduction description

Steps to reproduce:
1. Clone my example repo and install deps
2. bun run build
3. bun run start
4. Navigate to any page

### Expected behaviour

No error is present

**Comment by amannn** [comment]
Briefly looking through your example, I see two issues:
1. `[locale]/page.tsx` doesn't use `unstable_setRequestLocale`
2. `[locale]/test/page.tsx` doesn't _call_ `unstable_setRequestLocale`

Can you fix that and verify it fixes the bug?

**Comment by flagg2** [comment]
Yes it indeed works and it therefore looks like I wasn't able to reproduce the behaviour of my production app. I am going to try harder to reproduce it.

**Comment by flagg2** [comment]
Hey, I managed to reproduce the bug.

 What is happening is that basically, I did not have ```unstable_setRequestLocale(locale);``` on all pages, just the ones I was currently trying to convert to SSG.

However, it seems like you get the error
```
{
    description: "Page couldn't be rendered statically because it used 'headers'. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
    digest: 'DYNAMIC_SERVER_USAGE'
}
```

 even if you navigate to a page that is setup correctly and you have a different page, which is not yet set up that way. It is probably not enough to be considered an issue, I just did not expect this behaviour.

If you would like to reproduce it, just navigate to /test, which is setup correctly and you get the error thanks to the incorrect setup of ```IndexPage```

**Comment by amannn** [comment]
You currently don't have `unstable_setRequestLocale` on `[locale]/page.tsx` but `generateStaticParams` in `[locale]/layout.tsx` tries to generate that page. So I'd say there's an inconsistent configuration in your reproduction, right?

As a side note, the link on your layout is wrong (I guess it should be `/`?).
