### ISSUE TITLE
Value of the "href" property lost in the Link component when I use a dynamic route.

### ISSUE THREAD

**Issue by DaywisonSilva** [amannn/next-intl#901]
### Description

When I use the "createLocalizedPathnamesNavigation" function, I can't obtain dynamic route inferences in the "Link" component.

![image](https://github.com/amannn/next-intl/assets/150825771/f669f2cd-b448-4348-917b-67c14d2170a5)
![image](https://github.com/amannn/next-intl/assets/150825771/5812884a-e26b-4727-a2dc-8b5fe7ebd560)

### Mandatory reproduction URL

https://github.com/DaywisonSilva/next-intl-bug-repro-app-router

### Reproduction description

Steps to reproduce:
1. Use createLocalizedPathnamesNavigation with a single dynamic route
2. export Link component from createLocalizedPathnamesNavigation 
3. See error: in href attribute you cannot see the dynamic pathname

### Expected behaviour

When i use "createLocalizedPathnamesNavigation" function is expected in href prop of Link component all dynamic and statics localized pathnames.

**Comment by DaywisonSilva** [comment]
see layout.tsx file

**Comment by amannn** [comment]
For dynamic params, you need to pass the `pathname` and the `params` via an object to `href`, as shown in [the docs for `Link`](https://next-intl-docs.vercel.app/docs/routing/navigation#link):

```tsx
<Link href={{
  pathname: '/checkout/[cartId],
  params: {cartId: '28283763'}
}}>
  Cart
</Link>
```

**Comment by DaywisonSilva** [comment]
@amannn when i extend Link props generetad by "createLocalizedPathnamesNavigation" the href prop still missing with dynamic params. 
How can i use ComponentProps utility type to extend all props, including "href"?
