### ISSUE TITLE
Allow only translated pathnames

### ISSUE THREAD

**Issue by amannn** [amannn/next-intl#904]
### Discussed in https://github.com/amannn/next-intl/discussions/902

<div type='discussions-op-text'>

<sup>Originally posted by **mnemosx** March  1, 2024</sup>
Hi!
Using your middeware with pathnames set up like this:
```js
const handleI18nRouting = createIntlMiddleware({
  locales,
  defaultLocale: SupportedLangs.LV,
  localeDetection: false,

  pathnames: {
    '/': '/',
    '/about': {
      lv: '/par-mums',
      ru: '/o-nas',
    },
    '/contacts': {
      lv: '/kontakti',
      ru: '/kontakti',
    },
    '/faq': {
      lv: '/jautajumi',
      ru: '/voprosi',
    },
  },
});
```
works really well when I'm trying to access translated paths like `http://localhost:3000/lv/jautajumi/` 🙌 

There is just one issue -- `http://localhost:3000/lv/faq/` remains accessible too! This is not ideal because there are duplicate pages from the SEO standpoint.

What I'd like to see is that only the translated `lv` and `ru` links are available, while the English versions that are used as directory names in the App router and as keys in code (`about`, `contacts`, `faq`, etc.) return 404. e.g.:

- `/ru/voprosi/` -> renders Russian content
- `/voprosi/` -> adds the default prefix which is lv so path `/lv/voprosi/` renders 404
- `/lv/jautajumi/` -> renders Latvian content
- `/jautajumi/` -> adds the default prefix which is `lv` and renders Latvian content
- `/lv/faq/` -> **renders 404**
- `/ru/faq/` -> **renders 404**
- `/faq/` -> either adds a default prefix which is `lv` and renders 404 or just **renders 404** right away  

Can this be done?

Adding my folder structure for reference in case it helps:
<img width="224" alt="Screenshot 2024-03-01 at 15 06 53" src="https://github.com/amannn/next-intl/assets/16293217/166cfb46-6e01-41f7-919d-0301cca9f240">
</div>

**Comment by RomainGueffier** [comment]
Hi, I also noticed this possible feature, in my projects I currently handle myself unwanted original directory paths with 301 redirections but looks like 404 is better.

I would like to contribute to this awesome project and try submit a PR if nobody already works on it. Disclaimer, I will not ship it fast as it is my first "real" contribution 😃.

Should it be an opt-in feature?

**Comment by amannn** [comment]
@RomainGueffier That would be fantastic, thanks for jumping in here! 🙌 

On a second thought, maybe a redirect would be the better choice. While we can return a 404 status code from the middleware, I think this will not pick up the `not-found` layout (needs to be verified). If that is case, a 302 redirect to the matched locale might be more appropriate.

> Should it be an opt-in feature?

I'd make it non-configurable. The behavior should only be applied when there are routes that are purely "internal", i.e. they don't match any external route that is localized.

You can start by adding a test in [the middleware test suite](https://github.com/amannn/next-intl/blob/main/packages/next-intl/test/middleware/middleware.test.tsx) and start looking into the source code from there.

Let me know if I can help with something!

**Comment by RomainGueffier** [comment]
@amannn Thank you for the middleware test suite, easier to start with it.
