### ISSUE TITLE
Router push loses locale with basePath 

### ISSUE THREAD

**Issue by Oberwaditzer** [amannn/next-intl#905]
### Description

If a `basePath` is configured in the `nextConfig` it gets lost with `router.push`. With a `Link` it works fine.

### Mandatory reproduction URL

https://codesandbox.io/p/devbox/great-jerry-s6ylgc

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. You should be now on` /base-path/de`
3. Click on Link
4. you are now on `/base-path/de/test-page`
5. go back
6. Click on Router Push
7. you are now on `/base-path/test-page`

### Expected behaviour

If using` router.push` in combination with `basePath` the locale should also be carried with.

**Comment by gentrith44belt** [comment]
+1

`redirect('/profile') ` it's not working with basePath config.

<img width="916" alt="image" src="https://github.com/amannn/next-intl/assets/143590367/56fc9bbe-2b48-47cc-bd3b-85c6a85466e8">

**Comment by amorinabelt** [comment]
> +1
> 
> `redirect('/profile') ` it's not working with basePath config.
> 
> <img alt="image" width="916" src="https://private-user-images.githubusercontent.com/143590367/310039083-56fc9bbe-2b48-47cc-bd3b-85c6a85466e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjc3NjYsIm5iZiI6MTcwOTYyNzQ2NiwicGF0aCI6Ii8xNDM1OTAzNjcvMzEwMDM5MDgzLTU2ZmM5YmJlLTJiNDgtNDdjYy1iZDNiLTg1YzZhODU0NjZlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwODMxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTMzNWVlODBkZGYxY2NhYTc1N2U1NjVlZDNmYmVjZGUyODU1YTQ1ODBkODg0YWMzODY5N2I0ODA0MDFkZmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yGFue6TBameqHjbIqFwjMYQnA1y2mXZcT3QfXJNjbnQ">

+1
