### ISSUE TITLE
Allow using dots in locales keys

### ISSUE THREAD

**Issue by jide** [amannn/next-intl#907]
I like to use english language as the keys for the t calls, such as : 
```
t('Welcome to the app')
```
Yes I know I'm not supposed to do this, but I find this way more efficient than to have to use identifiers and add English translation afterwards. Going back and forth from code to messages strings is annoying.
Other languages are then translated from english. That's how many CMS localization work.

But I sometimes need to use dots in the strings : 
```
t('Welcome to the app. Go to your profile to update your information.')
```
But doing so throws an error.

### Describe the solution you'd like

Remove the error, maybe some config to disable this check ?

### Describe alternatives you've considered

Not using dots :)

**Comment by amannn** [comment]
Hey! This is currently not planned, please see the previous discussions:
- https://github.com/amannn/next-intl/issues/453
- https://github.com/amannn/next-intl/discussions/148

> I find this way more efficient than to have to use identifiers and add English translation afterwards. Going back and forth from code to messages strings is annoying.

Have you considered using [the VSCode integration](https://next-intl-docs.vercel.app/docs/workflows/vscode-integration) that effectively enables showing the final translation string in your code?

**Comment by bfischer1121** [comment]
For anyone looking to achieve this, here's a function to adjust your translations when they're loaded by `getRequestConfig`:
```typescript
const getConfig = async (locale: string) => {
  const messages = (await import(`@/messages/${locale}.json`)).default

  const adjustKeys = (obj: Record<string, any>): Record<string, any> =>
    Object.fromEntries(
      Object.entries(obj).map(([key, value]) =>
        typeof value === 'string'
          ? [key.replaceAll('.', '_'), value]
          : [key, typeof value === 'object' && value !== null ? adjustKeys(value) : value]
      )
    )

  // periods are parsed as path separators by next-intl, so we need to replace
  // them with underscores both here and in the t function returned by useTranslations
  return { messages: adjustKeys(messages) }
}
```

and a hook that makes the same adjustment so the translation keys match up again:
```typescript
// eslint-disable-next-line no-restricted-imports
import { useTranslations as _useTranslations } from 'next-intl'
import { useMemo } from 'react'

// periods are parsed as path separators by next-intl, so we need to replace
// them with underscores both here and in getRequestConfig
export const useTranslations: typeof _useTranslations = (...args) => {
  const translateFn = _useTranslations(...args)

  return useMemo(() => {
    const proxyTranslateFn = new Proxy(translateFn, {
      apply(target, thisArg, argumentsList: Parameters<typeof translateFn>) {
        const [message, ...rest] = argumentsList
        return target.apply(thisArg, [message.replaceAll('.', '_') as typeof message, ...rest])
      }
    }) as typeof translateFn

    Reflect.ownKeys(translateFn).forEach(key => {
      const propertyDescriptor = Object.getOwnPropertyDescriptor(translateFn, key)

      if (propertyDescriptor) {
        Object.defineProperty(proxyTranslateFn, key, propertyDescriptor)
      }
    })

    return proxyTranslateFn
  }, [translateFn])
}
```

A bit of a hack, but should do the deed.
