### ISSUE TITLE
embedding support e.g. for static <ul>...</ul> lists

### ISSUE THREAD

**Issue by Tockra** [amannn/next-intl#911]
If I have a enumeration or something similar in html like:
```html
<ul>
  <li>First text</li>
  <li>Second text</li>
  <li>third text</li>
</ul>
```
I have to create 3 different keys in the language file and add them by hand to the tsx file.
Isn't there a better solution like giving something like a list into the language file and then just use it by a loop in the code to generate each <li> ?

or at least a embedding helper function, which receives a list of keys, so we have not write it by our own.

### Describe the solution you'd like

Provide a solution with dynamic arrays in the language file, which can be parsed through a loop in code.

E.g. language file:
```json
{
"list" : ["text1","text2","text3"]
}
```

Tsx file:
```tsx
...
return <ul>{tMapElems("list",(text) => {return <li>{text}</li>})} </ul>
```

Is similar to:
```html
<ul>
   <li>text1</li>
   <li>text2</li>
   <li>text3</li>
</ul>
```

### Describe alternatives you've considered

User adds all related keys manually but has at least a helping function to embed the stuff.
Giving the t or similar function a list of keys and a embedding function which embed them all:

e.g.
```tsx
...
const elements = tMap(["key1", "key2", "key3"], (text) => {return <li>{text}</li>})

return <ul>{elements}</ul>
```
Resulting in 
```html
<ul>
   <li>{t('key1')}</li>
   <li>{t('key2')}</li>
   <li>{t('key3')}</li>
</ul>

**Comment by amannn** [comment]
The "What if the amount of items varies depending on the locale?" expandable section in [the arrays of messages docs](https://next-intl-docs.vercel.app/docs/usage/messages#arrays-of-messages) should answer this question.

It was only added recently, have a look and see if that's helpful for you!

Further support for arrays is currently not planned, but I think that should work for your use case.
