### ISSUE TITLE
Automatically prefer localized pathnames that are more specific

### ISSUE THREAD

**Issue by Hdanzo** [amannn/next-intl#913]
### Description

When using localized pathnames and trying to access a page (/products/add) that is in the same folder as a dynamic page (/products/[productId]), the user is redirected to the dynamic page with the name of the static page as the param (productId = "add"). 

This however is fixable by ordering "/products/add" before "/products/[productId]" in the pathnames object.

If this behavior is the expected one and not something that's planned to be changed, I suggest this behavior to be stated in the documentation.

### Mandatory reproduction URL

https://codesandbox.io/p/devbox/xenodochial-hodgkin-3wj7ll?file=%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A94%2C11

### Reproduction description

Steps to reproduce:
1. Open reproduction.
2. Change locale to "es" in the URL.
3. Click on "Agregar" Link.
4. Get redirected to "/productos/[productId]" instead of "/productos/agregar"

### Expected behaviour

1. Open reproduction.
2. Change locale to "es" in the URL.
3. Click on "Agregar" Link.
4. Get redirected to "/productos/agregar" instead of "/productos/[productId]"

**Comment by amannn** [comment]
Thanks for this report, that's a great point!

I wonder if `next-intl` could automatically do the right thing here, Next.js is certainly capable of that.

This would need some further research on how routes can be ordered in a meaningful way. If I'm not mistaken, this is how Next.js does it: [`sorted-routes.ts`](https://github.com/vercel/next.js/blob/415cd74b9a220b6f50da64da68c13043e9b02995/packages/next/src/shared/lib/router/utils/sorted-routes.ts#L16). There's another related note in [`normalize-catchall-routes.ts`](https://github.com/vercel/next.js/blob/415cd74b9a220b6f50da64da68c13043e9b02995/packages/next/src/build/normalize-catchall-routes.ts#L20).

And this is where we need to apply it in `next-intl`:

https://github.com/amannn/next-intl/blob/419a9cea2817949b65b1af9724927b95d7d3bf01/packages/next-intl/src/middleware/utils.tsx#L21

I'll add a note about this to the docs for the time being but would be open to reviewing a PR here in case someone is interested in diving deeper into this.

**Comment by amannn** [comment]
Absolutely if you're interested, always a pleasure! 🙌
