### ISSUE TITLE
Link `href` doesn't update when search params change when `localePrefix` is set to `never`.

### ISSUE THREAD

**Issue by jorgemoya** [amannn/next-intl#918]
### Description

If a `Link` is present in a client component and the url depends on the existing `searchParams`, the url is not updated when the `searchParams` change. For some reason this happens when `createSharedPathnamesNavigation` is invoked with `localePrefix: "never"`, default value seems to work fine.

### Mandatory reproduction URL

https://codesandbox.io/p/github/jorgemoya/next-intl-bug-repro-app-router/main?import=true

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on `Foo` link
3. Hover over `Broken Link` and notice it doesn't include `foo=bar` search params when it should.

Alternate:
1. Open reproduction
2. Click on `Foo` link
3. Refresh page
4. Click on `Home` link
5. Hover over `Broken Link` and notice it does include `foo=bar` search params when it shouldn't.

### Expected behaviour

The expected behavior would be for the `Broken Link` link the match the search params present, even after they update.

**Comment by amannn** [comment]
I can unfortunately not follow your reproduction steps in the provided reproduction, seems like the template is unchanged. Any chance you didn't commit the latest changes?

**Comment by jorgemoya** [comment]
> I can unfortunately not follow your reproduction steps in the provided reproduction, seems like the template is unchanged. Any chance you didn't commit the latest changes?

Yes, you're correct, should work now. Sorry about that. 🙏

**Comment by amannn** [comment]
This is fixed in `next-intl@3.9.4`!

Thank you so much for taking the time to build a great reproduction, that helped a lot with finding the cause and fixing it!
