### ISSUE TITLE
[Docs]: Internationalization of Metadata & Route Handlers with the Next.js App Router

### ISSUE THREAD

**Issue by patrycjalazna** [amannn/next-intl#919]
### Link to page

https://next-intl-docs.vercel.app/docs/environments/metadata-route-handlers

### Describe the problem

There's an issue with the Metadata API - `useTranslations` is shown in VS Code as deprecated, and there's no documentation provided for `getTranslator` as it's proposed.

**Comment by amannn** [comment]
Sorry, I can't follow. Can you elaborate on what the issue is and maybe include some screenshots?
