### ISSUE TITLE
IDE displays "i18n-ally-key-missing" when using getTranslations

### ISSUE THREAD

**Issue by manu-kz** [amannn/next-intl#922]
### Description

I recently updated to latest version of next intl so I had to change from getTranslator to getTranslations. 
Everything works great on my website, but an issue remains in VS Code. After I made the change, my IDE is throwing an error saying that the i18n key does not exists (even if it does and the correct text is displayed on my website). I attached a screenshot to illustrate. 
I also tried to change {t("contactForm.title")} with {t("Footer.contactForm.title")}, in that case the error disappears but in that case the text is not displayed on the website, instead it displays as expected Footer.Footer.contactForm.title
I can't find any solution to this issue, even if it is non blocking I would like to fix it because my code is now full of warnings and I can't go direclty to the text anymore by clicking on the arrow.

I am using VS Code 1.87.0. TypeScript version 5.2.2. Next.js version 14.1.0 and next-intl 3.9.2 (previously using 3.0.0-rc.7).

![Capture d'écran 2024-03-07 113146](https://github.com/amannn/next-intl/assets/128033919/6b7d8a36-53c0-4e97-9615-abe045c5ceb5)

### Mandatory reproduction URL

not available

### Reproduction description

No reproduction possible as it is a warning in the IDE

### Expected behaviour

To not throw an error if there is not

**Comment by amannn** [comment]
Yep, this is currently waiting to get merged on the i18n ally side: https://github.com/lokalise/i18n-ally/pull/1048

**Comment by ScreamZ** [comment]
Ups, read that a bit late ahah thanks
