### ISSUE TITLE
Translated dynamic slugs not documented, next-intl not aware of the translation

### ISSUE THREAD

**Issue by Micu22** [amannn/next-intl#929]
### Description

When using dynamic routes (slugs) next-intl is not aware of the translations, uses same (main slug) on all language versions.
There is no documentation on how this should be achieved. This is basic behavior of multilingual sites.

How can I achieve this, and make it easier for others in the future?

### Mandatory reproduction URL

[Link](https://codesandbox.io/p/github/Micu22/slugs-dynamic-next-intl/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltlsm0i500063j6g6wgcnezx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltlsm0i500023j6gs3g0coei%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltlsm0i500043j6glegmhe12%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltlsm0i500053j6gwvgy4bf5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltlsm0i500023j6gs3g0coei%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltlsm0i400013j6gt36cs9su%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cltlsm0i500023j6gs3g0coei%2522%252C%2522activeTabId%2522%253A%2522cltlsm0i400013j6gt36cs9su%2522%257D%252C%2522cltlsm0i500053j6gwvgy4bf5%2522%253A%257B%2522id%2522%253A%2522cltlsm0i500053j6gwvgy4bf5%2522%252C%2522activeTabId%2522%253A%2522cltlsmra7009n3j6ga312bjhz%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cltlsmra7009n3j6ga312bjhz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fen%252Fsolutions%252Fulotka%2522%257D%255D%257D%252C%2522cltlsm0i500043j6glegmhe12%2522%253A%257B%2522id%2522%253A%2522cltlsm0i500043j6glegmhe12%2522%252C%2522activeTabId%2522%253A%2522cltlsmolt007j3j6g5s041o09%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltlsm0i500033j6g3cd6j3gp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltlsm1ba000vdkhzb0kl2seb%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltlsmolt007j3j6g5s041o09%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on the only link visible, then switch between languages using the language switcher buttons, observe that next-intl is not aware of the translated slug.
When on link: /pl/rozwiazania/flyer
Clicking the language switcher sends to /en/solutions/flyer
NOTICE: both slugs are 'flyer' they aren't using the translated slug (polish for flyer is ulotka)
you can click the hard-coded links that will take you to the right slugs below, but again same issue with the switcher happens there again.

The docs do not explain how to approach a situation like this. Even though they go through dynamic slugs quite a bit, this is quite strange to me, because if we have dynamic slugs wouldn't it be straight-forward that there would be a need to translate them too?

What I tried:
Generating the pathnames variable dynamically in navigation.ts: couldn't make it work, the app never loaded when pathnames was reliant on a promise.

### Expected behaviour

Make next-intl translated slugs AWARE.
When the slugs defined in the CMS are: flyer (for 'en') and ulotka (for 'pl'). Make the system switch to the correct url. 

How?
1. By being able to generate the pathnames variable dynamically based on what we have in the CMS.
2. OR
3. By knowing how to extend the languageSwitcher so that it knows how to overcome the dynamic pathnames limitation.

**Comment by amannn** [comment]
I've added a note on this to the middleware docs in https://github.com/amannn/next-intl/commit/48950b844eeb4995a57db749fd57035b8352578c, hope this helps!

**Comment by mnemosx** [comment]
@Micu22 
Hi! Did you come up with a solution that worked for you?

**Comment by mnemosx** [comment]
> The other solution would be to make your language switcher pathname-aware, potentially incorporating a localized slug if the user is currently on the `solutions` page.

Could you please elaborate on this a bit please? Our language switcher must know all the variations for current dynamic slug (blog post in my case) in order to update the path right away. As far as I understand, it can only get that data either from some sort of global store where blog post page stored it or by fetching all posts and filtering through them to find the right slug (each post comes with all the slugs for all locales). Both options seem unattractive to me. As does self-healing URLs for different reasons.

So I'd love to better understand what was your idea there

**Comment by krystiangryczon** [comment]
I believe the solution lies [here](https://next-intl-docs.vercel.app/docs/routing/middleware#example-additional-rewrites).
In my case cms also holds translated_slugs object along with the page data. I'm making request to the cms in app dir to get the data (I want to dynamically build pages based on what's in cms). My thinking is I could make a request to the cms in the middleware too and in theory it should be deduplicated by next 🤔 (unsure whether the one on the server and the one in middleware will be treated as the same). 
 Tho I did not yet manage to make it work in my own setup.

**Comment by leon2811-be** [comment]
Hey @Micu22,

I found a solution to get it to work: 
1. I created a LanguageSwitcher.tsx component:


'use client';

import React, { useEffect, useState } from 'react';
import { useRouter, useParams } from 'next/navigation';

interface Localization {
    locale: string;
    slug: string;
}

const LanguageSwitcher = ({ localizations }: { localizations: Localization[] }) => {
    const router = useRouter();
    const currentParams = useParams();
    const [currentLocale, setCurrentLocale] = useState<string>(currentParams?.locale as string || 'en');
    const currentSlug = localizations.find(loc => loc.locale === currentLocale)?.slug || '';

    const otherLocales = localizations.filter(loc => loc.locale !== currentLocale);

    useEffect(() => {
        // Update the document's lang attribute
        document.documentElement.lang = currentLocale;

        // Update URL when the locale changes
        router.push(`/${currentLocale}/blog/post/${currentSlug}`);
    }, [currentLocale, currentSlug, router]);

    const handleLocaleChange = (locale: string) => {
        setCurrentLocale(locale); // Update current locale state
    };

    return (
        <div>
          
        </div>
    );
};

export default LanguageSwitcher;


2. Then added the component like this to my page.tsx where my page.tsx is in /post/[slug] : 
<LanguageSwitcher localizations={localizations} />

**Comment by about-daniel** [comment]
Hi everyone,
I encountered a similar issue where I needed to dynamically translate slugs for certain post paths. 

For example:
English: /news/this-is-number-1
Italian: /notizia/questo-è-il-numero-1

### Implemented Solution:

I was able to solve this problem by implementing a custom middleware that fetches all posts before passing the paths to the next-intl middleware. Here’s how I did it:

- Fetch Localized Posts:
I created a function called getLocalized that retrieves the localized data for the posts. I use this function within the middleware to fetch all posts.

- Generate Translated Paths:
I use the generatePathnames function to generate localized paths for the posts based on language prefixes and translated slugs.

- Optional Post Prefixes:
I introduced the postPrefixes variable to indicate whether a prefix is needed before the slug, such as /news for /news/this-is-number-1. 
Here’s an example structure:
```
const postPrefixes = { 
  en: "/news", 
  it: "/notizia" 
};
```
- Pathnames Structure:
After using my utility functions getLocalized and generatePathnames, I have a list of pathnames structured like this:
```
{
  "/news/this-is-number-1": {
    it: "/notizia/questo-è-il-numero-1",
    en: "/news/this-is-number-1",
  },
}
```
_Note: I created these functions for convenience, but once you obtain all dynamic posts via an API call, you can create a list of pathnames with this structure to add to your static pathnames._

- Assign Dynamic Paths:
I use Object.assign(pathnames, postPathname) to add the new generated paths to the static paths defined in the configuration.

- Integration with next-intl:
I pass everything to the next-intl middleware to handle the international routing logic.

**Here is the middleware code:**

```
import createMiddleware from "next-intl/middleware";
import {
  postPrefixes,
  defaultLocale,
  localePrefix,
  locales,
  pathnames,
} from "./i18n";
import { getLocalized, generatePathnames } from "./helpers/api/api-helpers";

export default async function middleware(request) {
  const posts = await getLocalized("posts");
  const postsPathnames = generatePathnames(posts, postPrefixes);

  postsPathnames.forEach((postPathname) => {
    Object.assign(pathnames, postPathname);
  });

  const handleI18nRouting = createMiddleware({
    locales: locales,
    defaultLocale: defaultLocale,
    localePrefix: localePrefix,
    pathnames: pathnames,
  });
  const response = handleI18nRouting(request);
  return response;
}

export const config = {
  matcher: [
    "/((?!api|_next|_vercel|.*\\..*).*)",
    "/([\\w-]+)?/users/(.+)",
  ],
};
```

**Comment by mupinnn** [comment]
Thank you @about-daniel, it works nicely. But I found some quirks with the pathname matching.

Consider this pathname:
```js
{
  "/news/this-is-number-1": {
    it: "/notizia/questo-è-il-numero-1",
    en: "/news/this-is-number-1",
  },
}
```

It will correctly redirect to the selected locale when switching the locale, but the `[slug]` param remains the English one. I think it is because the path property that is defined is the same as the English.

If we try to switch it like this, it will do the opposite:
```js
{
  "/notizia/questo-è-il-numero-1": {
    it: "/notizia/questo-è-il-numero-1",
    en: "/news/this-is-number-1",
  },
}
```

If we try to put both, the `[slug]` will take the first precedence/match from the pathnames. In this case, the English `[slug]`
```js
{
  "/news/this-is-number-1": {
    it: "/notizia/questo-è-il-numero-1",
    en: "/news/this-is-number-1",
  },
  "/notizia/questo-è-il-numero-1": {
    it: "/notizia/questo-è-il-numero-1",
    en: "/news/this-is-number-1",
  },
}
```

Is it expected behavior @amannn?

**Comment by michaelroth-xx** [comment]
Thank you @about-daniel for you idea. I was able to implement it so the pathnames have dynamic entries from the cms with that! Unfortunately I still got a problem.

This is how the pathnames look like after the assign in the middleware:
```
{
  // static defined pathnames in i18 nconfig
  "/imprint": { "en": "/imprint", "de": "/impressum" },
  ...
  // dynamically added pathnames in middleware
  "/english-slug": { "en": "/english-slug", "de": "/deutscher-slug" },
  ...
}
```

If i switch the language on e.g. "en/english-slug" to german the url in the browser changes correctly to "de/deutscher-slug" 

But whats odd is, that the slug that i get from the params object in the NextJS 14 (app router) component still is the identifier, not the translated value.

```
// app/[locale]/[[...slug]]/page.tsx
export default async function ContentPage({
    params: { slug, locale },
}: Readonly<HomeProps>) {
    setRequestLocale(locale)
    console.log(locale, slug) // => de [ 'english-slug' ]
    ...
}
```

Any idea what I might missing here?

**Comment by about-daniel** [comment]
@mupinnn @michaelroth-xx 
I’ve encountered the same issue where the slug remains in the original language during a language switch. Like you, I wasn’t sure of the underlying cause of this problem. Perhaps @amannn could provide some guidance on this matter!

However, I managed to work around the problem using a few additional tricks:

### Generating Static Parameters:

I used the following function to fetch all dynamic posts, retrieving only the slug in the default language (in my case, English). I then ensure that each locale in my project (English, Italian in my case) is associated with the slug in the original language.

```
import { defaultLocale, locales } from "@/i18n";

export async function generateStaticParams() {
  const posts = await fetchAPI("/posts", {
    "fields[0]": "Slug",
    locale: defaultLocale,
  });
  const staticParams = posts.flatMap((post) => {
    const ret = locales.map((l) => {
      return {
        slug: post.attributes.Slug,
        locale: l,
      };
    });
    return ret;
  });
  return staticParams;
}
```

With this function, I fetch all dynamic posts using only the slug in the default language. I then enforce that the function returns a structure where each locale in my project is linked to the original language slug. The translation of the slugs is used solely in the middleware for route renaming, while the fetch logic consistently employs the slug in the default language.

### Fetching Translated Content:

For obtaining the translated content in the current language, I always fetch by the slug in the default language. I use Strapi as my CMS, which also returns the translated content. If the language is different from the default, I search the response for the translation in the current language, retrieve the translated slug, and then fetch the translated content using this slug.

```
export async function getSingleBySlug(path, Slug, locale) {
  let ret = null;
  let urlParamsObject = {};
  if (locale == defaultLocale) {
    urlParamsObject = {
      "filters[Slug][$eq]": Slug,
      populate: "deep",
      locale: locale,
    };
    const response = await fetchAPI(path, urlParamsObject);
    ret = response[0];
  } else {
    urlParamsObject = {
      "filters[Slug][$eq]": Slug,
      populate: "localizations",
    };
    const response = await fetchAPI(path, urlParamsObject);
    const localizations = response[0].attributes.localizations.data;
    const localization = localizations.find(
      (loc) => loc.attributes.locale === locale
    );
    if (localization) {
      const translatedSlug = localization.attributes.Slug;
      const translatedSingle = await fetchAPI(path, {
        "filters[Slug][$eq]": translatedSlug,
        populate: "deep",
        locale: locale,
      });
      ret = translatedSingle[0];
    }
  }
  return ret;
}
```

It’s not the clearest or cleanest logic, but it works and allowed me to bypass the issue.

If anyone has a better solution or further insights, please share!

**Comment by amannn** [comment]
Thanks for chiming in here everyone, here are a few notes I made while reading your comments:

**How do localized pathnames map to routes in your app?**

> But whats odd is, that the slug that i get from the params object in the NextJS 14 (app router) component still is the identifier, not the translated value.

That's expected, yes. See this note in the [localized pathnames](https://next-intl-docs.vercel.app/docs/routing#pathnames) docs:

> Localized pathnames map to a single internal pathname that is created via the file-system based routing in Next.js.

**How do I integrate `pathnames` with a CMS?**

Maybe the docs were not clear in this regard previously, but I'd really recommend to _not_ provide the `pathnames` configuration for `next-intl` based on data from a CMS. If you merge dynamically fetched localized pathnames into statically-defined pathnames, this asks for trouble (the middleware might not share the runtime with where your pages are rendered, e.g. Edge vs Node.js).

`pathnames` is really intended to define statically known routes, esp. if you don't have a CMS which takes care of providing localized slugs, or at least for the routes which _are_ known statically.

I've tried to clarify the docs somewhat here: https://github.com/amannn/next-intl/commit/04f935650460c9c6f20ffef8c35fc680ad14aa73

Hope this is helpful!

**Comment by about-daniel** [comment]
> Thanks for chiming in here everyone, here are a few notes I made while reading your comments:
> 
> **How do localized pathnames map to routes in your app?**
> 
> > But whats odd is, that the slug that i get from the params object in the NextJS 14 (app router) component still is the identifier, not the translated value.
> 
> That's expected, yes. See this note in the [localized pathnames](https://next-intl-docs.vercel.app/docs/routing#pathnames) docs:
> 
> > Localized pathnames map to a single internal pathname that is created via the file-system based routing in Next.js.
> 
> **How do I integrate `pathnames` with a CMS?**
> 
> Maybe the docs were not clear in this regard previously, but I'd really recommend to _not_ provide the `pathnames` configuration for `next-intl` based on data from a CMS. If you merge dynamically fetched localized pathnames into statically-defined pathnames, this asks for trouble (the middleware might not share the runtime with where your pages are rendered, e.g. Edge vs Node.js).
> 
> `pathnames` is really intended to define statically known routes, esp. if you don't have a CMS which takes care of providing localized slugs, or at least for the routes which _are_ known statically.
> 
> I've tried to clarify the docs somewhat here: [04f9356](https://github.com/amannn/next-intl/commit/04f935650460c9c6f20ffef8c35fc680ad14aa73) (see: [How do I integrate with an external system like a CMS that provides localized pathnames?](https://next-intl-docs.vercel.app/docs/routing#localized-pathnames-cms))
> 
> Hope this is helpful!

Thank you @amannn! So you mean to put a dynamic segment in pathnames like this?
```
"[locale]/case-studies/[...slug]": {
    it: "[locale]/case-studies/[...slug]",
    en: "[locale]/case-studies/[...slug]",
    fr: "[locale]/etudes-de-cas/[...slug]",
  },
```

Or do you mean something different?

**Comment by amannn** [comment]
Yep, that looks good to me!

**Comment by amannn** [comment]
You can also use parallel routes to achieve localized slugs, I've left a comment here: https://github.com/amannn/next-intl/discussions/1740#discussioncomment-12313889
