### ISSUE TITLE
Help with implementing next-intl in a project with typescript

### ISSUE THREAD

**Issue by ishigami** [amannn/next-intl#94]
Hello @amannn. Good morning!

First of all, thanks for your wonderful package.

Well, I'm newbie in typescript and I'm facing some VS Code warnings when I use the "t" function. The parameter shows a underline and the following message:

`Argument of type 'string' is not assignable to parameter of type 'never'`

![image](https://user-images.githubusercontent.com/2190465/159911306-7ff5fe59-98d9-411a-923c-31d7e5ff7f6c.png)

I know that is not a bug, but I don't know how to deal with this.

I will appreciate your help, if you can.

And thank you so much for your understanding.

**Comment by amannn** [comment]
Hello @ishigami,

this is in fact really not an issue on your side but I accidentally published a prelease to the main release channel. You're likely using version 2.4.1-alpha.1 currently which has this bug.

I've just released 2.4.1 which doesn't have this bug. Please upgrade and let me know if the issue is gone!

**Comment by amannn** [comment]
Oh wow, thank you so much for your sponsoring! ❤️❤️❤️ That's really kind of you, I really appreciate it 🙂.

Have a good day and definitely let me know if you happen to run into something else!

**Comment by hbendix** [comment]
I seem to have this very issue on `"^2.10.2"` - any ideas @amannn ?

**Comment by amannn** [comment]
@hbendix Thanks for reaching out! Can you please open a new bug report and provide a reproduction of the issue you are seeing? The bug that was mentioned above has been resolved.
