### ISSUE TITLE
Path rewriting does not work for the home page

### ISSUE THREAD

**Issue by ponjs** [amannn/next-intl#940]
### Description

I'm rewriting `/about` as `/` but when I visit the `/` page, the url address bar is `/about`

https://github.com/amannn/next-intl/assets/39897744/d274635e-f168-4525-8b17-b696549a26ac

### Mandatory reproduction URL

https://stackblitz.com/edit/stackblitz-starters-nwjigc?file=src%2Fmiddleware.ts

### Reproduction description

Visit stackblitz's open prview in new tab and visit `/` page

### Expected behaviour

When the `/` page is accessed, the page is a `/about` page, but the url is still the `/` page.

**Comment by amannn** [comment]
For the record, navigating to a locale root works as expected:

![Screenshot 2024-03-15 at 10 42 34](https://github.com/amannn/next-intl/assets/4038316/d659ca08-4b01-432f-88b6-1663982d1363)

So as far as I understand the issue, this is about the location that's picked when there's a locale-specific redirect at the root:

![Screenshot 2024-03-15 at 10 43 12](https://github.com/amannn/next-intl/assets/4038316/9b004773-bab2-480a-bbea-0e0f40f81d01)

As a workaround, you can consider adding your own redirect at the root in the middleware, but I think it would be helpful to investigate wether there's something to address here in `next-intl`.

**Comment by amannn** [comment]
I've refactored the middleware handling somewhat in #1086 and have added a test for your use case. Should work in the future after the PR is merged!
