### ISSUE TITLE
Generating static pages with localized pathnames

### ISSUE THREAD

**Issue by ehuelsda** [amannn/next-intl#943]
### Description

I'm using localized pathnames in my project and want to generate the routes as static pages. However, the resulting routes keep the same pathname in both locales. 

### Mandatory reproduction URL

https://github.com/ehuelsda/next-intl-localized-pathnames-static-pages/tree/main

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Either clone and run 'npm run build' or look into the .next/server/app folder
3. See that no/articles was created instead of no/artikler

### Expected behaviour

Localized pathnames are respected and the routes /no/artikler and /en/articles are created.

**Comment by TMF42** [comment]
On a side note, due to this also canonicals set via the metadata API with "./" are incorrect.
