### ISSUE TITLE
Importing Messages during runtime

### ISSUE THREAD

**Issue by EliasVal** [amannn/next-intl#971]
### Is your feature request related to a problem? Please describe.

In the company I am working at, we have a centralized directory of translations: `C:/.../Translation` 

Combining `NextIntlClientProvider` with React state for the messages works fine, but it fails with `i18n.ts`.

### Describe the solution you'd like

A way to import files during runtime from a path outside the project folder

### Describe alternatives you've considered

*

**Comment by amannn** [comment]
I unfortunately don't know what `next-intl` can do to help here. `i18n.ts` is generally agnostic to where you fetch your messages from, but we recommend dynamically importing messages from a local path in the project. You can also fetch translations from a TMS, in the end you just have to return `messages` from an async function.

I don't know what problem you're practically experiencing, but sounds more like a Next.js bug possibly? In case you find that importing translations from that path generally works in a Next.js app but not in combination with `next-intl`, then please open a bug with a reproduction.

**Comment by EliasVal** [comment]
Hey, @amannn
I managed to work my way around it all, for the `i18n.ts` translations, I switched the `import` call to `fs.readFile` (with `JSON.parse`).
And for the NextIntlClientProvider I made a symlink in my public folder to the translation files.
