### ISSUE TITLE
Prevent useTranslations being triggered on prefetch

### ISSUE THREAD

**Issue by brandanking-decently** [amannn/next-intl#978]
### Is your feature request related to a problem? Please describe.

When hovering over a link on production that prefetches, useTranslation is triggered causing a rerender of the client component that it is in.

### Describe the solution you'd like

Prevent useTranslation causing a rerender on prefetching of future link

### Describe alternatives you've considered

Temporarily disabled prefetching

**Comment by amannn** [comment]
`useTranslations` doesn't have anything to do with prefetching, there might be a bug in your app code. If you think you've found a bug, then you're welcome to submit a bug report, but I'd assume the bug to be in the app code.
