### ISSUE TITLE
Support regional information in `select` arguments

### ISSUE THREAD

**Issue by aminahbl** [amannn/next-intl#984]
### Is your feature request related to a problem? Please describe.

The `next-intl` [terminology documentation](https://next-intl-docs.vercel.app/docs/usage/messages#terminology) indicates that regional locales and message files are permitted. However, `t`'s [`select` argument ](https://next-intl-docs.vercel.app/docs/usage/messages#selecting-enum-based-values) doesn't seem to support values with hyphens. 

If, for example, I have the following in my message files: 

```json
"localeSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, bo {བོད་སྐད་དུ།} en {English} zh {简体中文} zh-Hans {繁體中文} other {Unknown}}"
 }
```

I get an error:

```
{
  code: 'INVALID_MESSAGE',
  originalMessage: 'DUPLICATE_SELECT_ARGUMENT_SELECTOR ({locale, select, bo {བོད་སྐད་དུ།} en {English} zh {简体中文} zh-Hant {繁體中文} other {Unknown}})'
}
```

### Describe the solution you'd like

I would like the `select` argument to be able to accept a value that contains a hyphen. 

### Describe alternatives you've considered

At the moment I'm using the following workaround, but if feels a bit brittle. 

```js
{t("locale", { locale: currentLocale === "zh-Hant" ? "zhHant" : currentLocale })}
```

```json
"localeSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, bo {བོད་སྐད་དུ།} en {English} zh {简体中文} zhHant {繁體中文} other {Unknown}}"
}
```

**Comment by amannn** [comment]
In the "Which characters are supported for select values?" expandable section of the [selecting enum-based values docs](https://next-intl-docs.vercel.app/docs/usage/messages#selecting-enum-based-values) is an example just for this use case. Hope this helps!
